/**
 * @scopeblind/protect-mcp — Cedar Policy Evaluator (Local WASM)
 *
 * Evaluates Cedar policies locally using @cedar-policy/cedar-wasm.
 * No external server required. Same deterministic evaluation as
 * AWS Verified Permissions / AgentCore Policy.
 *
 * Cedar is loaded as an optional dependency — if the WASM module
 * isn't installed, this module exports stubs that return fallback decisions.
 */

import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join, extname } from 'node:path';
import type { ExternalDecision, TrustTier } from './types.js';
import { digestPolicyFiles, digestCedarSource } from './policy-digest.js';

// ============================================================
// Types
// ============================================================

export interface CedarPolicySet {
  /** Raw concatenated Cedar source */
  source: string;
  /** "sha256:<64 hex>" under acta-policy-digest-v1 (see policy-digest.ts) */
  digest: string;
  /** Number of individual .cedar files loaded */
  fileCount: number;
  /** Filenames loaded */
  files: string[];
}

export interface CedarEvalRequest {
  /** Tool name being called */
  tool: string;
  /** Trust tier of the agent */
  tier: TrustTier;
  /** Agent ID (optional) */
  agentId?: string;
  /** Additional context fields */
  context?: Record<string, unknown>;
  /** Tool input (for schema-validated evaluation) */
  /**
   * Which Cedar action the tool call is evaluated as. 'mcp' (default) is the
   * runtime model: Action::"MCP::Tool::call" with the tool as the resource.
   * 'tool' uses the tool name itself as the action (Action::"Bash"), which is
   * the model the published conformance policy in
   * agent-governance-testvectors/fixtures/policy is written against.
   */
  actionModel?: 'mcp' | 'tool';
  toolInput?: Record<string, unknown>;
}

/** Cedar schema for typed policy evaluation (generated by cedar-schema.ts) */
export interface CedarSchema {
  /** The schema as a JSON object for Cedar WASM */
  schemaJson: Record<string, unknown> | null;
  /** Namespace used in the schema */
  namespace?: string;
}

// ============================================================
// WASM module (lazily loaded)
// ============================================================

let cedarWasm: any | null = null;
let loadAttempted = false;
let cedarWasmSpecifier: string | null = null;
let cedarWasmLoadError: string | null = null;

/**
 * The package root of @cedar-policy/cedar-wasm resolves to its ESM build, whose
 * entry imports the .wasm binary as an ES module. Node 22 accepts that (behind
 * an experimental warning); Node 18 and 20 reject it with
 * ERR_UNKNOWN_FILE_EXTENSION, and until 0.13.1 that rejection was swallowed and
 * every evaluation became a fail-closed deny labelled cedar_wasm_not_available.
 * The package's /nodejs entry loads the binary through fs and works on every
 * supported Node, so it is tried first; the root is the fallback for bundlers.
 */
const CEDAR_WASM_SPECIFIERS = ['@cedar-policy/cedar-wasm/nodejs', '@cedar-policy/cedar-wasm'];

/**
 * Attempt to load the Cedar WASM module.
 * Returns true if successful, false if it could not be loaded; the reason is
 * kept for the decision that reports it.
 */
async function ensureCedarWasm(): Promise<boolean> {
  if (cedarWasm) return true;
  if (loadAttempted) return false;
  loadAttempted = true;

  const errors: string[] = [];
  for (const moduleName of CEDAR_WASM_SPECIFIERS) {
    try {
      const mod = await import(/* @vite-ignore */ moduleName);
      const engine = mod && (mod.default || mod);
      if (!engine || typeof engine.isAuthorized !== 'function') {
        errors.push(`${moduleName}: loaded but has no isAuthorized`);
        continue;
      }
      cedarWasm = mod;
      cedarWasmSpecifier = moduleName;
      return true;
    } catch (err) {
      const msg = err instanceof Error ? `${(err as any).code ? (err as any).code + ' ' : ''}${err.message.split('\n')[0]}` : String(err);
      errors.push(`${moduleName}: ${msg}`);
    }
  }
  cedarWasmLoadError = errors.join('; ');
  return false;
}

/** Which specifier the engine loaded from, and why it did not, for diagnostics and tests. */
export function getCedarWasmLoadInfo(): { loaded: boolean; specifier: string | null; error: string | null } {
  return { loaded: Boolean(cedarWasm), specifier: cedarWasmSpecifier, error: cedarWasmLoadError };
}

// ============================================================
// Policy loading
// ============================================================

/**
 * Load all .cedar files from a directory and return a compiled policy set.
 *
 * Files are sorted alphabetically for deterministic digest computation.
 * Throws if the directory doesn't exist or contains no .cedar files.
 */
export function loadCedarPolicies(dirPath: string): CedarPolicySet {
  if (!existsSync(dirPath)) {
    throw new Error(`Cedar policy directory not found: ${dirPath}`);
  }

  const entries = readdirSync(dirPath)
    .filter((f) => extname(f) === '.cedar')
    .sort();

  if (entries.length === 0) {
    throw new Error(`No .cedar files found in: ${dirPath}`);
  }

  const files: Array<{ name: string; content: string }> = [];
  for (const file of entries) {
    files.push({ name: file, content: readFileSync(join(dirPath, file), 'utf-8') });
  }

  // Concatenation is for EVALUATION only. The digest is the normative
  // acta-policy-digest-v1 construction (per-file hashes, no concatenation),
  // so the commitment a receipt carries is recomputable from published bytes.
  const concatenated = files.map((f) => f.content).join('\n\n');
  const digest = digestPolicyFiles('cedar', files).policy_digest;

  return {
    source: concatenated,
    digest,
    fileCount: entries.length,
    files: entries,
  };
}

// ============================================================
// Entity construction helpers
// ============================================================

/**
 * Build the Cedar entities array for a tool call evaluation.
 *
 * Entity model:
 *   Principal: Agent::"<tier>" (or Agent::"<agentId>" if known)
 *   Action:    Action::"MCP::Tool::call" (or Action::"<toolName>" when actionModel is 'tool')
 *   Resource:  Tool::"<toolName>"
 */
function buildEntities(req: CedarEvalRequest): Array<Record<string, unknown>> {
  const agentId = req.agentId || req.tier;
  return [
    {
      uid: { type: 'Agent', id: agentId },
      attrs: {
        tier: req.tier,
        ...(req.agentId ? { agent_id: req.agentId } : {}),
      },
      parents: [],
    },
    {
      uid: { type: 'Tool', id: req.tool },
      attrs: {},
      parents: [],
    },
  ];
}

// ============================================================
// Inputs Cedar can hold
// ============================================================

/** Keys Cedar's JSON format reads as typed escapes rather than data. */
const CEDAR_ESCAPE_KEYS = new Set(['__entity', '__extn', '__expr']);
/** Cedar's Long is a signed 64-bit integer; the engine refuses a whole number at or beyond 2^63 either way. */
const CEDAR_LONG_LIMIT = 2 ** 63;

/**
 * A value as Cedar can hold it. Cedar has no null, no fractions and no integers
 * beyond 64 bits, and the engine refuses the whole request when the context
 * carries one, so before 0.31.0 a single `"zoom": 1.5` denied the call under
 * every policy, permit-all included. Here a null (or undefined) is dropped, in a
 * list as in a record; a whole number inside Cedar's Long range stays a number;
 * any other number becomes the string JavaScript writes for it (1.5 becomes
 * "1.5", 1e20 becomes "100000000000000000000"); and the `__entity`, `__extn` and
 * `__expr` keys are dropped, so tool input is never read as a Cedar entity
 * reference or extension value. Strings and booleans pass unchanged. Returns
 * undefined for a value that is dropped.
 */
export function cedarSafeValue(value: unknown): unknown {
  if (value === null || value === undefined) return undefined;
  switch (typeof value) {
    case 'string':
    case 'boolean':
      return value;
    case 'number':
      return Number.isInteger(value) && Math.abs(value) < CEDAR_LONG_LIMIT ? value : String(value);
    case 'bigint':
      return value >= BigInt(Number.MIN_SAFE_INTEGER) && value <= BigInt(Number.MAX_SAFE_INTEGER) ? Number(value) : value.toString();
    case 'object': {
      if (Array.isArray(value)) {
        const items: unknown[] = [];
        for (const item of value) {
          const safe = cedarSafeValue(item);
          if (safe !== undefined) items.push(safe);
        }
        return items;
      }
      const record: Record<string, unknown> = {};
      for (const [key, item] of Object.entries(value as Record<string, unknown>)) {
        if (CEDAR_ESCAPE_KEYS.has(key)) continue;
        const safe = cedarSafeValue(item);
        // Defined, not assigned: a "__proto__" key in the input stays an ordinary
        // field, as JSON.parse made it, instead of becoming the record's prototype.
        if (safe !== undefined) Object.defineProperty(record, key, { value: safe, enumerable: true, writable: true, configurable: true });
      }
      return record;
    }
    default:
      return undefined;
  }
}

/** A request context as Cedar can hold it (see cedarSafeValue). */
export function cedarSafeContext(context: Record<string, unknown>): Record<string, unknown> {
  return cedarSafeValue(context) as Record<string, unknown>;
}

// ============================================================
// Rules by name
// ============================================================

interface PolicyName {
  /** The id the decision reports: the rule's @id, or Cedar's positional policyN. */
  id: string;
  /** The rule's @reason annotation, on one line. */
  reason?: string;
  /** Position in the policy text, so several matched rules are reported in source order. */
  order: number;
}

interface PreparedPolicies {
  /** What the engine evaluates: the text itself, or one entry per rule keyed by its name. */
  staticPolicies: string | Record<string, string>;
  names: Map<string, PolicyName>;
}

const preparedPolicies = new Map<string, PreparedPolicies>();
const PREPARED_CACHE_LIMIT = 32;

/** Collapse a text to one line and bound it, for reasons that reach stderr and receipts. */
function oneLine(text: string, max = 400): string {
  const line = text.replace(/\s+/g, ' ').trim();
  return line.length > max ? `${line.slice(0, max - 3)}...` : line;
}

/**
 * Key each rule by its `@id`, so a decision names the rule that made it instead
 * of Cedar's positional "policy2", and keep its `@reason` for the deny.
 * cedar-wasm's policySetTextToParts splits the text into one verbatim slice per
 * rule, sorted by the positional ids the parser gave them (policy0, policy1,
 * policy10, policy11, policy2, ... as strings), so position k of the parts is
 * the k-th of those ids in string order. A rule without an @id, or one whose @id
 * repeats, looks positional or is "__proto__", keeps its positional id.
 * Evaluation is unchanged: the same rules, word for word, under names. A text
 * the engine cannot split (or one with templates, or parts that are not
 * verbatim slices, or any rule that would not get its own key) is evaluated
 * whole, as before, and its rules report positional ids.
 */
function preparePolicies(engine: any, source: string): PreparedPolicies {
  const cached = preparedPolicies.get(source);
  if (cached) return cached;
  let prepared: PreparedPolicies = { staticPolicies: source, names: new Map() };
  try {
    if (typeof engine?.policySetTextToParts === 'function' && typeof engine?.policyToJson === 'function') {
      const parts = engine.policySetTextToParts(source);
      const texts: unknown = parts?.policies;
      const templates: unknown = parts?.policy_templates;
      // Only verbatim slices of the source are evaluated by name: if an engine
      // ever returned rewritten text, the rules would no longer be the ones written.
      if (parts?.type === 'success' && Array.isArray(texts) && texts.length > 0 && (!Array.isArray(templates) || templates.length === 0)
        && texts.every((text) => typeof text === 'string' && source.includes(text))) {
        const positional = texts.map((_, i) => `policy${i}`).sort();
        const annotations = texts.map((text) => {
          const json = engine.policyToJson(text);
          return json?.type === 'success' ? ((json.json?.annotations ?? {}) as Record<string, unknown>) : null;
        });
        if (annotations.every((a) => a !== null)) {
          const idOf = (a: Record<string, unknown> | null): string => (a && typeof a.id === 'string' ? a.id : '');
          const counts = new Map<string, number>();
          for (const a of annotations) {
            const id = idOf(a);
            if (id) counts.set(id, (counts.get(id) || 0) + 1);
          }
          const keyed: Record<string, string> = Object.create(null);
          const names = new Map<string, PolicyName>();
          texts.forEach((text: string, k: number) => {
            const a = annotations[k];
            const id = idOf(a);
            const usable = id.trim() !== '' && counts.get(id) === 1 && !/^policy\d+$/.test(id) && id !== '__proto__';
            const key = usable ? id : positional[k];
            const reason = a && typeof a.reason === 'string' && a.reason.trim() !== '' ? oneLine(a.reason) : undefined;
            keyed[key] = text;
            names.set(key, { id: key, ...(reason ? { reason } : {}), order: Number(positional[k].slice('policy'.length)) });
          });
          // Every rule must reach the engine under its own key. If any did not,
          // evaluate the text whole rather than risk a forbid going missing.
          if (Object.keys(keyed).length === texts.length && names.size === texts.length) {
            prepared = { staticPolicies: { ...keyed }, names };
          }
        }
      }
    }
  } catch {
    prepared = { staticPolicies: source, names: new Map() };
  }
  if (preparedPolicies.size >= PREPARED_CACHE_LIMIT) {
    const oldest = preparedPolicies.keys().next().value;
    if (oldest !== undefined) preparedPolicies.delete(oldest);
  }
  preparedPolicies.set(source, prepared);
  return prepared;
}

/** The rules a decision names, in source order, each with its @reason when it has one. */
function namedPolicies(ids: unknown, prepared: PreparedPolicies): Array<{ id: string; reason?: string }> {
  const list = Array.isArray(ids) ? ids.filter((id): id is string => typeof id === 'string') : [];
  return list
    .map((id) => prepared.names.get(id) ?? { id, order: Number.MAX_SAFE_INTEGER })
    .sort((a, b) => a.order - b.order || (a.id < b.id ? -1 : a.id > b.id ? 1 : 0))
    .map(({ id, reason }) => (reason ? { id, reason } : { id }));
}

/**
 * The deny reason: the forbid rules that matched, by @id and @reason
 * (`cedar_deny: starter.read-secret-file: Reads a credential file ...`), or
 * `cedar_deny: no permit matched (default deny)` when no rule permitted the call.
 */
function denyReason(deniedBy: Array<{ id: string; reason?: string }>): string {
  if (deniedBy.length === 0) return 'cedar_deny: no permit matched (default deny)';
  return `cedar_deny: ${deniedBy.map((p) => (p.reason ? `${p.id}: ${p.reason}` : p.id)).join('; ')}`;
}

// ============================================================
// Evaluation
// ============================================================

export interface CedarEvalOptions {
  /**
   * Default true (0.7.0+). When true, ANY evaluation error, engine
   * unavailability, malformed result, or per-policy error DENIES. When false
   * (explicit observe/shadow use only), those paths ALLOW but are flagged
   * would_deny:true in the decision metadata so the failure is never silent.
   */
  failClosed?: boolean;
}

/**
 * Map an evaluation error or uncertainty to a decision. FAIL-CLOSED (deny) by
 * default; allow only when failClosed is explicitly false, and flag it loudly.
 * This single chokepoint is why protect-mcp cannot silently permit on an error.
 */
function onEvalError(reason: string, failClosed: boolean, extra?: Record<string, unknown>): ExternalDecision {
  return {
    allowed: !failClosed,
    reason: failClosed ? reason : `${reason} (observe mode; would DENY under enforcement)`,
    metadata: { error: true, fail_closed: failClosed, would_deny: true, ...(extra || {}) },
  };
}

/**
 * Evaluate a Cedar policy set against a tool call.
 *
 * FAIL-CLOSED by default (0.7.0+): if Cedar is unavailable, the engine API is
 * unsupported, evaluation throws, the result is malformed, or ANY policy errored
 * during evaluation (which Cedar otherwise silently discards, leaving a residual
 * permit standing), this returns DENY. The allow-on-error behavior is reachable
 * only by explicitly passing { failClosed: false }, and even then it is flagged.
 */
export async function evaluateCedar(
  policySet: CedarPolicySet,
  req: CedarEvalRequest,
  schema?: CedarSchema,
  options?: CedarEvalOptions,
): Promise<ExternalDecision> {
  const failClosed = options?.failClosed ?? true;
  const available = await ensureCedarWasm();

  if (!available) {
    return onEvalError(`cedar_wasm_not_available: ${cedarWasmLoadError || 'unknown load failure'}`, failClosed, { fallback: true });
  }

  try {
    const agentId = req.agentId || req.tier;

    // Build the authorization request context
    const context: Record<string, unknown> = {
      tier: req.tier,
      ...(req.context || {}),
    };

    // If tool input is provided and we have a schema, include it in context
    // for typed attribute access in Cedar policies
    if (req.toolInput && Object.keys(req.toolInput).length > 0) {
      context.input = req.toolInput;
    }

    const authRequest = {
      principal: { type: 'Agent', id: agentId },
      action: { type: 'Action', id: req.actionModel === 'tool' ? req.tool : 'MCP::Tool::call' },
      resource: { type: 'Tool', id: req.tool },
      // Only values Cedar can hold: a fraction, a null or an escape key in the
      // input no longer makes the engine refuse the whole call (see cedarSafeValue).
      context: cedarSafeContext(context),
    };

    const entities = buildEntities(req);

    // Resolve schema: use provided schema JSON, or null for unvalidated evaluation
    const cedarSchema = schema?.schemaJson ?? null;

    // Cedar WASM isAuthorized() call
    // The WASM module exports different APIs depending on version.
    // We support both the newer `isAuthorized` and older `checkAuthorization`.
    let result: any;
    let prepared: PreparedPolicies = { staticPolicies: policySet.source, names: new Map() };

    if (typeof cedarWasm.isAuthorized === 'function') {
      prepared = preparePolicies(cedarWasm, policySet.source);
      result = cedarWasm.isAuthorized({
        policies: { staticPolicies: prepared.staticPolicies },
        entities,
        principal: authRequest.principal,
        action: authRequest.action,
        resource: authRequest.resource,
        context: authRequest.context,
        schema: cedarSchema,
      });
    } else if (typeof cedarWasm.checkAuthorization === 'function') {
      result = cedarWasm.checkAuthorization(
        policySet.source,
        JSON.stringify(entities),
        JSON.stringify(authRequest),
      );
    } else {
      // Fallback: try the default export
      const cedarEngine = cedarWasm.default || cedarWasm;
      if (typeof cedarEngine.isAuthorized === 'function') {
        prepared = preparePolicies(cedarEngine, policySet.source);
        result = cedarEngine.isAuthorized({
          policies: { staticPolicies: prepared.staticPolicies },
          entities,
          principal: authRequest.principal,
          action: authRequest.action,
          resource: authRequest.resource,
          context: authRequest.context,
          schema: cedarSchema,
        });
      } else {
        return onEvalError('cedar_wasm_api_unsupported', failClosed, { exports: Object.keys(cedarWasm) });
      }
    }

    // Parse and HARDEN the decision. A permit that survives only because a
    // forbid rule errored (Cedar silently discards an erroring policy) is
    // unsound, so any per-policy error is treated as an evaluation error and
    // denied under fail-closed. This is the runtime catch for the 0.6.x
    // in-on-String advisory: even a bad policy cannot silently permit-all.
    const parsed = parseWasmResult(result);
    const policyErrors = extractPolicyErrors(result);

    if (parsed.kind === 'error') {
      return onEvalError(`cedar_unparseable_result: ${parsed.diagnostics}`, failClosed);
    }
    if (policyErrors.length > 0) {
      return onEvalError(
        `cedar_policy_errored: ${policyErrors.length} policy error(s); decision is unsound`,
        failClosed,
        { policy_errors: policyErrors.slice(0, 5), policy_digest: policySet.digest },
      );
    }

    // Name the rules that decided: a deny says which forbid matched, by its
    // @id, with its @reason, so the agent learns why and the receipt says so.
    if (parsed.kind === 'allow') {
      return {
        allowed: true,
        reason: undefined,
        metadata: {
          policy_digest: policySet.digest,
          ...(parsed.matchedPolicies ? { matched_policies: namedPolicies(parsed.matchedPolicies, prepared).map((p) => p.id) } : {}),
        },
      };
    }
    if (!parsed.matchedPolicies && parsed.diagnostics === undefined) {
      // A legacy engine answer with no diagnostics: nothing to name.
      return { allowed: false, reason: 'cedar_deny', metadata: { policy_digest: policySet.digest } };
    }
    const deniedBy = namedPolicies(parsed.matchedPolicies, prepared);
    return {
      allowed: false,
      reason: denyReason(deniedBy),
      metadata: {
        policy_digest: policySet.digest,
        matched_policies: deniedBy.map((p) => p.id),
        denied_by: deniedBy,
        default_deny: deniedBy.length === 0,
      },
    };
  } catch (err) {
    return onEvalError(`cedar_eval_error: ${err instanceof Error ? err.message : 'unknown'}`, failClosed);
  }
}

type ParsedDecision =
  | { kind: 'allow'; matchedPolicies?: string[] }
  | { kind: 'deny'; diagnostics?: string; matchedPolicies?: string[] }
  | { kind: 'error'; diagnostics: string };

/**
 * Parse the WASM evaluation result. A result we cannot interpret is an ERROR,
 * never an allow, so the caller fails closed. (Pre-0.7.0 this returned allow for
 * null/unknown, which is exactly how a malformed engine response opened the gate.)
 */
function parseWasmResult(result: any): ParsedDecision {
  if (!result) return { kind: 'error', diagnostics: 'null result from Cedar WASM' };

  // Cedar WASM 4.x AuthorizationAnswer:
  //   { type: "failure", errors: [...] }  -> request/policy errors, cannot decide
  //   { type: "success", response: { decision: "allow"|"deny", diagnostics } }
  if (result.type === 'failure') {
    return { kind: 'error', diagnostics: `cedar failure: ${JSON.stringify(result.errors ?? [])}` };
  }
  if (result.type === 'success' && result.response) {
    const dec = result.response.decision;
    const reasons = result.response.diagnostics?.reason;
    if (dec === 'allow' || dec === 'Allow') return { kind: 'allow', matchedPolicies: reasons };
    if (dec === 'deny' || dec === 'Deny') {
      return { kind: 'deny', diagnostics: result.response.diagnostics ? JSON.stringify(result.response.diagnostics) : undefined, matchedPolicies: reasons };
    }
  }

  // Tolerated legacy shapes (older engines / direct decision field)
  if (result.type === 'allow' || result.decision === 'Allow') return { kind: 'allow' };
  if (result.type === 'deny' || result.decision === 'Deny') return { kind: 'deny' };
  if (typeof result === 'boolean') return result ? { kind: 'allow' } : { kind: 'deny' };

  return { kind: 'error', diagnostics: `unknown result format: ${JSON.stringify(result)}` };
}

/**
 * Extract per-policy evaluation errors from a Cedar WASM response across the
 * shapes different engine versions use. A non-empty list means at least one
 * policy was discarded due to an error, so any surviving permit is unsound.
 */
function extractPolicyErrors(result: any): string[] {
  if (!result || typeof result !== 'object') return [];
  // Cedar 4.x surfaces errors at the top level on a "failure" answer, and inside
  // response.diagnostics.errors when a policy errored but a decision still formed.
  const raw =
    result.errors ??
    result.response?.diagnostics?.errors ??
    result.diagnostics?.errors ??
    [];
  if (!Array.isArray(raw)) return [];
  return raw
    .map((e: any) => (typeof e === 'string' ? e : e?.message ?? e?.error ?? JSON.stringify(e)))
    .filter(Boolean);
}

/**
 * Validate that Cedar WASM is available.
 * Useful for CLI startup diagnostics.
 */
export async function isCedarAvailable(): Promise<boolean> {
  return ensureCedarWasm();
}

/**
 * Check that a policy text parses, before a command writes it. `checked` is
 * false when the engine is not installed here, so the caller can say the text
 * went unchecked rather than claim it parses.
 */
export async function checkCedarPolicyText(source: string): Promise<{ checked: boolean; ok: boolean; error?: string }> {
  if (!(await ensureCedarWasm())) return { checked: false, ok: true };
  const engine = typeof cedarWasm.checkParsePolicySet === 'function' ? cedarWasm : cedarWasm.default;
  if (!engine || typeof engine.checkParsePolicySet !== 'function') return { checked: false, ok: true };
  try {
    const answer = engine.checkParsePolicySet({ staticPolicies: source });
    if (answer?.type === 'success') return { checked: true, ok: true };
    const first = Array.isArray(answer?.errors) ? answer.errors[0] : undefined;
    return { checked: true, ok: false, error: oneLine(String(first?.message ?? JSON.stringify(answer))) };
  } catch (err) {
    return { checked: true, ok: false, error: err instanceof Error ? oneLine(err.message) : 'unknown parse error' };
  }
}

// ============================================================
// Proof-of-restraint self-test (the gate proves itself)
// ============================================================

/** Build a CedarPolicySet from inline source (for the self-test). */
export function policySetFromSource(source: string, name = 'inline'): CedarPolicySet {
  const digest = digestCedarSource(source).policy_digest;
  return { source, digest, fileCount: 1, files: [name] };
}

export interface SelfTestCase {
  name: string;
  expected: 'ALLOW' | 'DENY';
  actual: 'ALLOW' | 'DENY';
  pass: boolean;
  reason?: string;
}
export interface SelfTestReport {
  wasmAvailable: boolean;
  passed: boolean;
  cases: SelfTestCase[];
}

/**
 * Run known deny/allow vectors through the LIVE evaluator before the gate is
 * trusted. Always proves the fail-closed invariant (the engine being unable to
 * decide must DENY). When Cedar WASM is present it also proves a real forbid
 * denies, a permit allows, and a policy using the silently-discarded
 * `in`-on-String pattern DENIES rather than permit-all (the 0.6.x regression).
 */
export async function runEvaluatorSelfTest(): Promise<SelfTestReport> {
  const wasmAvailable = await isCedarAvailable();
  const cases: SelfTestCase[] = [];

  const run = async (name: string, expected: 'ALLOW' | 'DENY', policy: CedarPolicySet, context: Record<string, unknown>) => {
    const d = await evaluateCedar(policy, { tool: 'Bash', tier: 'unknown', context }, undefined, { failClosed: true });
    const actual: 'ALLOW' | 'DENY' = d.allowed ? 'ALLOW' : 'DENY';
    cases.push({ name, expected, actual, pass: actual === expected, reason: d.reason });
  };

  if (!wasmAvailable) {
    // The one universally-provable invariant: no engine means DENY, not allow.
    await run('engine unavailable denies', 'DENY', policySetFromSource('permit(principal, action, resource);'), {});
    return { wasmAvailable, passed: cases.every((c) => c.pass), cases };
  }

  const correct = policySetFromSource(
    'forbid(principal, action, resource) when { ["rm", "dd", "mkfs"].contains(context.command) };\npermit(principal, action, resource);',
  );
  await run('forbid denies rm', 'DENY', correct, { command: 'rm' });
  await run('permit allows ls', 'ALLOW', correct, { command: 'ls' });

  // The advisory regression: an in-on-String forbid that Cedar silently discards
  // must NOT leave a residual permit-all standing under fail-closed evaluation.
  const broken = policySetFromSource(
    'forbid(principal, action, resource) when { context.command in ["rm", "dd"] };\npermit(principal, action, resource);',
  );
  await run('in-on-String forbid does not permit-all', 'DENY', broken, { command: 'rm' });

  return { wasmAvailable, passed: cases.every((c) => c.pass), cases };
}
