/**
 * @scopeblind/protect-mcp — Cedar Policy Evaluator (Local WASM)
 *
 * Evaluates Cedar policies locally using @cedar-policy/cedar-wasm.
 * No external server required. Same deterministic evaluation as
 * AWS Verified Permissions / AgentCore Policy.
 *
 * Cedar is loaded as an optional dependency — if the WASM module
 * isn't installed, this module exports stubs that return fallback decisions.
 */

import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join, extname } from 'node:path';
import type { ExternalDecision, TrustTier } from './types.js';
import { digestPolicyFiles, digestCedarSource } from './policy-digest.js';

// ============================================================
// Types
// ============================================================

export interface CedarPolicySet {
  /** Raw concatenated Cedar source */
  source: string;
  /** "sha256:<64 hex>" under acta-policy-digest-v1 (see policy-digest.ts) */
  digest: string;
  /** Number of individual .cedar files loaded */
  fileCount: number;
  /** Filenames loaded */
  files: string[];
}

export interface CedarEvalRequest {
  /** Tool name being called */
  tool: string;
  /** Trust tier of the agent */
  tier: TrustTier;
  /** Agent ID (optional) */
  agentId?: string;
  /** Additional context fields */
  context?: Record<string, unknown>;
  /** Tool input (for schema-validated evaluation) */
  toolInput?: Record<string, unknown>;
}

/** Cedar schema for typed policy evaluation (generated by cedar-schema.ts) */
export interface CedarSchema {
  /** The schema as a JSON object for Cedar WASM */
  schemaJson: Record<string, unknown> | null;
  /** Namespace used in the schema */
  namespace?: string;
}

// ============================================================
// WASM module (lazily loaded)
// ============================================================

let cedarWasm: any | null = null;
let loadAttempted = false;

/**
 * Attempt to load the Cedar WASM module.
 * Returns true if successful, false if not installed.
 */
async function ensureCedarWasm(): Promise<boolean> {
  if (cedarWasm) return true;
  if (loadAttempted) return false;
  loadAttempted = true;

  try {
    const moduleName = '@cedar-policy/cedar-wasm';
    cedarWasm = await import(/* @vite-ignore */ moduleName);
    return true;
  } catch {
    return false;
  }
}

// ============================================================
// Policy loading
// ============================================================

/**
 * Load all .cedar files from a directory and return a compiled policy set.
 *
 * Files are sorted alphabetically for deterministic digest computation.
 * Throws if the directory doesn't exist or contains no .cedar files.
 */
export function loadCedarPolicies(dirPath: string): CedarPolicySet {
  if (!existsSync(dirPath)) {
    throw new Error(`Cedar policy directory not found: ${dirPath}`);
  }

  const entries = readdirSync(dirPath)
    .filter((f) => extname(f) === '.cedar')
    .sort();

  if (entries.length === 0) {
    throw new Error(`No .cedar files found in: ${dirPath}`);
  }

  const files: Array<{ name: string; content: string }> = [];
  for (const file of entries) {
    files.push({ name: file, content: readFileSync(join(dirPath, file), 'utf-8') });
  }

  // Concatenation is for EVALUATION only. The digest is the normative
  // acta-policy-digest-v1 construction (per-file hashes, no concatenation),
  // so the commitment a receipt carries is recomputable from published bytes.
  const concatenated = files.map((f) => f.content).join('\n\n');
  const digest = digestPolicyFiles('cedar', files).policy_digest;

  return {
    source: concatenated,
    digest,
    fileCount: entries.length,
    files: entries,
  };
}

// ============================================================
// Entity construction helpers
// ============================================================

/**
 * Build the Cedar entities array for a tool call evaluation.
 *
 * Entity model:
 *   Principal: Agent::"<tier>" (or Agent::"<agentId>" if known)
 *   Action:    Action::"MCP::Tool::call"
 *   Resource:  Tool::"<toolName>"
 */
function buildEntities(req: CedarEvalRequest): Array<Record<string, unknown>> {
  const agentId = req.agentId || req.tier;
  return [
    {
      uid: { type: 'Agent', id: agentId },
      attrs: {
        tier: req.tier,
        ...(req.agentId ? { agent_id: req.agentId } : {}),
      },
      parents: [],
    },
    {
      uid: { type: 'Tool', id: req.tool },
      attrs: {},
      parents: [],
    },
  ];
}

// ============================================================
// Evaluation
// ============================================================

export interface CedarEvalOptions {
  /**
   * Default true (0.7.0+). When true, ANY evaluation error, engine
   * unavailability, malformed result, or per-policy error DENIES. When false
   * (explicit observe/shadow use only), those paths ALLOW but are flagged
   * would_deny:true in the decision metadata so the failure is never silent.
   */
  failClosed?: boolean;
}

/**
 * Map an evaluation error or uncertainty to a decision. FAIL-CLOSED (deny) by
 * default; allow only when failClosed is explicitly false, and flag it loudly.
 * This single chokepoint is why protect-mcp cannot silently permit on an error.
 */
function onEvalError(reason: string, failClosed: boolean, extra?: Record<string, unknown>): ExternalDecision {
  return {
    allowed: !failClosed,
    reason: failClosed ? reason : `${reason} (observe mode; would DENY under enforcement)`,
    metadata: { error: true, fail_closed: failClosed, would_deny: true, ...(extra || {}) },
  };
}

/**
 * Evaluate a Cedar policy set against a tool call.
 *
 * FAIL-CLOSED by default (0.7.0+): if Cedar is unavailable, the engine API is
 * unsupported, evaluation throws, the result is malformed, or ANY policy errored
 * during evaluation (which Cedar otherwise silently discards, leaving a residual
 * permit standing), this returns DENY. The allow-on-error behavior is reachable
 * only by explicitly passing { failClosed: false }, and even then it is flagged.
 */
export async function evaluateCedar(
  policySet: CedarPolicySet,
  req: CedarEvalRequest,
  schema?: CedarSchema,
  options?: CedarEvalOptions,
): Promise<ExternalDecision> {
  const failClosed = options?.failClosed ?? true;
  const available = await ensureCedarWasm();

  if (!available) {
    return onEvalError('cedar_wasm_not_available', failClosed, { fallback: true });
  }

  try {
    const agentId = req.agentId || req.tier;

    // Build the authorization request context
    const context: Record<string, unknown> = {
      tier: req.tier,
      ...(req.context || {}),
    };

    // If tool input is provided and we have a schema, include it in context
    // for typed attribute access in Cedar policies
    if (req.toolInput && Object.keys(req.toolInput).length > 0) {
      context.input = req.toolInput;
    }

    const authRequest = {
      principal: { type: 'Agent', id: agentId },
      action: { type: 'Action', id: 'MCP::Tool::call' },
      resource: { type: 'Tool', id: req.tool },
      context,
    };

    const entities = buildEntities(req);

    // Resolve schema: use provided schema JSON, or null for unvalidated evaluation
    const cedarSchema = schema?.schemaJson ?? null;

    // Cedar WASM isAuthorized() call
    // The WASM module exports different APIs depending on version.
    // We support both the newer `isAuthorized` and older `checkAuthorization`.
    let result: any;

    if (typeof cedarWasm.isAuthorized === 'function') {
      result = cedarWasm.isAuthorized({
        policies: { staticPolicies: policySet.source },
        entities,
        principal: authRequest.principal,
        action: authRequest.action,
        resource: authRequest.resource,
        context: authRequest.context,
        schema: cedarSchema,
      });
    } else if (typeof cedarWasm.checkAuthorization === 'function') {
      result = cedarWasm.checkAuthorization(
        policySet.source,
        JSON.stringify(entities),
        JSON.stringify(authRequest),
      );
    } else {
      // Fallback: try the default export
      const cedarEngine = cedarWasm.default || cedarWasm;
      if (typeof cedarEngine.isAuthorized === 'function') {
        result = cedarEngine.isAuthorized({
          policies: { staticPolicies: policySet.source },
          entities,
          principal: authRequest.principal,
          action: authRequest.action,
          resource: authRequest.resource,
          context: authRequest.context,
          schema: cedarSchema,
        });
      } else {
        return onEvalError('cedar_wasm_api_unsupported', failClosed, { exports: Object.keys(cedarWasm) });
      }
    }

    // Parse and HARDEN the decision. A permit that survives only because a
    // forbid rule errored (Cedar silently discards an erroring policy) is
    // unsound, so any per-policy error is treated as an evaluation error and
    // denied under fail-closed. This is the runtime catch for the 0.6.x
    // in-on-String advisory: even a bad policy cannot silently permit-all.
    const parsed = parseWasmResult(result);
    const policyErrors = extractPolicyErrors(result);

    if (parsed.kind === 'error') {
      return onEvalError(`cedar_unparseable_result: ${parsed.diagnostics}`, failClosed);
    }
    if (policyErrors.length > 0) {
      return onEvalError(
        `cedar_policy_errored: ${policyErrors.length} policy error(s); decision is unsound`,
        failClosed,
        { policy_errors: policyErrors.slice(0, 5), policy_digest: policySet.digest },
      );
    }

    return {
      allowed: parsed.kind === 'allow',
      reason: parsed.kind === 'allow' ? undefined : `cedar_deny${parsed.diagnostics ? ': ' + parsed.diagnostics : ''}`,
      metadata: {
        policy_digest: policySet.digest,
        ...(parsed.matchedPolicies ? { matched_policies: parsed.matchedPolicies } : {}),
      },
    };
  } catch (err) {
    return onEvalError(`cedar_eval_error: ${err instanceof Error ? err.message : 'unknown'}`, failClosed);
  }
}

type ParsedDecision =
  | { kind: 'allow'; matchedPolicies?: string[] }
  | { kind: 'deny'; diagnostics?: string; matchedPolicies?: string[] }
  | { kind: 'error'; diagnostics: string };

/**
 * Parse the WASM evaluation result. A result we cannot interpret is an ERROR,
 * never an allow, so the caller fails closed. (Pre-0.7.0 this returned allow for
 * null/unknown, which is exactly how a malformed engine response opened the gate.)
 */
function parseWasmResult(result: any): ParsedDecision {
  if (!result) return { kind: 'error', diagnostics: 'null result from Cedar WASM' };

  // Cedar WASM 4.x AuthorizationAnswer:
  //   { type: "failure", errors: [...] }  -> request/policy errors, cannot decide
  //   { type: "success", response: { decision: "allow"|"deny", diagnostics } }
  if (result.type === 'failure') {
    return { kind: 'error', diagnostics: `cedar failure: ${JSON.stringify(result.errors ?? [])}` };
  }
  if (result.type === 'success' && result.response) {
    const dec = result.response.decision;
    const reasons = result.response.diagnostics?.reason;
    if (dec === 'allow' || dec === 'Allow') return { kind: 'allow', matchedPolicies: reasons };
    if (dec === 'deny' || dec === 'Deny') {
      return { kind: 'deny', diagnostics: result.response.diagnostics ? JSON.stringify(result.response.diagnostics) : undefined, matchedPolicies: reasons };
    }
  }

  // Tolerated legacy shapes (older engines / direct decision field)
  if (result.type === 'allow' || result.decision === 'Allow') return { kind: 'allow' };
  if (result.type === 'deny' || result.decision === 'Deny') return { kind: 'deny' };
  if (typeof result === 'boolean') return result ? { kind: 'allow' } : { kind: 'deny' };

  return { kind: 'error', diagnostics: `unknown result format: ${JSON.stringify(result)}` };
}

/**
 * Extract per-policy evaluation errors from a Cedar WASM response across the
 * shapes different engine versions use. A non-empty list means at least one
 * policy was discarded due to an error, so any surviving permit is unsound.
 */
function extractPolicyErrors(result: any): string[] {
  if (!result || typeof result !== 'object') return [];
  // Cedar 4.x surfaces errors at the top level on a "failure" answer, and inside
  // response.diagnostics.errors when a policy errored but a decision still formed.
  const raw =
    result.errors ??
    result.response?.diagnostics?.errors ??
    result.diagnostics?.errors ??
    [];
  if (!Array.isArray(raw)) return [];
  return raw
    .map((e: any) => (typeof e === 'string' ? e : e?.message ?? e?.error ?? JSON.stringify(e)))
    .filter(Boolean);
}

/**
 * Validate that Cedar WASM is available.
 * Useful for CLI startup diagnostics.
 */
export async function isCedarAvailable(): Promise<boolean> {
  return ensureCedarWasm();
}

// ============================================================
// Proof-of-restraint self-test (the gate proves itself)
// ============================================================

/** Build a CedarPolicySet from inline source (for the self-test). */
export function policySetFromSource(source: string, name = 'inline'): CedarPolicySet {
  const digest = digestCedarSource(source).policy_digest;
  return { source, digest, fileCount: 1, files: [name] };
}

export interface SelfTestCase {
  name: string;
  expected: 'ALLOW' | 'DENY';
  actual: 'ALLOW' | 'DENY';
  pass: boolean;
  reason?: string;
}
export interface SelfTestReport {
  wasmAvailable: boolean;
  passed: boolean;
  cases: SelfTestCase[];
}

/**
 * Run known deny/allow vectors through the LIVE evaluator before the gate is
 * trusted. Always proves the fail-closed invariant (the engine being unable to
 * decide must DENY). When Cedar WASM is present it also proves a real forbid
 * denies, a permit allows, and a policy using the silently-discarded
 * `in`-on-String pattern DENIES rather than permit-all (the 0.6.x regression).
 */
export async function runEvaluatorSelfTest(): Promise<SelfTestReport> {
  const wasmAvailable = await isCedarAvailable();
  const cases: SelfTestCase[] = [];

  const run = async (name: string, expected: 'ALLOW' | 'DENY', policy: CedarPolicySet, context: Record<string, unknown>) => {
    const d = await evaluateCedar(policy, { tool: 'Bash', tier: 'unknown', context }, undefined, { failClosed: true });
    const actual: 'ALLOW' | 'DENY' = d.allowed ? 'ALLOW' : 'DENY';
    cases.push({ name, expected, actual, pass: actual === expected, reason: d.reason });
  };

  if (!wasmAvailable) {
    // The one universally-provable invariant: no engine means DENY, not allow.
    await run('engine unavailable denies', 'DENY', policySetFromSource('permit(principal, action, resource);'), {});
    return { wasmAvailable, passed: cases.every((c) => c.pass), cases };
  }

  const correct = policySetFromSource(
    'forbid(principal, action, resource) when { ["rm", "dd", "mkfs"].contains(context.command) };\npermit(principal, action, resource);',
  );
  await run('forbid denies rm', 'DENY', correct, { command: 'rm' });
  await run('permit allows ls', 'ALLOW', correct, { command: 'ls' });

  // The advisory regression: an in-on-String forbid that Cedar silently discards
  // must NOT leave a residual permit-all standing under fail-closed evaluation.
  const broken = policySetFromSource(
    'forbid(principal, action, resource) when { context.command in ["rm", "dd"] };\npermit(principal, action, resource);',
  );
  await run('in-on-String forbid does not permit-all', 'DENY', broken, { command: 'rm' });

  return { wasmAvailable, passed: cases.every((c) => c.pass), cases };
}
