/** Managed, disposable repository transport. Human and coding authority remains in the existing protocols. */
import {canonical,sha256,verify,type Signed} from './coordination-protocol.js';
import {REPOSITORY_HEX,REPOSITORY_ID,REPOSITORY_SHA,validRepositoryEnvelope,type RepositoryState} from './coordination-repository.js';
import {validRepositoryWorkspace,validWorkspaceInvitation,type RepositoryWorkspace,type WorkspaceInvitation,type WorkspaceTaskAssignment,type RepositoryWorkspaceState} from './coordination-repository-workspace.js';
import type {RepositoryCodingConnectionConfig,RepositorySetupChallenge,RepositorySetupWorkflowProof} from './coordination-repository-connection.js';
import type {RepositoryCodingJob} from './coordination-repository-coding.js';
import {TRIAL_BEFORE_HTML,TRIAL_SOURCE_HTML} from './repository-trial-template.js';

export const REPOSITORY_TRIAL_ACTIONS=['repository_trial_info','repository_trial_create','repository_trial_get','repository_trial_bind','repository_trial_dispatch','repository_trial_poll','repository_trial_complete'] as const;
export type RepositoryTrialAction=typeof REPOSITORY_TRIAL_ACTIONS[number];
export const TRIAL_REPOSITORY='ScopeBlind/scopeblind-repository-demo';
export const TRIAL_WORKFLOW='.github/workflows/scopeblind-trial.yml';
export const TRIAL_TEMPLATE='styled-contact-v1';
export const TRIAL_SOURCE_CHECK={name:'ScopeBlind trial source safety',app_id:15368};
export const TRIAL_CODING_CHECK={name:'ScopeBlind isolated coding checks',app_id:15368};
export const TRIAL_LIMITS={max_jobs:1,max_attempts:2,max_model_calls:8,max_tokens:98304,max_seconds:600,max_changed_files:2,max_changed_bytes:32768} as const;
export const TRIAL_DOCKER_IMAGE='node@sha256:e21fc383b50d5347dc7a9f1cae45b8f4e2f0d39f7ade28e4eef7d2934522b752';
export const trialBase=(id:string)=>`scopeblind/trial/${id}/base`;
export const trialSource=(id:string)=>`scopeblind/trial/${id}/source`;
export interface RepositoryTrialRequest {type:'scopeblind.repository.trial-request.v1';id:string;owner_key:string;authority_key:string;title:string;template:typeof TRIAL_TEMPLATE;reviewer_secret_hash:string;issued_at:string;expires_at:string}
export interface RepositoryTrialHtml {html:string;sha256:string;blob_sha:string}
export interface RepositoryTrialProvision {type:'scopeblind.repository.trial-provision.v1';trial_id:string;request_digest:string;receiver_key:string;repository:typeof TRIAL_REPOSITORY;template_sha:string;base_branch:string;source_branch:string;base_sha:string;source_sha:string;pull_number:number;before:RepositoryTrialHtml;source:RepositoryTrialHtml;source_check:{id:number;name:string;app_id:number;head_sha:string;conclusion:'success'};observed_at:string}
export interface RepositoryTrialReadiness {type:'scopeblind.repository.trial-readiness.v1';receiver_key:string;worker_key:string;repository:typeof TRIAL_REPOSITORY;proof:RepositorySetupWorkflowProof;observed_at:string;expires_at:string}
export interface RepositoryTrialInfo {type:'scopeblind.repository.trial-info.v1';repository:typeof TRIAL_REPOSITORY;template:typeof TRIAL_TEMPLATE;receiver_key:string|null;worker_key:string|null;template_sha:string|null;availability:'ready'|'starting'|'setup_required'|'at_capacity';dispatch_available:boolean;readiness:Signed<RepositoryTrialReadiness>|null;limits:typeof TRIAL_LIMITS;source_checks:Array<typeof TRIAL_SOURCE_CHECK>;required_checks:Array<typeof TRIAL_CODING_CHECK>;allowed_paths:['site/**'];docker_image:string;test_command:['node','--test','tests/contact.test.cjs'];build_command:['node','tools/build.cjs'];preview_directory:'dist';observed_at:string}
export type RepositoryTrialJobKind='provision'|'inspect'|'execute'|'reconcile'|'coding'|'coding_reconcile'|'coding_ready';
export interface RepositoryTrialJobView {id:string;kind:RepositoryTrialJobKind;target_id:string|null;status:'queued'|'leased'|'complete'|'failed'|'unknown';attempts:number;error:string|null;updated_at:string}
export interface RepositoryTrialState {type:'scopeblind.repository.trial-state.v1';request:Signed<RepositoryTrialRequest>;provision:Signed<RepositoryTrialProvision>|null;workspace:Signed<RepositoryWorkspace>|null;invitation:Signed<WorkspaceInvitation>|null;config:RepositoryCodingConnectionConfig;receiver_key:string;readiness:Signed<RepositoryTrialReadiness>|null;status:'queued'|'provisioning'|'ready'|'active'|'expired'|'failed'|'unknown';dispatch_status:'requested'|'unconfigured'|'unavailable';jobs:RepositoryTrialJobView[];observed_at:string}
export interface RepositoryTrialJob {type:'scopeblind.repository.trial-job.v1';id:string;kind:RepositoryTrialJobKind;target_id:string|null;request:Signed<RepositoryTrialRequest>;provision:Signed<RepositoryTrialProvision>|null;workspace:Signed<RepositoryWorkspaceState>|null;assignment:Signed<WorkspaceTaskAssignment>|null;task:Signed<RepositoryState>|null;coding:Signed<RepositoryCodingJob>|null;config:RepositoryCodingConnectionConfig;receiver_key:string;template_sha:string;lease_id:string;lease_expires_at:string;proof:RepositorySetupWorkflowProof;observed_at:string}
export interface RepositoryTrialCompletion {type:'scopeblind.repository.trial-completion.v1';job_id:string;trial_id:string;request_digest:string;lease_id:string;receiver_key:string;kind:RepositoryTrialJobKind;provision:Signed<RepositoryTrialProvision>|null;error:string|null;observed_at:string}
export interface RepositoryTrialPoll {type:'scopeblind.repository.trial-poll.v1';lease_id:string;challenge:RepositorySetupChallenge;job:Signed<RepositoryTrialJob>|null;observed_at:string}
const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const exact=(v:Record<string,unknown>,keys:string[])=>Object.keys(v).length===keys.length&&keys.every(k=>Object.hasOwn(v,k));
const key=(v:unknown)=>typeof v==='string'&&REPOSITORY_HEX.test(v),id=(v:unknown)=>typeof v==='string'&&REPOSITORY_ID.test(v),sha=(v:unknown)=>typeof v==='string'&&REPOSITORY_SHA.test(v);
const at=(v:unknown)=>typeof v==='string'&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString()===v;
export function validRepositoryTrialRequest(v:unknown):v is RepositoryTrialRequest{return object(v)&&exact(v,['type','id','owner_key','authority_key','title','template','reviewer_secret_hash','issued_at','expires_at'])&&v.type==='scopeblind.repository.trial-request.v1'&&id(v.id)&&key(v.owner_key)&&key(v.authority_key)&&v.owner_key!==v.authority_key&&key(v.reviewer_secret_hash)&&v.template===TRIAL_TEMPLATE&&typeof v.title==='string'&&v.title.trim().length>0&&v.title.length<=100&&!/[\u0000-\u001f\u007f]/.test(v.title)&&at(v.issued_at)&&at(v.expires_at)&&Date.parse(String(v.expires_at))>Date.parse(String(v.issued_at))&&Date.parse(String(v.expires_at))-Date.parse(String(v.issued_at))<=86400000;}
export function validRepositoryTrialProvision(v:unknown):v is RepositoryTrialProvision{return object(v)&&exact(v,['type','trial_id','request_digest','receiver_key','repository','template_sha','base_branch','source_branch','base_sha','source_sha','pull_number','before','source','source_check','observed_at'])&&v.type==='scopeblind.repository.trial-provision.v1'&&id(v.trial_id)&&[v.request_digest,v.receiver_key].every(key)&&v.repository===TRIAL_REPOSITORY&&[v.template_sha,v.base_sha,v.source_sha].every(sha)&&v.base_branch===trialBase(String(v.trial_id))&&v.source_branch===trialSource(String(v.trial_id))&&Number.isSafeInteger(v.pull_number)&&Number(v.pull_number)>0&&[v.before,v.source].every(h=>object(h)&&exact(h,['html','sha256','blob_sha'])&&typeof h.html==='string'&&new TextEncoder().encode(h.html).length<=32768&&key(h.sha256)&&sha(h.blob_sha))&&object(v.source_check)&&exact(v.source_check,['id','name','app_id','head_sha','conclusion'])&&Number.isSafeInteger(v.source_check.id)&&Number(v.source_check.id)>0&&v.source_check.name===TRIAL_SOURCE_CHECK.name&&v.source_check.app_id===15368&&v.source_check.head_sha===v.source_sha&&v.source_check.conclusion==='success'&&at(v.observed_at);}
export async function verifyRepositoryTrialState(value:unknown,authority:string):Promise<boolean>{
 try{if(!validRepositoryEnvelope(value))return false;const signed=value as Signed<RepositoryTrialState>,s=signed.payload,r=s?.request;
 if(!object(s)||!exact(s,['type','request','provision','workspace','invitation','config','receiver_key','readiness','status','dispatch_status','jobs','observed_at'])||s.type!=='scopeblind.repository.trial-state.v1'||!validRepositoryTrialRequest(r?.payload)||r.payload.authority_key!==authority||!await verify(r,r.payload.owner_key)||!await verify(signed,authority)||!at(s.observed_at)||!key(s.config.worker_key)||!key(s.receiver_key)||new Set([authority,r.payload.owner_key,s.receiver_key,s.config.worker_key]).size!==4||canonical(s.config)!==canonical(trialCodingConfig(r.payload.id,s.config.endpoint,authority,s.config.worker_key)))return false;
 const endpoint=new URL(s.config.endpoint);if(endpoint.protocol!=='https:'||endpoint.pathname!=='/api/coordination'||endpoint.username||endpoint.password||endpoint.hash||endpoint.search)return false;
 if(s.provision){const p=s.provision.payload;if(!validRepositoryEnvelope(s.provision)||!validRepositoryTrialProvision(p)||p.trial_id!==r.payload.id||p.request_digest!==r.digest||p.receiver_key!==s.receiver_key||p.base_sha!==p.template_sha||p.source_sha===p.base_sha||p.before.html!==TRIAL_BEFORE_HTML||p.source.html!==TRIAL_SOURCE_HTML||Date.parse(p.observed_at)>Date.parse(s.observed_at)||!await verify(s.provision,p.receiver_key))return false;for(const h of[p.before,p.source]){if(await sha256(h.html)!==h.sha256)return false;const bytes=new TextEncoder().encode(h.html),prefix=new TextEncoder().encode(`blob ${bytes.length}\0`),raw=new Uint8Array(prefix.length+bytes.length);raw.set(prefix);raw.set(bytes,prefix.length);const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-1',raw))).map(n=>n.toString(16).padStart(2,'0')).join('');if(hash!==h.blob_sha)return false;}}
 if((s.workspace===null)!==(s.invitation===null))return false;
 if(s.workspace){const w=s.workspace.payload;if(!validRepositoryEnvelope(s.workspace)||!validRepositoryWorkspace(w)||!await verify(s.workspace,r.payload.owner_key)||w.repository!==TRIAL_REPOSITORY||w.base_branch!==trialBase(r.payload.id)||w.authority_key!==authority||w.receiver_key!==s.provision?.payload.receiver_key||w.owner_key!==r.payload.owner_key||Date.parse(w.expires_at)>Date.parse(r.payload.expires_at))return false;}
 if(s.invitation){const i=s.invitation.payload;if(!s.workspace||!validWorkspaceInvitation(i)||i.workspace_id!==s.workspace.payload.id||i.workspace_digest!==s.workspace.digest||i.role!=='reviewer'||i.issuer_key!==r.payload.owner_key||i.secret_hash!==r.payload.reviewer_secret_hash||!await verify(s.invitation,r.payload.owner_key))return false;}
 if(s.readiness&&(!validRepositoryEnvelope(s.readiness)||!validTrialReadiness(s.readiness.payload)||!await verify(s.readiness,authority)||s.readiness.payload.worker_key!==s.config.worker_key||s.readiness.payload.receiver_key!==s.receiver_key||Date.parse(s.readiness.payload.observed_at)>Date.parse(s.observed_at)))return false;
 return Array.isArray(s.jobs)&&s.jobs.length<=30&&new Set(s.jobs.map(j=>j.id)).size===s.jobs.length&&s.jobs.every(j=>object(j)&&exact(j,['id','kind','target_id','status','attempts','error','updated_at'])&&id(j.id)&&['provision','inspect','execute','reconcile','coding','coding_reconcile','coding_ready'].includes(j.kind)&&(j.kind==='provision'?j.target_id===null:id(j.target_id))&&['queued','leased','complete','failed','unknown'].includes(j.status)&&Number.isInteger(j.attempts)&&j.attempts>=0&&j.attempts<=3&&(j.error===null||typeof j.error==='string'&&/^[a-z0-9_]{3,100}$/.test(j.error))&&at(j.updated_at)&&Date.parse(j.updated_at)<=Date.parse(s.observed_at))&&['queued','provisioning','ready','active','expired','failed','unknown'].includes(s.status)&&['requested','unconfigured','unavailable'].includes(s.dispatch_status);
 }catch{return false;}
}
export function trialCodingConfig(id:string,endpoint:string,authority:string,worker:string):RepositoryCodingConnectionConfig{return {type:'scopeblind.repository.coding-config.v1',endpoint,authority_key:authority,worker_key:worker,repository:TRIAL_REPOSITORY,base_branch:trialBase(id),runtime:'node22-static-v1',docker_image:TRIAL_DOCKER_IMAGE,test_command:['node','--test','tests/contact.test.cjs'],build_command:['node','tools/build.cjs'],preview_directory:'dist'};}
export function validTrialReadiness(value:unknown):value is RepositoryTrialReadiness {if(!object(value)||!exact(value,['type','receiver_key','worker_key','repository','proof','observed_at','expires_at']))return false;const r=value,p=r.proof;return r.type==='scopeblind.repository.trial-readiness.v1'&&r.repository===TRIAL_REPOSITORY&&key(r.receiver_key)&&key(r.worker_key)&&r.receiver_key!==r.worker_key&&at(r.observed_at)&&at(r.expires_at)&&Date.parse(String(r.expires_at))>Date.parse(String(r.observed_at))&&Date.parse(String(r.expires_at))-Date.parse(String(r.observed_at))<=86400000&&object(p)&&exact(p,['repository_id','run_id','run_attempt','workflow_ref','workflow_sha','token_digest','verified_at'])&&p.workflow_ref===`${TRIAL_REPOSITORY}/${TRIAL_WORKFLOW}@refs/heads/main`&&sha(p.workflow_sha)&&key(p.token_digest)&&[p.repository_id,p.run_id,p.run_attempt].every(n=>Number.isSafeInteger(n)&&Number(n)>0)&&at(p.verified_at)&&Date.parse(String(p.verified_at))<=Date.parse(String(r.observed_at));}
export async function verifyRepositoryTrialConnection(value:unknown,authority:string):Promise<boolean>{try{const c=value as {kind:string;setup_id:string;config:RepositoryCodingConnectionConfig;readiness:Signed<RepositoryTrialReadiness>},r=c?.readiness?.payload;if(!c||c.kind!=='managed_trial'||!id(c.setup_id)||!r||!validTrialReadiness(r)||r.type!=='scopeblind.repository.trial-readiness.v1'||r.repository!==TRIAL_REPOSITORY||!key(r.receiver_key)||r.worker_key!==c.config.worker_key||r.receiver_key===r.worker_key||canonical(c.config)!==canonical(trialCodingConfig(c.setup_id,c.config.endpoint,authority,r.worker_key))||!await verify(c.readiness,authority)||!at(r.observed_at)||!at(r.expires_at)||Date.parse(r.expires_at)<=Date.now()||Date.parse(r.expires_at)-Date.parse(r.observed_at)>86400000||Date.parse(r.observed_at)>Date.now()+1000)return false;const u=new URL(c.config.endpoint),p=r.proof;return u.protocol==='https:'&&u.pathname==='/api/coordination'&&!u.search&&!u.hash&&!u.username&&!u.password&&p.workflow_ref===`${TRIAL_REPOSITORY}/${TRIAL_WORKFLOW}@refs/heads/main`&&sha(p.workflow_sha)&&key(p.token_digest)&&Number.isSafeInteger(p.repository_id)&&p.repository_id>0&&Number.isSafeInteger(p.run_id)&&p.run_id>0&&Number.isSafeInteger(p.run_attempt)&&p.run_attempt>0&&at(p.verified_at);}catch{return false;}}
