/** Explicit code-edit authority. Preparation grants never authorize these operations. */
import {type Signed} from './coordination-protocol.js';
import {REPOSITORY_HEX,REPOSITORY_ID,REPOSITORY_SHA,repositoryBranch,repositoryPath,pathAllowed} from './coordination-repository.js';
import {workspacePathsWithin,type RepositoryWorkspaceState} from './coordination-repository-workspace.js';
import type {RepositoryReviewEvidence} from './coordination-repository-review-evidence.js';
export const REPOSITORY_CODING_ACTIONS=['repository_coding_info','repository_coding_mandate','repository_coding_adopt','repository_coding_revoke','repository_coding_start','repository_coding_get','repository_coding_list','repository_coding_cancel','repository_coding_reconcile','repository_coding_poll','repository_coding_heartbeat','repository_coding_model','repository_coding_publish','repository_coding_preview','repository_coding_complete'] as const;
export type RepositoryCodingAction=typeof REPOSITORY_CODING_ACTIONS[number];
export interface RepositoryCodingSource {task_id:string;task_digest:string;basis_digest:string;packet_digest:string;feedback_digest:string}
export interface RepositoryCodingMandate {
 type:'scopeblind.repository.coding-mandate.v1';id:string;workspace_id:string;workspace_digest:string;mode:'edit_code';
 owner_member_id:string;owner_key:string;owner_member_revision:number;reviewer_member_id:string;reviewer_key:string;reviewer_member_revision:number;worker_key:string;
 repository:string;base_branch:string;allowed_paths:string[];required_checks:Array<{name:string;app_id:number}>;
 runtime:'node22-static-v1';docker_image:string;test_command:string[];build_command:string[];preview_directory:string;
 max_jobs:number;max_attempts:number;max_model_calls:number;max_tokens:number;max_seconds:number;max_changed_files:number;max_changed_bytes:number;
 permissions:['read_source','edit_code','run_tests','open_pull_request','publish_preview'];issued_at:string;expires_at:string;
}
/** Historical installed connections may be refreshed; this record grants no work authority. */
export interface RepositoryCodingRefreshableConnection {setup_id:string;worker_key:string}
export interface RepositoryCodingRequest {type:'scopeblind.repository.coding-request.v1';id:string;workspace_id:string;mandate_digest:string;source:RepositoryCodingSource;owner_key:string;issued_at:string}
export interface RepositoryCodingStop {type:'scopeblind.repository.coding-stop.v1';id:string;workspace_id:string;mandate_digest:string;job_id?:string;principal_key:string;issued_at:string}
export type RepositoryCodingStatus='queued'|'running'|'testing'|'publishing'|'pr_ready'|'failed'|'cancelled'|'unknown'|'expired';
export interface RepositoryCodingFile {path:string;before_sha:string|null;content:string|null}
export interface RepositoryCodingTest {command_digest:string;exit_code:number;output_sha256:string;duration_ms:number}
export interface RepositoryCodingPlan {
 type:'scopeblind.repository.coding-plan.v1';job_id:string;request_digest:string;mandate_digest:string;source_head_sha:string;source_base_sha:string;
 branch:string;commit_sha:string;tree_sha:string;files:Array<{path:string;before_sha:string|null;after_sha:string|null;bytes:number}>;
 tests:RepositoryCodingTest;build:RepositoryCodingTest;preview_digest:string;model_calls:number;reserved_tokens:number;issued_at:string;
}
export interface RepositoryCodingPublication {type:'scopeblind.repository.coding-publication.v1';job_id:string;plan_digest:string;mandate_digest:string;request_digest:string;worker_key:string;lease_id:string;issued_at:string;expires_at:string}
export interface RepositoryCodingResult {
 type:'scopeblind.repository.coding-result.v1';job_id:string;plan_digest:string;publication_digest:string;repository:string;branch:string;head_sha:string;pull_number:number;pull_url:string;preview_url:string;preview_digest:string;deployment_id:number;deployment_status_id:number;deployment_environment:'ScopeBlind coding preview';check:{id:number;name:'ScopeBlind isolated coding checks';app_id:15368;head_sha:string;conclusion:'success'};observed_at:string;
}
export interface RepositoryCodingJob {
 type:'scopeblind.repository.coding-job.v1';request:Signed<RepositoryCodingRequest>;mandate:Signed<RepositoryCodingMandate>;adoption:Signed<RepositoryCodingMandate>;workspace:Signed<RepositoryWorkspaceState>;parent:RepositoryReviewEvidence;
 status:RepositoryCodingStatus;attempts:number;model_calls:number;reserved_tokens:number;lease_id:string|null;lease_expires_at:string|null;started_at:string|null;
 plan:Signed<RepositoryCodingPlan>|null;publication:Signed<RepositoryCodingPublication>|null;result:Signed<RepositoryCodingResult>|null;stop:Signed<RepositoryCodingStop>|null;error:string|null;observed_at:string;
}
export interface RepositoryCodingMandateView {mandate:Signed<RepositoryCodingMandate>;adoption:Signed<RepositoryCodingMandate>|null;revocation:Signed<RepositoryCodingStop>|null;status:'awaiting_reviewer'|'active'|'expired'|'revoked'|'membership_changed'|'exhausted';used_jobs:number}
export interface RepositoryCodingEvidence {type:'scopeblind.repository.coding-evidence.v1';job:Signed<RepositoryCodingJob>}
export interface RepositoryCodingModelContext {files:Array<{path:string;content:string}>;history:Array<{action:unknown;result:string}>}
export type RepositoryCodingModelAction={action:'write_file';path:string;content:string}|{action:'delete_file';path:string}|{action:'run_tests'|'finish'};
export const CODING_PERMISSIONS=['read_source','edit_code','run_tests','open_pull_request','publish_preview'] as const;
const object=(x:unknown):x is Record<string,unknown>=>!!x&&typeof x==='object'&&!Array.isArray(x);
const exact=(v:Record<string,unknown>,required:string[],optional:string[]=[])=>required.every(k=>Object.hasOwn(v,k))&&Object.keys(v).every(k=>required.includes(k)||optional.includes(k));
const key=(v:unknown)=>typeof v==='string'&&REPOSITORY_HEX.test(v),id=(v:unknown)=>typeof v==='string'&&REPOSITORY_ID.test(v);
const number=(v:unknown,min:number,max:number)=>Number.isSafeInteger(v)&&Number(v)>=min&&Number(v)<=max;
const at=(v:unknown)=>typeof v==='string'&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString()===v;
const hex40=(v:unknown)=>typeof v==='string'&&REPOSITORY_SHA.test(v);
export function validRepositoryCodingRefreshableConnections(v:unknown):v is RepositoryCodingRefreshableConnection[]{return Array.isArray(v)&&v.length<=20&&v.every(c=>object(c)&&exact(c,['setup_id','worker_key'])&&id(c.setup_id)&&key(c.worker_key))&&new Set(v.map(c=>c.setup_id)).size===v.length;}
export function codingSafePath(path:unknown):path is string {return typeof path==='string'&&repositoryPath(path)&&!path.toLowerCase().split('/').some(p=>p==='node_modules'||p==='.git'||p==='.github'||p==='.env'||p.startsWith('.env.')||p==='.npmrc'||p==='.yarnrc'||p==='.netrc')&&!/\.(pem|key|p12|pfx)$/i.test(path);}
export function codingCommand(v:unknown):v is string[]{return Array.isArray(v)&&v.length>=2&&v.length<=8&&v[0]==='node'&&v.slice(1).every(x=>typeof x==='string'&&x.length<=200)&&((v[1]==='--test'&&v.length>=3&&v.slice(2).every(codingSafePath))||(v.length===2&&codingSafePath(v[1])));}
export function validRepositoryCodingSource(v:unknown):v is RepositoryCodingSource{return object(v)&&exact(v,['task_id','task_digest','basis_digest','packet_digest','feedback_digest'])&&id(v.task_id)&&[v.task_digest,v.basis_digest,v.packet_digest,v.feedback_digest].every(key);}
export function validRepositoryCodingMandate(v:unknown):v is RepositoryCodingMandate {
 if(!object(v)||!exact(v,['type','id','workspace_id','workspace_digest','mode','owner_member_id','owner_key','owner_member_revision','reviewer_member_id','reviewer_key','reviewer_member_revision','worker_key','repository','base_branch','allowed_paths','required_checks','runtime','docker_image','test_command','build_command','preview_directory','max_jobs','max_attempts','max_model_calls','max_tokens','max_seconds','max_changed_files','max_changed_bytes','permissions','issued_at','expires_at']))return false;
 return v.type==='scopeblind.repository.coding-mandate.v1'&&v.mode==='edit_code'&&[v.id,v.workspace_id,v.owner_member_id,v.reviewer_member_id].every(id)&&[v.workspace_digest,v.owner_key,v.reviewer_key,v.worker_key].every(key)&&new Set([v.owner_key,v.reviewer_key,v.worker_key]).size===3&&v.owner_member_id!==v.reviewer_member_id&&number(v.owner_member_revision,1,1000)&&number(v.reviewer_member_revision,1,1000)&&typeof v.repository==='string'&&/^[A-Za-z0-9][A-Za-z0-9-]{0,38}\/[A-Za-z0-9_.-]{1,100}$/.test(v.repository)&&repositoryBranch(v.base_branch)&&Array.isArray(v.allowed_paths)&&v.allowed_paths.length>0&&v.allowed_paths.length<=12&&new Set(v.allowed_paths).size===v.allowed_paths.length&&v.allowed_paths.every(p=>typeof p==='string'&&codingSafePath(p.endsWith('/**')?p.slice(0,-3):p))&&Array.isArray(v.required_checks)&&v.required_checks.length>0&&v.required_checks.length<=12&&new Set(v.required_checks.map(c=>object(c)?c.name:null)).size===v.required_checks.length&&v.required_checks.every(c=>object(c)&&exact(c,['name','app_id'])&&typeof c.name==='string'&&c.name.length>0&&c.name.length<=100&&number(c.app_id,1,Number.MAX_SAFE_INTEGER))&&v.runtime==='node22-static-v1'&&typeof v.docker_image==='string'&&/^node@sha256:[a-f0-9]{64}$/.test(v.docker_image)&&codingCommand(v.test_command)&&codingCommand(v.build_command)&&codingSafePath(v.preview_directory)&&!pathAllowed(v.preview_directory,v.allowed_paths as string[])&&(v.allowed_paths as string[]).every(p=>p!==v.preview_directory&&!p.startsWith(String(v.preview_directory)+'/'))&&(v.test_command as string[]).slice(1).filter(p=>!p.startsWith('--')).every(p=>!pathAllowed(p,v.allowed_paths as string[]))&&(v.build_command as string[]).slice(1).every(p=>!pathAllowed(p,v.allowed_paths as string[]))&&number(v.max_jobs,1,3)&&number(v.max_attempts,1,2)&&number(v.max_model_calls,1,12)&&number(v.max_tokens,4096,524288)&&number(v.max_seconds,60,900)&&number(v.max_changed_files,1,20)&&number(v.max_changed_bytes,1,262144)&&JSON.stringify(v.permissions)===JSON.stringify(CODING_PERMISSIONS)&&at(v.issued_at)&&at(v.expires_at)&&Date.parse(String(v.expires_at))>Date.parse(String(v.issued_at))&&Date.parse(String(v.expires_at))-Date.parse(String(v.issued_at))<=86400000;
}
export function validRepositoryCodingRequest(v:unknown):v is RepositoryCodingRequest{return object(v)&&exact(v,['type','id','workspace_id','mandate_digest','source','owner_key','issued_at'])&&v.type==='scopeblind.repository.coding-request.v1'&&[v.id,v.workspace_id].every(id)&&[v.mandate_digest,v.owner_key].every(key)&&validRepositoryCodingSource(v.source)&&at(v.issued_at);}
export function validRepositoryCodingStop(v:unknown):v is RepositoryCodingStop{return object(v)&&exact(v,['type','id','workspace_id','mandate_digest','principal_key','issued_at'],['job_id'])&&v.type==='scopeblind.repository.coding-stop.v1'&&[v.id,v.workspace_id].every(id)&&[v.mandate_digest,v.principal_key].every(key)&&(v.job_id===undefined||id(v.job_id))&&at(v.issued_at);}
export function validRepositoryCodingPlan(v:unknown,m:RepositoryCodingMandate):v is RepositoryCodingPlan {
 return object(v)&&exact(v,['type','job_id','request_digest','mandate_digest','source_head_sha','source_base_sha','branch','commit_sha','tree_sha','files','tests','build','preview_digest','model_calls','reserved_tokens','issued_at'])&&v.type==='scopeblind.repository.coding-plan.v1'&&id(v.job_id)&&[v.request_digest,v.mandate_digest,v.preview_digest].every(key)&&[v.source_head_sha,v.source_base_sha,v.commit_sha,v.tree_sha].every(hex40)&&v.branch==='scopeblind/code/'+v.job_id&&Array.isArray(v.files)&&v.files.length>0&&v.files.length<=m.max_changed_files&&new Set(v.files.map(f=>object(f)?f.path:null)).size===v.files.length&&v.files.every(f=>object(f)&&exact(f,['path','before_sha','after_sha','bytes'])&&codingSafePath(f.path)&&pathAllowed(f.path,m.allowed_paths)&&(f.before_sha===null||hex40(f.before_sha))&&(f.after_sha===null||hex40(f.after_sha))&&f.before_sha!==f.after_sha&&number(f.bytes,0,m.max_changed_bytes))&&v.files.reduce((n,f)=>n+Number(f.bytes),0)<=m.max_changed_bytes&&[v.tests,v.build].every(t=>object(t)&&exact(t,['command_digest','exit_code','output_sha256','duration_ms'])&&key(t.command_digest)&&key(t.output_sha256)&&t.exit_code===0&&number(t.duration_ms,0,m.max_seconds*1000))&&number(v.model_calls,1,m.max_model_calls)&&number(v.reserved_tokens,4096,m.max_tokens)&&at(v.issued_at);
}
export function codingScopeWithin(paths:string[],m:RepositoryCodingMandate){return workspacePathsWithin(paths,m.allowed_paths);}

export function validRepositoryCodingResult(v:unknown):v is RepositoryCodingResult{return object(v)&&exact(v,['type','job_id','plan_digest','publication_digest','repository','branch','head_sha','pull_number','pull_url','preview_url','preview_digest','deployment_id','deployment_status_id','deployment_environment','check','observed_at'])&&v.type==='scopeblind.repository.coding-result.v1'&&id(v.job_id)&&[v.plan_digest,v.publication_digest,v.preview_digest].every(key)&&hex40(v.head_sha)&&typeof v.repository==='string'&&typeof v.branch==='string'&&number(v.pull_number,1,Number.MAX_SAFE_INTEGER)&&v.pull_url===`https://github.com/${v.repository}/pull/${v.pull_number}`&&typeof v.preview_url==='string'&&v.preview_url.startsWith('https://')&&number(v.deployment_id,1,Number.MAX_SAFE_INTEGER)&&number(v.deployment_status_id,1,Number.MAX_SAFE_INTEGER)&&v.deployment_environment==='ScopeBlind coding preview'&&object(v.check)&&exact(v.check,['id','name','app_id','head_sha','conclusion'])&&number(v.check.id,1,Number.MAX_SAFE_INTEGER)&&v.check.name==='ScopeBlind isolated coding checks'&&v.check.app_id===15368&&v.check.head_sha===v.head_sha&&v.check.conclusion==='success'&&at(v.observed_at);}
