import {canonical,sha256,verify,type Signed} from './coordination-protocol.js';
import {pathAllowed,validRepositoryEnvelope,verifyRepositoryEvidence,type RepositoryEvidence,type RepositoryState} from './coordination-repository.js';
import {verifyRepositoryCollaborationEvidence,type RepositoryCollaborationEvidence} from './coordination-repository-collaboration-evidence.js';
import {validRepositoryReviewBrief,validRepositoryReviewPacket,validRepositoryReviewDecision,validRepositoryReviewFeedback,validRepositoryReviewRecommendation,type RepositoryReviewState} from './coordination-repository-review.js';
import {validWorkspacePreparationMandate,validWorkspaceTaskAssignment,validWorkspaceReviewDraft,type WorkspaceReviewDraft,type WorkspaceTaskAssignment,type WorkspacePreparationMandate} from './coordination-repository-workspace.js';
export interface RepositoryReviewOrigin {draft:Signed<WorkspaceReviewDraft>;assignment:Signed<WorkspaceTaskAssignment>;parent_assignment:Signed<WorkspaceTaskAssignment>;parent:Omit<RepositoryReviewEvidence,'origin'>;preparation:{mandate:Signed<WorkspacePreparationMandate>;adoption:Signed<WorkspacePreparationMandate>}}
export interface RepositoryReviewEvidence {type:'scopeblind.repository.review-evidence.v1';repository:RepositoryEvidence|RepositoryCollaborationEvidence;review:Signed<RepositoryReviewState>;origin?:RepositoryReviewOrigin}
export type RepositoryReviewPins=string|{authority_key:string;owner_key?:string;reviewer_key?:string;receiver_key?:string};
const shape=(v:unknown,keys:string[],optional:string[]=[]):boolean=>!!v&&typeof v==='object'&&!Array.isArray(v)&&keys.every(k=>Object.prototype.hasOwnProperty.call(v,k))&&Object.keys(v).every(k=>keys.includes(k)||optional.includes(k));
const at=(v:unknown):v is string=>typeof v==='string'&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString()===v;
export function repositoryReviewCore(e:RepositoryReviewEvidence):RepositoryEvidence{return e.repository.type==='scopeblind.repository.evidence.v1'?e.repository:e.repository.repository;}
/** Historical signatures remain checkable after expiry. This function never reports an assessment as code correctness. */
export async function verifyRepositoryReviewEvidence(value:unknown,pins?:RepositoryReviewPins){
 const errors:string[]=[],check=(condition:unknown,message:string)=>{if(!condition)errors.push(message);};let originVerified=false,accepted=false,packetVerified=false,decisionsVerified=false,previewAvailable=false,authorityPinned=false;
 try{
  const e=value as RepositoryReviewEvidence;check((shape(e,['type','repository','review'])||shape(e,['type','repository','review','origin']))&&e.type==='scopeblind.repository.review-evidence.v1','Review evidence shape is invalid');
  const core=repositoryReviewCore(e),base=e.repository.type==='scopeblind.repository.evidence.v1'?await verifyRepositoryEvidence(e.repository,pins):await verifyRepositoryCollaborationEvidence(e.repository,pins),s=core.state.payload,r=e.review.payload,t=s.task.payload,key=typeof pins==='string'?pins:pins?.authority_key??t.authority_key;
  check(base.valid,'Underlying repository evidence is invalid');accepted=base.accepted;authorityPinned=base.authorityPinned;
  check(validRepositoryEnvelope(e.review)&&shape(r,['type','task_id','task_digest','brief','packet','decisions','feedback','recommendations','history','agent_uses','observed_at'],['origin_digest'])&&r.type==='scopeblind.repository.review-state.v1'&&r.task_id===t.id&&r.task_digest===s.task.digest&&at(r.observed_at)&&Date.parse(r.observed_at)>=Date.parse(s.observed_at)&&await verify(e.review,key),'Review service state is invalid');
  check(validRepositoryEnvelope(r.brief)&&validRepositoryReviewBrief(r.brief.payload,t,s.task.digest)&&Date.parse(r.brief.payload.issued_at)<=Date.parse(r.observed_at)&&await verify(r.brief,t.owner_key),'Owner review brief is invalid');
  check(Array.isArray(r.decisions)&&r.decisions.length<=2&&new Set(r.decisions.map(d=>d.payload.role)).size===r.decisions.length&&Array.isArray(r.feedback)&&r.feedback.length<=20&&new Set(r.feedback.map(f=>f.payload.id)).size===r.feedback.length&&Array.isArray(r.recommendations)&&r.recommendations.length<=20&&new Set(r.recommendations.map(f=>f.payload.id)).size===r.recommendations.length&&Array.isArray(r.history)&&r.history.length<=40&&new Set(r.history.map(h=>h.state.digest+':'+h.packet.digest)).size===r.history.length,'Review record bounds are invalid');
  check(Array.isArray(r.agent_uses)&&r.agent_uses.length<=40&&new Set(r.agent_uses.map(u=>u.payload.record_digest)).size===r.agent_uses.length,'Agent-use record bounds are invalid');
  if(r.packet){packetVerified=!!s.proposal&&validRepositoryEnvelope(r.packet)&&validRepositoryReviewPacket(r.packet.payload,r.brief,s.proposal)&&Date.parse(r.packet.payload.observed_at)<=Date.parse(r.observed_at)&&await verify(r.packet,t.receiver_key);check(packetVerified,'Receiver review packet is invalid');previewAvailable=packetVerified&&r.packet.payload.preview.status==='available';}
  else check(!r.decisions.length&&!s.execution,'Exact packet decisions require a current packet');
  for(const decision of r.decisions){const a=s.approvals.find(a=>a.payload.role===decision.payload.role),principal=decision.payload.role==='owner'?t.owner_key:s.reviewer?.payload.reviewer_key;check(a&&r.packet&&validRepositoryEnvelope(decision)&&validRepositoryReviewDecision(decision.payload,r.brief,r.packet,a)&&decision.payload.principal_key===principal&&await verify(decision,principal)&&Date.parse(decision.payload.issued_at)<=Date.parse(r.observed_at),'Exact packet decision is invalid');}
  check(r.decisions.length===s.approvals.length&&s.approvals.every(a=>r.decisions.some(d=>d.payload.role===a.payload.role&&d.payload.approval_digest===a.digest)),'Each ordinary approval requires its exact packet decision');
  decisionsVerified=packetVerified&&r.decisions.length===2&&s.approvals.length===2&&s.approvals.every(a=>a.payload.decision==='approve');
  if(s.execution)check(decisionsVerified&&r.packet&&Date.parse(s.execution.payload.expires_at)<=Date.parse(r.packet.payload.expires_at),'Execution lacks both exact current packet decisions');
  const contexts=r.packet?[{state:core.state,packet:r.packet}]:[];
  for(const h of r.history){
   check(shape(h,['state','packet','decisions'])&&(await verifyRepositoryEvidence({type:'scopeblind.repository.evidence.v1',state:h.state},pins??key)).valid&&h.state.payload.task.digest===s.task.digest&&h.state.payload.reviewer?.digest===s.reviewer?.digest&&Date.parse(h.state.payload.observed_at)<=Date.parse(r.observed_at)&&h.state.payload.proposal&&validRepositoryEnvelope(h.packet)&&validRepositoryReviewPacket(h.packet.payload,r.brief,h.state.payload.proposal)&&await verify(h.packet,t.receiver_key),'Historical review basis is invalid');contexts.push(h);
   check(Array.isArray(h.decisions)&&h.decisions.length<=2&&new Set(h.decisions.map(d=>d.payload.role)).size===h.decisions.length,'Historical packet decisions are invalid');
   for(const decision of h.decisions){const approval=h.state.payload.approvals.find(a=>a.payload.role===decision.payload.role),principal=decision.payload.role==='owner'?t.owner_key:s.reviewer?.payload.reviewer_key;check(approval&&validRepositoryEnvelope(decision)&&validRepositoryReviewDecision(decision.payload,r.brief,h.packet,approval)&&decision.payload.principal_key===principal&&await verify(decision,principal),'Historical exact packet decision is invalid');}
   check(h.decisions.length===h.state.payload.approvals.length&&h.state.payload.approvals.every(a=>h.decisions.some(d=>d.payload.role===a.payload.role&&d.payload.approval_digest===a.digest)),'Each historical approval requires its exact packet decision');
   if(h.state.payload.execution)check(h.decisions.length===2&&Date.parse(h.state.payload.execution.payload.expires_at)<=Date.parse(h.packet.payload.expires_at),'Historical execution lacks both exact packet decisions');
   check(r.feedback.some(f=>f.payload.packet_digest===h.packet.digest&&(f.payload.basis_digest===h.state.payload.proposal?.digest||f.payload.basis_digest===h.state.payload.outcome?.digest||f.payload.basis_digest===h.state.payload.acceptance?.digest))||r.recommendations.some(a=>a.payload.packet_digest===h.packet.digest&&a.payload.proposal_digest===h.state.payload.proposal?.digest),'Unreferenced review history is invalid');
  }
  const uses=new Map<string,typeof r.agent_uses[number]>();
  for(const use of r.agent_uses){const u=use.payload,m=u.mandate?.payload,a=u.assignment?.payload,record=[...r.feedback,...r.recommendations].find(x=>x.digest===u.record_digest),recordTime=record?(record.payload as {issued_at?:string;observed_at?:string}).issued_at??(record.payload as {observed_at:string}).observed_at:'';
   check(validRepositoryEnvelope(use)&&shape(u,['type','task_id','task_digest','record_digest','permission','mandate','adoption','assignment','checked_at'])&&u.type==='scopeblind.repository.review-agent-use.v1'&&u.task_id===t.id&&u.task_digest===s.task.digest&&await verify(use,key)&&record&&at(u.checked_at)&&Date.parse(u.checked_at)<=Date.parse(r.observed_at)&&Date.parse(u.checked_at)>=Date.parse(recordTime),'Agent-use service attestation is invalid');
   check(validRepositoryEnvelope(u.mandate)&&validRepositoryEnvelope(u.adoption)&&validWorkspacePreparationMandate(m)&&m.owner_key===t.owner_key&&m.reviewer_key===s.reviewer?.payload.reviewer_key&&!['',t.owner_key,t.receiver_key,t.authority_key,s.reviewer?.payload.reviewer_key].includes(m.agent_key)&&m.repository===t.repository&&m.base_branch===t.base_branch&&u.adoption.digest===u.mandate.digest&&canonical(u.adoption.payload)===canonical(m)&&await verify(u.mandate,t.owner_key)&&await verify(u.adoption,m.reviewer_key)&&m.permissions.includes(u.permission)&&['report_criteria','request_revision'].includes(u.permission)&&Date.parse(m.issued_at)<=Date.parse(recordTime)&&Date.parse(m.expires_at)>=Date.parse(u.checked_at)&&t.allowed_paths.every(p=>m.allowed_paths.includes(p)||m.allowed_paths.some(scope=>scope.endsWith('/**')&&p.startsWith(scope.slice(0,-2))))&&m.required_checks.every(c=>t.required_checks.some(tc=>tc.name===c.name&&tc.app_id===c.app_id)),'Dual-signed preparation mandate is invalid');
   check(validRepositoryEnvelope(u.assignment)&&validWorkspaceTaskAssignment(a)&&a.task_id===t.id&&a.task_digest===s.task.digest&&a.review_brief_digest===r.brief.digest&&a.workspace_id===m.workspace_id&&a.workspace_digest===m.workspace_digest&&a.owner_key===t.owner_key&&a.reviewer_key===s.reviewer?.payload.reviewer_key&&a.owner_member_id===m.owner_member_id&&a.reviewer_member_id===m.reviewer_member_id&&a.owner_member_revision===m.owner_member_revision&&a.reviewer_member_revision===m.reviewer_member_revision&&Date.parse(a.issued_at)<=Date.parse(recordTime)&&Date.parse(a.expires_at)>=Date.parse(u.checked_at)&&await verify(u.assignment,t.owner_key),'Task assignment for the agent use is invalid');uses.set(u.record_digest,use);
  }
  for(const feedback of r.feedback){const f=feedback.payload,c=contexts.find(c=>c.packet.digest===f.packet_digest&&[c.state.payload.proposal?.digest,c.state.payload.outcome?.digest,c.state.payload.acceptance?.digest].includes(f.basis_digest));
   check(c&&validRepositoryEnvelope(feedback)&&validRepositoryReviewFeedback(f,r.brief,c.packet)&&await verify(feedback,f.requester_key)&&Date.parse(f.issued_at)<=Date.parse(r.observed_at),'Review feedback is invalid');
   const use=uses.get(feedback.digest)?.payload;check(f.mandate_digest?use&&use.permission==='request_revision'&&use.mandate.digest===f.mandate_digest&&use.mandate.payload.agent_key===f.requester_key:!use&&[t.owner_key,s.reviewer?.payload.reviewer_key].includes(f.requester_key),'Review feedback lacks independently verifiable human or scoped-agent authority');
  }
  for(const recommendation of r.recommendations){const a=recommendation.payload,c=contexts.find(c=>c.packet.digest===a.packet_digest&&c.state.payload.proposal?.digest===a.proposal_digest);
   check(c&&validRepositoryEnvelope(recommendation)&&validRepositoryReviewRecommendation(a,r.brief,c.packet,c.state.payload.proposal!)&&await verify(recommendation,a.agent_key)&&Date.parse(a.observed_at)<=Date.parse(r.observed_at),'Criterion recommendation is invalid');
   const use=uses.get(recommendation.digest)?.payload;check(use&&use.permission==='report_criteria'&&use.mandate.digest===a.mandate_digest&&use.mandate.payload.agent_key===a.agent_key,'Recommendation lacks independently verifiable scoped-agent authority');
  }
  check(e.origin?r.origin_digest===await sha256(canonical(e.origin)):r.origin_digest===undefined,'Registered origin commitment is missing or mismatched');
  if(e.origin){
   const o=e.origin;check(shape(o,['draft','assignment','parent_assignment','parent','preparation'])&&!Object.prototype.hasOwnProperty.call(o.parent,'origin')&&shape(o.preparation,['mandate','adoption']),'Review origin shape or depth is invalid');
   if(!shape(o.parent,['type','repository','review']))throw Error('Nested origin is forbidden');
   const parent=await verifyRepositoryReviewEvidence(o.parent,key),ps=repositoryReviewCore(o.parent).state.payload,d=o.draft.payload,a=o.assignment.payload,m=o.preparation.mandate.payload,source=d.source;
   check(parent.valid&&validRepositoryEnvelope(o.draft)&&validWorkspaceReviewDraft(d)&&source&&d.repository===t.repository&&d.pull_number===t.pull_number&&d.workspace_id===a.workspace_id&&d.mandate_digest===o.preparation.mandate.digest&&d.agent_key===m.agent_key&&await verify(o.draft,d.agent_key),'Incoming review draft is invalid');
   const pa=o.parent_assignment?.payload;check(validRepositoryEnvelope(o.parent_assignment)&&validWorkspaceTaskAssignment(pa)&&pa.task_id===ps.task.payload.id&&pa.task_digest===ps.task.digest&&pa.review_brief_digest===o.parent.review.payload.brief.digest&&pa.workspace_id===a.workspace_id&&pa.workspace_digest===a.workspace_digest&&pa.owner_key===ps.task.payload.owner_key&&pa.reviewer_key===ps.reviewer?.payload.reviewer_key&&await verify(o.parent_assignment,ps.task.payload.owner_key),'Source task project assignment is invalid');
   const feedback=source?o.parent.review.payload.feedback.find(f=>f.digest===source.feedback_digest):undefined;
   check(source&&ps.task.payload.id===source.task_id&&ps.task.digest===source.task_digest&&ps.task.payload.repository===t.repository&&ps.task.payload.authority_key===t.authority_key&&ps.task.payload.receiver_key===t.receiver_key&&o.parent.review.payload.packet?.digest===source.packet_digest&&feedback&&feedback.payload.basis_digest===source.basis_digest&&feedback.payload.packet_digest===source.packet_digest&&Date.parse(feedback.payload.issued_at)<=Date.parse(d.issued_at)&&Date.parse(ps.observed_at)<=Date.parse(d.issued_at)&&o.parent.review.payload.feedback.length===1&&o.parent.review.payload.recommendations.length===0,'Incoming source feedback does not match the frozen parent');
   check(validRepositoryEnvelope(o.assignment)&&validWorkspaceTaskAssignment(a)&&a.task_id===t.id&&a.task_digest===s.task.digest&&a.review_brief_digest===r.brief.digest&&a.source_draft_digest===o.draft.digest&&a.owner_key===t.owner_key&&a.reviewer_key===m.reviewer_key&&(!s.reviewer||a.reviewer_key===s.reviewer.payload.reviewer_key)&&a.workspace_id===m.workspace_id&&a.workspace_digest===m.workspace_digest&&a.owner_member_id===m.owner_member_id&&a.reviewer_member_id===m.reviewer_member_id&&a.owner_member_revision===m.owner_member_revision&&a.reviewer_member_revision===m.reviewer_member_revision&&Date.parse(a.issued_at)>=Date.parse(d.issued_at)&&Date.parse(a.issued_at)<=Date.parse(r.observed_at)&&await verify(o.assignment,t.owner_key),'Incoming task assignment is invalid');
   check(validRepositoryEnvelope(o.preparation.mandate)&&validRepositoryEnvelope(o.preparation.adoption)&&validWorkspacePreparationMandate(m)&&m.owner_key===t.owner_key&&m.repository===t.repository&&m.base_branch===t.base_branch&&m.permissions.includes('prepare_review')&&![t.owner_key,t.receiver_key,t.authority_key,m.reviewer_key].includes(d.agent_key)&&canonical(o.preparation.adoption.payload)===canonical(m)&&o.preparation.adoption.digest===o.preparation.mandate.digest&&await verify(o.preparation.mandate,m.owner_key)&&await verify(o.preparation.adoption,m.reviewer_key)&&Date.parse(d.issued_at)>=Date.parse(m.issued_at)&&Date.parse(d.issued_at)<=Date.parse(m.expires_at)&&d.allowed_paths.every(p=>m.allowed_paths.includes(p)||m.allowed_paths.some(scope=>scope.endsWith('/**')&&p.startsWith(scope.slice(0,-2))))&&m.required_checks.every(c=>d.required_checks.some(dc=>dc.name===c.name&&dc.app_id===c.app_id)),'Incoming draft preparation authority is invalid');originVerified=true;
  }
 }catch{errors.push('Malformed review evidence');}
 return {valid:errors.length===0,errors,originVerified:originVerified&&errors.length===0,accepted:accepted&&errors.length===0,authorityPinned:authorityPinned&&errors.length===0,packetVerified:packetVerified&&errors.length===0,previewAvailable:previewAvailable&&errors.length===0,decisionsVerified:decisionsVerified&&errors.length===0,limitations:['A receiver signature records GitHub API metadata; it is not a GitHub-signed receipt.','An external preview URL is mutable. Its observed commit association does not pin the bytes the browser later receives.','An observed artifact digest does not prove that a preview URL serves that artifact.','A pinned check provider identifies the check issuer, not necessarily the deployment publisher.','Agent criterion assessments are recommendations, not independent proof, human review, or execution authority.','The service attests that membership, revocation and counters were checked atomically when each recorded agent use was accepted. This is historical authority, not a current grant.','This controls only the installed receiver. Other repository credentials and actions remain outside its coverage.',...(!pins?['No independent authority key was supplied. Only consistency with the included authority was checked.']:[])]};
}
