/** Real repository tasks. Browser/Worker/Node contract; no credentials or I/O. */
import {canonical,sha256,verify,type Signed} from './coordination-protocol.js';

export const REPOSITORY_ACTIONS=['repository_create','repository_get','repository_claim','repository_propose','repository_approve','repository_cancel','repository_begin','repository_outcome','repository_accept','repository_export'] as const;
export type RepositoryAction=typeof REPOSITORY_ACTIONS[number];
export interface RepositoryTask {
 type:'scopeblind.repository.task.v1';id:string;title:string;repository:string;pull_number:number;base_branch:string;
 owner_key:string;receiver_key:string;authority_key:string;allowed_paths:string[];required_checks:Array<{name:string;app_id:number}>;
 reviewer_secret_hash:string;issued_at:string;expires_at:string;
}
export interface RepositoryClaim {type:'scopeblind.repository.claim.v1';task_id:string;task_digest:string;reviewer_key:string;name:string;issued_at:string}
export interface RepositoryFile {path:string;previous_path?:string;status:'added'|'modified'|'removed'|'renamed';mode:'100644'|'100755';additions:number;deletions:number;patch?:string;patch_truncated?:true}
export interface RepositoryCheck {id:number;name:string;app_id:number;head_sha:string;conclusion:'success'}
export interface RepositoryProposal {
 type:'scopeblind.repository.proposal.v1';id:string;task_id:string;task_digest:string;repository_id:string;
 base_ref:string;head_ref:string;base_sha:string;head_sha:string;merge_sha:string;tree_sha:string;
 files:RepositoryFile[];checks:RepositoryCheck[];observed_at:string;
}
export interface RepositoryApproval {type:'scopeblind.repository.approval.v1';task_id:string;task_digest:string;proposal_digest:string;role:'owner'|'reviewer';principal_key:string;decision:'approve'|'reject';issued_at:string;expires_at:string;note:string}
export interface RepositoryExecution {type:'scopeblind.repository.execution.v1';operation_id:string;receiver_attempt_id:string;task_id:string;task_digest:string;proposal_digest:string;owner_approval_digest:string;reviewer_approval_digest:string;receiver_key:string;action:'github.updateRefs';issued_at:string;expires_at:string}
export interface RepositoryOutcome {type:'scopeblind.repository.outcome.v1';operation_id:string;task_id:string;task_digest:string;proposal_digest:string;execution_digest:string;status:'confirmed'|'failed'|'unknown';observed_base_sha:string|null;readback:'exact_ref'|'descendant_ref'|'not_confirmed';github_request_id?:string;observed_at:string;note:string}
export interface RepositoryAcceptance {type:'scopeblind.repository.acceptance.v1';task_id:string;task_digest:string;outcome_digest:string;reviewer_key:string;decision:'accept'|'request_changes';issued_at:string;note:string}
export interface RepositoryState {
 type:'scopeblind.repository.state.v1';task:Signed<RepositoryTask>;reviewer:Signed<RepositoryClaim>|null;proposal:Signed<RepositoryProposal>|null;approvals:Signed<RepositoryApproval>[];execution:Signed<RepositoryExecution>|null;outcome:Signed<RepositoryOutcome>|null;acceptance:Signed<RepositoryAcceptance>|null;
 status:'awaiting_reviewer'|'awaiting_snapshot'|'review'|'approved'|'executing'|'confirmed'|'unknown'|'failed'|'rejected'|'cancelled'|'accepted'|'changes_requested';revision:number;observed_at:string;
}
export interface RepositoryEvidence {type:'scopeblind.repository.evidence.v1';state:Signed<RepositoryState>}
export const REPOSITORY_HEX=/^[0-9a-f]{64}$/,REPOSITORY_SHA=/^[0-9a-f]{40}$/,REPOSITORY_ID=/^[A-Za-z0-9_-]{8,100}$/;
const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const text=(v:unknown,n:number)=>typeof v==='string'&&v.length>0&&v.length<=n&&!/[\u0000-\u001f\u007f]/.test(v);
const time=(v:unknown)=>typeof v==='string'&&Number.isFinite(Date.parse(v));
const exact=(v:Record<string,unknown>,required:string[],optional:string[]=[])=>required.every(k=>k in v)&&Object.keys(v).every(k=>required.includes(k)||optional.includes(k));
export function repositoryPath(path:unknown):path is string{return text(path,300)&&!(path as string).startsWith('/')&&!(path as string).endsWith('/')&&!(path as string).includes('\\')&&!(path as string).split('/').some(p=>!p||p==='.'||p==='..'||p.toLowerCase()==='.git');}
export function repositoryBranch(branch:unknown):branch is string{return text(branch,150)&&!(branch as string).includes('..')&&!/[~^:?*\[\\\s]/.test(branch as string)&&!(branch as string).startsWith('/')&&!(branch as string).endsWith('/')&&!(branch as string).endsWith('.lock')&&!(branch as string).includes('@{')&&!(branch as string).split('/').some(p=>!p||p.startsWith('.')||p.endsWith('.'));}
export function pathAllowed(path:string,allowed:string[]):boolean {
 // The privileged receiver never accepts changes to workflow/control files.
 if(!repositoryPath(path)||/^\.github(?:\/|$)/i.test(path)||/(^|\/)(?:\.gitmodules|CODEOWNERS)$/i.test(path))return false;
 return allowed.some(rule=>rule.endsWith('/**')?path.startsWith(rule.slice(0,-2)):path===rule);
}
export function validRepositoryTask(v:unknown):v is RepositoryTask {
 if(!object(v)||!exact(v,['type','id','title','repository','pull_number','base_branch','owner_key','receiver_key','authority_key','allowed_paths','required_checks','reviewer_secret_hash','issued_at','expires_at']))return false;
 return v.type==='scopeblind.repository.task.v1'&&REPOSITORY_ID.test(String(v.id))&&text(v.title,140)&&typeof v.repository==='string'&&/^[A-Za-z0-9][A-Za-z0-9-]{0,38}\/[A-Za-z0-9_.-]{1,100}$/.test(v.repository)&&Number.isSafeInteger(v.pull_number)&&Number(v.pull_number)>0&&repositoryBranch(v.base_branch)&&[v.owner_key,v.receiver_key,v.authority_key,v.reviewer_secret_hash].every(x=>typeof x==='string'&&REPOSITORY_HEX.test(x))&&v.owner_key!==v.receiver_key&&v.owner_key!==v.authority_key&&v.receiver_key!==v.authority_key&&Array.isArray(v.allowed_paths)&&v.allowed_paths.length>0&&v.allowed_paths.length<=12&&new Set(v.allowed_paths).size===v.allowed_paths.length&&v.allowed_paths.every(p=>typeof p==='string'&&repositoryPath(p.endsWith('/**')?p.slice(0,-3):p)&&pathAllowed(p.endsWith('/**')?p.slice(0,-2)+'placeholder':p,[p]))&&Array.isArray(v.required_checks)&&v.required_checks.length>0&&v.required_checks.length<=12&&v.required_checks.every(c=>object(c)&&exact(c,['name','app_id'])&&text(c.name,100)&&Number.isSafeInteger(c.app_id)&&Number(c.app_id)>0)&&new Set(v.required_checks.map(c=>canonical(c))).size===v.required_checks.length&&time(v.issued_at)&&time(v.expires_at)&&Date.parse(String(v.expires_at))>Date.parse(String(v.issued_at))&&Date.parse(String(v.expires_at))-Date.parse(String(v.issued_at))<=7*86400000;
}
export function validRepositoryProposal(v:unknown,task:RepositoryTask,taskDigest:string):v is RepositoryProposal {
 if(!object(v)||!exact(v,['type','id','task_id','task_digest','repository_id','base_ref','head_ref','base_sha','head_sha','merge_sha','tree_sha','files','checks','observed_at']))return false;
 if(v.type!=='scopeblind.repository.proposal.v1'||!REPOSITORY_ID.test(String(v.id))||v.task_id!==task.id||v.task_digest!==taskDigest||!text(v.repository_id,100)||v.base_ref!==`refs/heads/${task.base_branch}`||typeof v.head_ref!=='string'||!v.head_ref.startsWith('refs/heads/')||!repositoryBranch(v.head_ref.slice(11))||v.head_ref===v.base_ref||![v.base_sha,v.head_sha,v.merge_sha,v.tree_sha].every(s=>typeof s==='string'&&REPOSITORY_SHA.test(s))||v.base_sha===v.head_sha||v.merge_sha===v.base_sha||!time(v.observed_at))return false;
 if(!Array.isArray(v.files)||!v.files.length||v.files.length>50||new Set(v.files.map(f=>object(f)?f.path:null)).size!==v.files.length||!v.files.every(f=>object(f)&&exact(f,['path','status','mode','additions','deletions'],['previous_path','patch','patch_truncated'])&&typeof f.path==='string'&&pathAllowed(f.path,task.allowed_paths)&&['added','modified','removed','renamed'].includes(String(f.status))&&['100644','100755'].includes(String(f.mode))&&Number.isSafeInteger(f.additions)&&Number(f.additions)>=0&&Number.isSafeInteger(f.deletions)&&Number(f.deletions)>=0&&(f.patch===undefined||typeof f.patch==='string'&&f.patch.length<=400)&&(f.patch_truncated===undefined||f.patch_truncated===true)&&(f.status==='renamed'?typeof f.previous_path==='string'&&pathAllowed(f.previous_path,task.allowed_paths):f.previous_path===undefined)))return false;
 return Array.isArray(v.checks)&&v.checks.length===task.required_checks.length&&v.checks.every(c=>object(c)&&exact(c,['id','name','app_id','head_sha','conclusion'])&&Number.isSafeInteger(c.id)&&Number(c.id)>0&&c.head_sha===v.head_sha&&c.conclusion==='success'&&task.required_checks.some(r=>r.name===c.name&&r.app_id===c.app_id))&&new Set(v.checks.map(c=>`${c.name}:${c.app_id}`)).size===v.checks.length;
}
export async function repositorySnapshotDigest(p:RepositoryProposal):Promise<string>{const {id,observed_at,...snapshot}=p;return sha256(canonical(snapshot));}

/** Strict signed records: unknown authority-bearing fields fail closed. */
export function validRepositoryRecord(v:unknown,kind:'claim'|'approval'|'execution'|'outcome'|'acceptance'):boolean {
 if(!object(v)||v.type!==`scopeblind.repository.${kind}.v1`||!REPOSITORY_ID.test(String(v.task_id))||!REPOSITORY_HEX.test(String(v.task_digest)))return false;
 const common=['type','task_id','task_digest'];
 if(kind==='claim')return exact(v,[...common,'reviewer_key','name','issued_at'])&&REPOSITORY_HEX.test(String(v.reviewer_key))&&text(v.name,60)&&time(v.issued_at);
 const note=(v:unknown)=>typeof v==='string'&&v.length<=600;
 if(kind==='approval')return exact(v,[...common,'proposal_digest','role','principal_key','decision','issued_at','expires_at','note'])&&REPOSITORY_HEX.test(String(v.proposal_digest))&&REPOSITORY_HEX.test(String(v.principal_key))&&['owner','reviewer'].includes(String(v.role))&&['approve','reject'].includes(String(v.decision))&&time(v.issued_at)&&time(v.expires_at)&&note(v.note)&&Date.parse(String(v.expires_at))>Date.parse(String(v.issued_at))&&Date.parse(String(v.expires_at))-Date.parse(String(v.issued_at))<=900000;
 if(kind==='execution')return exact(v,[...common,'operation_id','receiver_attempt_id','proposal_digest','owner_approval_digest','reviewer_approval_digest','receiver_key','action','issued_at','expires_at'])&&[v.operation_id,v.receiver_attempt_id].every(x=>REPOSITORY_ID.test(String(x)))&&[v.proposal_digest,v.owner_approval_digest,v.reviewer_approval_digest,v.receiver_key].every(x=>REPOSITORY_HEX.test(String(x)))&&v.action==='github.updateRefs'&&time(v.issued_at)&&time(v.expires_at)&&Date.parse(String(v.expires_at))>Date.parse(String(v.issued_at))&&Date.parse(String(v.expires_at))-Date.parse(String(v.issued_at))<=120000;
 if(kind==='outcome')return exact(v,[...common,'operation_id','proposal_digest','execution_digest','status','observed_base_sha','readback','observed_at','note'],['github_request_id'])&&REPOSITORY_ID.test(String(v.operation_id))&&[v.proposal_digest,v.execution_digest].every(x=>REPOSITORY_HEX.test(String(x)))&&['confirmed','failed','unknown'].includes(String(v.status))&&(v.observed_base_sha===null||REPOSITORY_SHA.test(String(v.observed_base_sha)))&&['exact_ref','descendant_ref','not_confirmed'].includes(String(v.readback))&&(v.status==='confirmed'?v.readback!=='not_confirmed'&&v.observed_base_sha!==null:v.readback==='not_confirmed')&&time(v.observed_at)&&note(v.note)&&(v.github_request_id===undefined||text(v.github_request_id,200));
 return exact(v,[...common,'outcome_digest','reviewer_key','decision','issued_at','note'])&&[v.outcome_digest,v.reviewer_key].every(x=>REPOSITORY_HEX.test(String(x)))&&['accept','request_changes'].includes(String(v.decision))&&time(v.issued_at)&&note(v.note);
}
export const validRepositoryEnvelope=(e:unknown)=>object(e)&&exact(e,['payload','signer','digest','signature']);
/** Verifies recorded signatures and bindings, not GitHub's independent truth.
 * GitHub API observations are attested by the explicitly trusted receiver. */
export async function verifyRepositoryEvidence(value:unknown,pin?:string|{authority_key:string;owner_key?:string;reviewer_key?:string;receiver_key?:string}):Promise<{valid:boolean;errors:string[];accepted:boolean;authorityPinned:boolean;limitations:string[]}>{
 const pins=typeof pin==='string'?{authority_key:pin}:pin??{authority_key:(value as RepositoryEvidence)?.state?.payload?.task?.payload?.authority_key};
 const errors:string[]=[];let accepted=false;const check=(condition:unknown,message:string)=>{if(!condition)errors.push(message);};
 try{
  const e=value as RepositoryEvidence,s=e.state?.payload,t=s?.task?.payload;
  check(object(e)&&exact(e as unknown as Record<string,unknown>,['type','state'])&&e.type==='scopeblind.repository.evidence.v1'&&validRepositoryEnvelope(e.state)&&!!s&&s.type==='scopeblind.repository.state.v1'&&exact(s as unknown as Record<string,unknown>,['type','task','reviewer','proposal','approvals','execution','outcome','acceptance','status','revision','observed_at'])&&Number.isSafeInteger(s.revision)&&s.revision>0&&time(s.observed_at)&&await verify(e.state,pins.authority_key),'Service state signature or shape is invalid');
  check(validRepositoryEnvelope(s.task)&&validRepositoryTask(t)&&await verify(s.task,t.owner_key)&&t.authority_key===pins.authority_key&&(!pins.owner_key||pins.owner_key===t.owner_key)&&(!pins.receiver_key||pins.receiver_key===t.receiver_key)&&Date.parse(s.observed_at)>=Date.parse(t.issued_at),'Task or pinned owner/receiver is invalid');
  const reviewer=s.reviewer?.payload;
  if(s.reviewer)check(validRepositoryEnvelope(s.reviewer)&&validRepositoryRecord(reviewer,'claim')&&reviewer!.task_id===t.id&&reviewer!.task_digest===s.task.digest&&![t.owner_key,t.receiver_key,t.authority_key].includes(reviewer!.reviewer_key)&&await verify(s.reviewer,reviewer!.reviewer_key)&&(!pins.reviewer_key||pins.reviewer_key===reviewer!.reviewer_key)&&Date.parse(reviewer!.issued_at)>=Date.parse(t.issued_at)&&Date.parse(reviewer!.issued_at)<Date.parse(t.expires_at),'Reviewer role is invalid');
  if(s.proposal)check(!!reviewer&&validRepositoryEnvelope(s.proposal)&&validRepositoryProposal(s.proposal.payload,t,s.task.digest)&&await verify(s.proposal,t.receiver_key)&&Date.parse(s.proposal.payload.observed_at)>=Date.parse(reviewer!.issued_at)&&Date.parse(s.proposal.payload.observed_at)<Date.parse(t.expires_at),'Repository snapshot is invalid');
  check(Array.isArray(s.approvals)&&s.approvals.length<=2&&new Set(s.approvals.map(a=>a.payload.role)).size===s.approvals.length,'Approval roles are invalid');
  for(const approval of s.approvals){const a=approval.payload,key=a.role==='owner'?t.owner_key:reviewer?.reviewer_key;check(!!s.proposal&&validRepositoryEnvelope(approval)&&validRepositoryRecord(a,'approval')&&a.principal_key===key&&a.task_id===t.id&&a.task_digest===s.task.digest&&a.proposal_digest===s.proposal.digest&&await verify(approval,key)&&Date.parse(a.issued_at)>=Date.parse(s.proposal.payload.observed_at)&&Date.parse(a.expires_at)<=Date.parse(t.expires_at),'Exact proposal approval is invalid');}
  if(s.execution){const x=s.execution.payload,owner=s.approvals.find(a=>a.payload.role==='owner'),review=s.approvals.find(a=>a.payload.role==='reviewer');check(!!s.proposal&&!!owner&&!!review&&validRepositoryEnvelope(s.execution)&&validRepositoryRecord(x,'execution')&&x.task_id===t.id&&x.task_digest===s.task.digest&&x.proposal_digest===s.proposal.digest&&x.receiver_key===t.receiver_key&&x.owner_approval_digest===owner?.digest&&x.reviewer_approval_digest===review?.digest&&owner?.payload.decision==='approve'&&review?.payload.decision==='approve'&&[owner,review].every(a=>a&&Date.parse(a.payload.expires_at)>=Date.parse(x.expires_at)&&Date.parse(a.payload.issued_at)<=Date.parse(x.issued_at))&&Date.parse(x.expires_at)<=Date.parse(t.expires_at)&&await verify(s.execution,pins.authority_key),'Execution authority is invalid');}
  if(s.outcome){const o=s.outcome.payload;check(!!s.execution&&validRepositoryEnvelope(s.outcome)&&validRepositoryRecord(o,'outcome')&&o.task_id===t.id&&o.task_digest===s.task.digest&&o.proposal_digest===s.proposal?.digest&&o.execution_digest===s.execution?.digest&&o.operation_id===s.execution?.payload.operation_id&&await verify(s.outcome,t.receiver_key)&&Date.parse(o.observed_at)>=Date.parse(s.execution.payload.issued_at),'Receiver outcome is invalid');check(o.status!=='confirmed'||o.readback!=='exact_ref'||o.observed_base_sha===s.proposal?.payload.merge_sha,'Confirmed readback is invalid');}
  if(s.acceptance){const a=s.acceptance.payload;check(s.outcome?.payload.status==='confirmed'&&validRepositoryEnvelope(s.acceptance)&&validRepositoryRecord(a,'acceptance')&&a.task_id===t.id&&a.task_digest===s.task.digest&&a.outcome_digest===s.outcome.digest&&a.reviewer_key===reviewer?.reviewer_key&&await verify(s.acceptance,reviewer?.reviewer_key)&&Date.parse(a.issued_at)>=Date.parse(s.outcome.payload.observed_at),'Recipient acceptance is invalid');accepted=a.decision==='accept';}
  const expected=s.acceptance?s.acceptance.payload.decision==='accept'?'accepted':'changes_requested':s.outcome?s.outcome.payload.status:s.execution?'executing':!reviewer?'awaiting_reviewer':!s.proposal?'awaiting_snapshot':s.approvals.some(a=>a.payload.decision==='reject')?'rejected':s.approvals.length===2&&s.approvals.every(a=>Date.parse(a.payload.expires_at)>Date.parse(s.observed_at))?'approved':'review';
  check(s.status===expected||s.status==='cancelled'&&!s.execution&&!s.outcome&&!s.acceptance,'State status is inconsistent with the signed records');
  for(const record of [s.reviewer,s.proposal,...s.approvals,s.execution,s.outcome,s.acceptance])if(record)check(Date.parse((record.payload as {issued_at?:string;observed_at?:string}).issued_at??(record.payload as {observed_at:string}).observed_at)<=Date.parse(s.observed_at),'A signed record is later than the state observation');
 }catch{errors.push('Malformed repository evidence');}
 return {valid:errors.length===0,errors,accepted:accepted&&errors.length===0,authorityPinned:!!pin&&errors.length===0,limitations:['The pinned receiver attests to GitHub API observations; this is not a GitHub-signed receipt.','This controls the installed receiver’s exact branch update. Other credentials and repository actions are outside its coverage.','Destination readback establishes resulting repository state. After a lost reply it does not establish which actor caused that state.','The checked files, commits and named checks do not prove the code is safe or universally correct.','Signatures identify keys, not a person’s legal identity.',...(!pin?['No independent authority key was supplied. Only consistency with the included authority was checked.']:[])]};
}
