import {canonical,sha256,verify,type Signed} from './coordination-protocol.js';
import {validRepositoryEnvelope} from './coordination-repository.js';
import {verifyRepositoryWorkspaceState} from './coordination-repository-workspace.js';
import {verifyRepositoryReviewEvidence,type RepositoryReviewEvidence} from './coordination-repository-review-evidence.js';
import * as C from './coordination-repository-coding.js';
const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const shape=(v:Record<string,unknown>,keys:string[])=>Object.keys(v).length===keys.length&&keys.every(k=>Object.hasOwn(v,k));
const at=(v:unknown)=>typeof v==='string'&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString()===v;
const before=(a:string,b:string)=>Date.parse(a)<=Date.parse(b);
const status=['queued','running','testing','publishing','pr_ready','failed','cancelled','unknown','expired'];
export async function verifyRepositoryCodingEvidence(value:unknown,authorityKey?:string):Promise<{valid:boolean;errors:string[];published:boolean;authorityPinned:boolean;limitations:string[]}> {
 const errors:string[]=[];let published=false;function check(ok:unknown,message:string):asserts ok{if(!ok)throw Error(message);}
 try {
  check(object(value)&&shape(value,['type','job'])&&value.type==='scopeblind.repository.coding-evidence.v1','Unrecognized coding evidence');const e=value as unknown as C.RepositoryCodingEvidence,j=e.job?.payload,m=j?.mandate?.payload,r=j?.request?.payload;
  check(validRepositoryEnvelope(e.job)&&object(j)&&shape(j,['type','request','mandate','adoption','workspace','parent','status','attempts','model_calls','reserved_tokens','lease_id','lease_expires_at','started_at','plan','publication','result','stop','error','observed_at'])&&j.type==='scopeblind.repository.coding-job.v1'&&status.includes(j.status)&&at(j.observed_at),'Invalid coding state');
  const key=authorityKey||j.workspace?.signer;check(await verify(e.job,key),'Coding service signature invalid');check(await verifyRepositoryWorkspaceState(j.workspace,key),'Coding workspace proof invalid');const w=j.workspace.payload.workspace.payload;
  check(validRepositoryEnvelope(j.mandate)&&C.validRepositoryCodingMandate(m)&&await verify(j.mandate,m.owner_key)&&validRepositoryEnvelope(j.adoption)&&j.adoption.digest===j.mandate.digest&&canonical(j.adoption.payload)===canonical(m)&&await verify(j.adoption,m.reviewer_key),'Separate dual-signed code-edit authority required');
  check(m.workspace_id===w.id&&m.workspace_digest===j.workspace.payload.workspace.digest&&m.repository===w.repository&&m.base_branch===w.base_branch&&m.worker_key!==key&&m.worker_key!==w.receiver_key,'Coding project scope mismatch');
  for(const [id,k,revision,role] of [[m.owner_member_id,m.owner_key,m.owner_member_revision,'owner'],[m.reviewer_member_id,m.reviewer_key,m.reviewer_member_revision,'reviewer']] as const){const member=j.workspace.payload.members.find(x=>x.member_id===id);check(member&&member.current_key===k&&member.revision===revision&&member.status==='active'&&member.role===role,'Coding member revision mismatch');}
  check(validRepositoryEnvelope(j.request)&&C.validRepositoryCodingRequest(r)&&await verify(j.request,m.owner_key)&&r.owner_key===m.owner_key&&r.workspace_id===m.workspace_id&&r.mandate_digest===j.mandate.digest&&before(m.issued_at,r.issued_at)&&before(r.issued_at,m.expires_at)&&before(r.issued_at,j.observed_at)&&before(r.issued_at,j.workspace.payload.observed_at)&&before(j.workspace.payload.observed_at,j.observed_at),'Coding request authority mismatch');
  check(!j.parent.origin&&!(j.parent as any).coding_origin&&(await verifyRepositoryReviewEvidence(j.parent,key)).valid,'Invalid frozen coding source');const core=j.parent.repository.type==='scopeblind.repository.evidence.v1'?j.parent.repository.state:j.parent.repository.repository.state,source=r.source,feedback=j.parent.review.payload.feedback.find(f=>f.digest===source.feedback_digest);
  check(core.payload.task.digest===source.task_digest&&core.payload.task.payload.id===source.task_id&&core.payload.task.payload.repository===m.repository&&core.payload.task.payload.base_branch===m.base_branch&&feedback&&feedback.payload.basis_digest===source.basis_digest&&feedback.payload.packet_digest===source.packet_digest&&before(feedback.payload.issued_at,r.issued_at)&&core.payload.proposal,'Coding source feedback mismatch');
  check(Number.isSafeInteger(j.attempts)&&j.attempts>=0&&j.attempts<=m.max_attempts&&Number.isSafeInteger(j.model_calls)&&j.model_calls>=0&&j.model_calls<=m.max_model_calls&&Number.isSafeInteger(j.reserved_tokens)&&j.reserved_tokens>=0&&j.reserved_tokens<=m.max_tokens,'Coding work limits exceeded');
  check((j.started_at===null||at(j.started_at)&&before(r.issued_at,j.started_at)&&before(j.started_at,j.observed_at))&&(j.lease_id===null?j.lease_expires_at===null:typeof j.lease_id==='string'&&at(j.lease_expires_at))&&(j.error===null||typeof j.error==='string'&&/^[a-z0-9_]{3,80}$/.test(j.error)),'Invalid coding lifecycle');
  if(j.stop){check(validRepositoryEnvelope(j.stop)&&C.validRepositoryCodingStop(j.stop.payload)&&[m.owner_key,m.reviewer_key].includes(j.stop.payload.principal_key)&&await verify(j.stop,j.stop.payload.principal_key)&&j.stop.payload.job_id===r.id&&j.stop.payload.mandate_digest===j.mandate.digest&&j.stop.payload.workspace_id===m.workspace_id&&before(j.stop.payload.issued_at,j.observed_at),'Invalid coding cancellation');}
  if(j.plan){const p=j.plan.payload;check(validRepositoryEnvelope(j.plan)&&C.validRepositoryCodingPlan(p,m)&&await verify(j.plan,m.worker_key)&&p.job_id===r.id&&p.request_digest===j.request.digest&&p.mandate_digest===j.mandate.digest&&p.source_head_sha===core.payload.proposal.payload.head_sha&&p.source_base_sha===core.payload.proposal.payload.base_sha&&p.tests.command_digest===await sha256(canonical(m.test_command))&&p.build.command_digest===await sha256(canonical(m.build_command))&&p.model_calls===j.model_calls&&p.reserved_tokens===j.reserved_tokens&&before(p.issued_at,j.observed_at),'Coding plan scope or tests invalid');}
  if(j.publication){const p=j.publication.payload;check(j.plan&&validRepositoryEnvelope(j.publication)&&object(p)&&shape(p,['type','job_id','plan_digest','mandate_digest','request_digest','worker_key','lease_id','issued_at','expires_at'])&&p.type==='scopeblind.repository.coding-publication.v1'&&await verify(j.publication,key)&&p.job_id===r.id&&p.plan_digest===j.plan.digest&&p.mandate_digest===j.mandate.digest&&p.request_digest===j.request.digest&&p.worker_key===m.worker_key&&at(p.issued_at)&&at(p.expires_at)&&before(j.plan.payload.issued_at,p.issued_at)&&Date.parse(p.expires_at)>Date.parse(p.issued_at)&&Date.parse(p.expires_at)-Date.parse(p.issued_at)<=120000&&before(p.expires_at,m.expires_at)&&before(p.issued_at,j.observed_at),'Invalid exact publication gate');}
  if(j.result){const result=j.result.payload;check(j.plan&&j.publication&&validRepositoryEnvelope(j.result)&&C.validRepositoryCodingResult(result)&&result.type==='scopeblind.repository.coding-result.v1'&&await verify(j.result,m.worker_key)&&result.job_id===r.id&&result.plan_digest===j.plan.digest&&result.publication_digest===j.publication.digest&&result.repository===m.repository&&result.branch===j.plan.payload.branch&&result.head_sha===j.plan.payload.commit_sha&&Number.isSafeInteger(result.pull_number)&&result.pull_number>0&&result.pull_url===`https://github.com/${m.repository}/pull/${result.pull_number}`&&result.preview_digest===j.plan.payload.preview_digest&&Number.isSafeInteger(result.deployment_id)&&result.deployment_id>0&&Number.isSafeInteger(result.deployment_status_id)&&result.deployment_status_id>0&&at(result.observed_at)&&before(j.publication.payload.issued_at,result.observed_at)&&before(result.observed_at,j.observed_at),'Invalid coding publication readback');const u=new URL(result.preview_url);check(u.protocol==='https:'&&!u.username&&!u.password&&!u.search&&!u.hash&&u.pathname===`/v1/${r.id}/${result.head_sha}/${result.preview_digest}/index.html`,'Preview must identify the immutable content');published=true;}
  check((j.status==='pr_ready')===!!j.result&&(!j.publication||j.plan)&&(!['publishing','unknown'].includes(j.status)||!!j.publication),'Contradictory coding status');
 }catch(error){errors.push(error instanceof Error?error.message:'Malformed coding evidence');}
 return {valid:errors.length===0,errors,published:errors.length===0&&published,authorityPinned:!!authorityKey,limitations:['Code-edit authority permits only bounded work and a new pull request; no merge or recipient acceptance is inherited.','The service attests live membership, revocation, spending reservations and the publication gate. The worker attests model work, isolated test results and GitHub readbacks.','A content-addressed preview identifies the published bundle; verification does not execute it or prove that the code satisfies the brief.']};
}
