import {describe,it,expect} from 'vitest';
import {canonical,sha256,generateIdentity,sign,type Signed} from './coordination-protocol.js';
import {validRepositoryReviewContent,validRepositoryReviewDecision,validRepositoryReviewPacket,type RepositoryReviewBrief,type RepositoryReviewPacket,type RepositoryReviewState,type RepositoryReviewDecision,type RepositoryReviewFeedback} from './coordination-repository-review.js';
import {verifyRepositoryReviewEvidence,type RepositoryReviewEvidence} from './coordination-repository-review-evidence.js';
import type {RepositoryTask,RepositoryClaim,RepositoryProposal,RepositoryState,RepositoryApproval,RepositoryExecution} from './coordination-repository.js';
const time=(s:number)=>new Date(1800000000000+s*1000).toISOString();
export async function reviewFixture(){
 const [owner,reviewer,receiver,service,agent]=await Promise.all(Array.from({length:5},()=>generateIdentity()));
 const task=await sign<RepositoryTask>({type:'scopeblind.repository.task.v1',id:'review-task-test',title:'Review existing website PR',repository:'Owner/Repo',pull_number:7,base_branch:'main',owner_key:owner.publicKey,receiver_key:receiver.publicKey,authority_key:service.publicKey,allowed_paths:['site/**'],required_checks:[{name:'Tests',app_id:99}],reviewer_secret_hash:'f'.repeat(64),issued_at:time(0),expires_at:time(7200)},owner);
 const claim=await sign<RepositoryClaim>({type:'scopeblind.repository.claim.v1',task_id:task.payload.id,task_digest:task.digest,reviewer_key:reviewer.publicKey,name:'Client',issued_at:time(2)},reviewer);
 const proposal=await sign<RepositoryProposal>({type:'scopeblind.repository.proposal.v1',id:'proposal-test',task_id:task.payload.id,task_digest:task.digest,repository_id:'R_test',base_ref:'refs/heads/main',head_ref:'refs/heads/feature',base_sha:'1'.repeat(40),head_sha:'2'.repeat(40),merge_sha:'3'.repeat(40),tree_sha:'4'.repeat(40),files:[{path:'site/index.html',status:'modified',mode:'100644',additions:1,deletions:1}],checks:[{id:41,name:'Tests',app_id:99,head_sha:'2'.repeat(40),conclusion:'success'}],observed_at:time(3)},receiver);
 const brief=await sign<RepositoryReviewBrief>({type:'scopeblind.repository.review-brief.v1',task_id:task.payload.id,task_digest:task.digest,owner_key:owner.publicKey,brief:'A working contact form.\nKeep the existing brand.',success_criteria:[{id:'contact-works',text:'Submitting sends a confirmation.'}],preview_policy:{environment:'Preview',check:{name:'Deploy',app_id:77},allowed_origins:['https://preview.example.com'],required:true},issued_at:time(1),expires_at:time(7200)},owner);
 const packet=await sign<RepositoryReviewPacket>({type:'scopeblind.repository.review-packet.v1',task_id:task.payload.id,task_digest:task.digest,brief_digest:brief.digest,proposal_digest:proposal.digest,base_sha:proposal.payload.base_sha,head_sha:proposal.payload.head_sha,merge_sha:proposal.payload.merge_sha,preview:{status:'available',deployment:{deployment_id:15,status_id:16,sha:proposal.payload.head_sha,environment:'Preview',state:'success',environment_url:'https://preview.example.com/pr/7',deployment_creator_id:111,status_creator_id:222,created_at:time(2),updated_at:time(4),check:{id:17,name:'Deploy',app_id:77,head_sha:proposal.payload.head_sha,conclusion:'success'}}},observed_at:time(5),expires_at:time(905)},receiver);
 const state=await sign<RepositoryState>({type:'scopeblind.repository.state.v1',task,reviewer:claim,proposal,approvals:[],execution:null,outcome:null,acceptance:null,status:'review',revision:3,observed_at:time(10)},service);
 const review=await sign<RepositoryReviewState>({type:'scopeblind.repository.review-state.v1',task_id:task.payload.id,task_digest:task.digest,brief,packet,decisions:[],feedback:[],recommendations:[],history:[],agent_uses:[],observed_at:time(11)},service);
 const evidence:RepositoryReviewEvidence={type:'scopeblind.repository.review-evidence.v1',repository:{type:'scopeblind.repository.evidence.v1',state},review};return {owner,reviewer,receiver,service,agent,task,claim,proposal,brief,packet,state,review,evidence};
}
describe('exact review brief and packet evidence',()=>{
 it('preserves multiline requirements and rejects duplicate or unrecognized material fields',()=>{const content={brief:'Line one\nLine two',success_criteria:[{id:'criterion-one',text:'It works'}]};expect(validRepositoryReviewContent(content)).toBe(true);for(const c of [{...content,success_criteria:[]},{...content,success_criteria:[...content.success_criteria,...content.success_criteria]},{...content,automatic_approval:true},{...content,brief:'bad\u0000text'}])expect(validRepositoryReviewContent(c)).toBe(false);});
 it('verifies an exact preview observation without claiming pinned URL bytes or acceptance',async()=>{const f=await reviewFixture(),r=await verifyRepositoryReviewEvidence(f.evidence,f.service.publicKey);expect(r.valid,r.errors.join(';')).toBe(true);expect(r.packetVerified).toBe(true);expect(r.previewAvailable).toBe(true);expect(r.accepted).toBe(false);expect(r.decisionsVerified).toBe(false);expect(r.limitations.join(' ')).toContain('mutable');expect((await verifyRepositoryReviewEvidence(f.evidence,f.owner.publicKey)).valid).toBe(false);});
 it('rejects re-signed mismatched criteria, proposal, head, lifetime, provider and URL',async()=>{const f=await reviewFixture(),preview=f.packet.payload.preview;if(preview.status!=='available')throw Error();for(const patch of [{brief_digest:'a'.repeat(64)},{proposal_digest:'b'.repeat(64)},{head_sha:'5'.repeat(40)},{expires_at:time(906)},{preview:{status:'available',deployment:{...preview.deployment,check:{...preview.deployment.check,app_id:78}}}},{preview:{status:'available',deployment:{...preview.deployment,environment_url:'https://elsewhere.example.com/'}}}]){const packet=await sign({...f.packet.payload,...patch},f.receiver),e={...f.evidence,review:await sign({...f.review.payload,packet},f.service)};expect((await verifyRepositoryReviewEvidence(e,f.service.publicKey)).valid).toBe(false);}});
 it('requires both exact packet decisions in addition to existing v1 merge approvals',async()=>{const f=await reviewFixture();const approvals=await Promise.all([f.owner,f.reviewer].map((key,i)=>sign<RepositoryApproval>({type:'scopeblind.repository.approval.v1',task_id:f.task.payload.id,task_digest:f.task.digest,proposal_digest:f.proposal.digest,role:i?'reviewer':'owner',principal_key:key.publicKey,decision:'approve',issued_at:time(6),expires_at:time(306),note:''},key)));
 const decisions=await Promise.all(approvals.map((a,i)=>sign<RepositoryReviewDecision>({type:'scopeblind.repository.review-decision.v1',task_id:f.task.payload.id,task_digest:f.task.digest,brief_digest:f.brief.digest,packet_digest:f.packet.digest,proposal_digest:f.proposal.digest,approval_digest:a.digest,principal_key:a.payload.principal_key,role:a.payload.role,issued_at:a.payload.issued_at,expires_at:a.payload.expires_at},i?f.reviewer:f.owner)));
 const execution=await sign<RepositoryExecution>({type:'scopeblind.repository.execution.v1',operation_id:'operation-test',receiver_attempt_id:'attempt-test',task_id:f.task.payload.id,task_digest:f.task.digest,proposal_digest:f.proposal.digest,owner_approval_digest:approvals[0].digest,reviewer_approval_digest:approvals[1].digest,receiver_key:f.receiver.publicKey,action:'github.updateRefs',issued_at:time(7),expires_at:time(127)},f.service);
 const state=await sign({...f.state.payload,approvals,execution,status:'executing' as const},f.service),review=await sign({...f.review.payload,decisions},f.service),e={...f.evidence,repository:{type:'scopeblind.repository.evidence.v1' as const,state},review};expect((await verifyRepositoryReviewEvidence(e,f.service.publicKey)).valid).toBe(true);
 for(const changed of [[],decisions.slice(0,1),[decisions[0],await sign({...decisions[1].payload,packet_digest:'f'.repeat(64)},f.reviewer)]])expect((await verifyRepositoryReviewEvidence({...e,review:await sign({...review.payload,decisions:changed},f.service)},f.service.publicKey)).valid).toBe(false);
 });
 it('does not approve a missing required preview',async()=>{const f=await reviewFixture(),packet=await sign({...f.packet.payload,preview:{status:'missing' as const,reason:'No deployment'}},f.receiver);expect(validRepositoryReviewPacket(packet.payload,f.brief,f.proposal)).toBe(true);const approval=await sign<RepositoryApproval>({type:'scopeblind.repository.approval.v1',task_id:f.task.payload.id,task_digest:f.task.digest,proposal_digest:f.proposal.digest,role:'owner',principal_key:f.owner.publicKey,decision:'approve',issued_at:time(6),expires_at:time(306),note:''},f.owner),decision={type:'scopeblind.repository.review-decision.v1' as const,task_id:f.task.payload.id,task_digest:f.task.digest,brief_digest:f.brief.digest,packet_digest:packet.digest,proposal_digest:f.proposal.digest,approval_digest:approval.digest,principal_key:f.owner.publicKey,role:'owner' as const,issued_at:time(6),expires_at:time(306)};expect(validRepositoryReviewDecision(decision,f.brief,packet,approval)).toBe(false);});
 it('requires actual human or dual-granted author authority on feedback, not just a signature',async()=>{const f=await reviewFixture();for(const key of [f.reviewer,f.agent]){const feedback=await sign<RepositoryReviewFeedback>({type:'scopeblind.repository.review-feedback.v1',id:'feedback-test',task_id:f.task.payload.id,task_digest:f.task.digest,basis_digest:f.proposal.digest,packet_digest:f.packet.digest,requester_key:key.publicKey,criterion_ids:['contact-works'],message:'The submit button is unresponsive.',requested_changes:'Connect the button to the form.',issued_at:time(7)},key),e={...f.evidence,review:await sign({...f.review.payload,feedback:[feedback]},f.service)};expect((await verifyRepositoryReviewEvidence(e,f.service.publicKey)).valid).toBe(key===f.reviewer);}});
 it('rejects unused history and unknown signed envelope fields',async()=>{const f=await reviewFixture();for(const e of [{...f.evidence,accepted:true},{...f.evidence,review:{...f.review,authorization_signature:'fake'}},{...f.evidence,review:await sign({...f.review.payload,history:[{state:f.state,packet:f.packet}]},f.service)}])expect((await verifyRepositoryReviewEvidence(e,f.service.publicKey)).valid).toBe(false);});
});

describe('historical dual-signed agent review authority',()=>{
 it('requires both principals, exact task assignment, scoped permission and atomic recording attestation',async()=>{
  const f=await reviewFixture(),{validWorkspacePreparationMandate}=await import('./coordination-repository-workspace.js');
  const mandate=await sign<import('./coordination-repository-workspace.js').WorkspacePreparationMandate>({type:'scopeblind.repository.preparation-mandate.v1',id:'mandate-test',workspace_id:'workspace-test',workspace_digest:'a'.repeat(64),mode:'prepare_review',owner_member_id:'owner-member',owner_key:f.owner.publicKey,owner_member_revision:1,reviewer_member_id:'reviewer-member',reviewer_key:f.reviewer.publicKey,reviewer_member_revision:1,agent_key:f.agent.publicKey,repository:f.task.payload.repository,base_branch:f.task.payload.base_branch,allowed_paths:['site/**'],required_checks:f.task.payload.required_checks,permissions:['prepare_review','read_task','report_criteria','request_revision'],max_requests:10,max_open_requests:2,issued_at:time(0),expires_at:time(1000)},f.owner),adoption=await sign(mandate.payload,f.reviewer);
  expect(validWorkspacePreparationMandate(mandate.payload)).toBe(true);
  const assignment=await sign<import('./coordination-repository-workspace.js').WorkspaceTaskAssignment>({type:'scopeblind.repository.workspace-task-assignment.v1',workspace_id:'workspace-test',workspace_digest:'a'.repeat(64),task_id:f.task.payload.id,task_digest:f.task.digest,owner_member_id:'owner-member',owner_key:f.owner.publicKey,owner_member_revision:1,reviewer_member_id:'reviewer-member',reviewer_key:f.reviewer.publicKey,reviewer_member_revision:1,review_brief_digest:f.brief.digest,issued_at:time(2),expires_at:time(1000)},f.owner);
  const feedback=await sign<RepositoryReviewFeedback>({type:'scopeblind.repository.review-feedback.v1',id:'agent-feedback-test',task_id:f.task.payload.id,task_digest:f.task.digest,basis_digest:f.proposal.digest,packet_digest:f.packet.digest,requester_key:f.agent.publicKey,mandate_digest:mandate.digest,criterion_ids:['contact-works'],message:'Test invalid email input.',requested_changes:'Add clear validation.',issued_at:time(7)},f.agent);
  const use=await sign<import('./coordination-repository-review.js').RepositoryReviewAgentUse>({type:'scopeblind.repository.review-agent-use.v1',task_id:f.task.payload.id,task_digest:f.task.digest,record_digest:feedback.digest,permission:'request_revision',mandate,adoption,assignment,checked_at:time(8)},f.service);
  const build=async(uses=[use],record=feedback)=>({...f.evidence,review:await sign({...f.review.payload,feedback:[record],agent_uses:uses},f.service)});
  const result=await verifyRepositoryReviewEvidence(await build(),f.service.publicKey);expect(result.valid,result.errors.join(';')).toBe(true);expect(result.accepted).toBe(false);
  for(const changes of [{adoption:mandate},{permission:'report_criteria'},{record_digest:'f'.repeat(64)},{checked_at:time(1001)},{assignment:await sign({...assignment.payload,review_brief_digest:'f'.repeat(64)},f.owner)}]){const changed=await sign({...use.payload,...changes},f.service);expect((await verifyRepositoryReviewEvidence(await build([changed as typeof use]),f.service.publicKey)).valid).toBe(false);}
  expect((await verifyRepositoryReviewEvidence(await build([]),f.service.publicKey)).valid).toBe(false);
  const later=await sign({...f.review.payload,feedback:[feedback],agent_uses:[use],observed_at:time(2000)},f.service);expect((await verifyRepositoryReviewEvidence({...f.evidence,review:later},f.service.publicKey)).valid).toBe(true,'Historical use stays verifiable after the mandate expires.');
 });
});
it('independently verifies optional discovery pins, PR scope and expiry before filling a policy draft',async()=>{
 const f=await reviewFixture(),{verifyRepositoryPreviewDiscovery}=await import('./coordination-repository-review.js'),payload={type:'scopeblind.repository.preview-discovery.v1' as const,repository:f.task.payload.repository,pull_number:7,head_sha:f.proposal.payload.head_sha,owner_key:f.owner.publicKey,receiver_key:f.receiver.publicKey,authority_key:f.service.publicKey,candidates:[{environment:'Preview',origin:'https://preview.example.com',environment_url:'https://preview.example.com/pr/7',deployment_id:15,status_id:16}],checks:[{name:'Deploy',app_id:77,id:17}],status:'observed' as const,observed_at:time(5),expires_at:time(1000)},discovery=await sign(payload,f.receiver),pins={repository:f.task.payload.repository,pull_number:7,owner_key:f.owner.publicKey,receiver_key:f.receiver.publicKey,authority_key:f.service.publicKey};
 expect(await verifyRepositoryPreviewDiscovery(discovery,pins,Date.parse(time(10)))).toBe(true);expect(await verifyRepositoryPreviewDiscovery(discovery,{...pins,pull_number:8},Date.parse(time(10)))).toBe(false);expect(await verifyRepositoryPreviewDiscovery(discovery,pins,Date.parse(time(1001)))).toBe(false);expect(await verifyRepositoryPreviewDiscovery(await sign(payload,f.agent),pins,Date.parse(time(10)))).toBe(false);
});
it('links an agent-prepared child to one exact source feedback without inheriting acceptance or later parent state',async()=>{
 const f=await reviewFixture(),W=await import('./coordination-repository-workspace.js');
 const mandate=await sign<import('./coordination-repository-workspace.js').WorkspacePreparationMandate>({type:'scopeblind.repository.preparation-mandate.v1',id:'mandate-origin',workspace_id:'workspace-origin',workspace_digest:'a'.repeat(64),mode:'prepare_review',owner_member_id:'owner-member',owner_key:f.owner.publicKey,owner_member_revision:1,reviewer_member_id:'reviewer-member',reviewer_key:f.reviewer.publicKey,reviewer_member_revision:1,agent_key:f.agent.publicKey,repository:f.task.payload.repository,base_branch:'main',allowed_paths:['site/**'],required_checks:f.task.payload.required_checks,permissions:['prepare_review','read_task','request_revision'],max_requests:10,max_open_requests:2,issued_at:time(0),expires_at:time(1000)},f.owner),adoption=await sign(mandate.payload,f.reviewer);
 const feedback=await sign<RepositoryReviewFeedback>({type:'scopeblind.repository.review-feedback.v1',id:'source-feedback',task_id:f.task.payload.id,task_digest:f.task.digest,basis_digest:f.proposal.digest,packet_digest:f.packet.digest,requester_key:f.reviewer.publicKey,criterion_ids:['contact-works'],message:'Add clear validation.',requested_changes:'Show an email error.',issued_at:time(7)},f.reviewer),parent={...f.evidence,review:await sign({...f.review.payload,feedback:[feedback]},f.service)};
 const draft=await sign<import('./coordination-repository-workspace.js').WorkspaceReviewDraft>({type:'scopeblind.repository.workspace-review-draft.v1',id:'child-draft-test',workspace_id:'workspace-origin',mandate_digest:mandate.digest,agent_key:f.agent.publicKey,repository:f.task.payload.repository,pull_number:8,title:'Add form validation',content:{brief:'Fix validation.',success_criteria:[{id:'error-shown',text:'Invalid email shows an error.'}]},allowed_paths:['site/**'],required_checks:f.task.payload.required_checks,source:{task_id:f.task.payload.id,task_digest:f.task.digest,basis_digest:f.proposal.digest,packet_digest:f.packet.digest,feedback_digest:feedback.digest},issued_at:time(12)},f.agent);expect(W.validWorkspaceReviewDraft(draft.payload)).toBe(true);
 const child=await sign({...f.task.payload,id:'child-review-task',pull_number:8,title:draft.payload.title,issued_at:time(13)},f.owner),brief=await sign({...f.brief.payload,...draft.payload.content,task_id:child.payload.id,task_digest:child.digest,issued_at:time(13)},f.owner),state=await sign<RepositoryState>({...f.state.payload,task:child,reviewer:null,proposal:null,status:'awaiting_reviewer',revision:1,observed_at:time(15)},f.service),review=await sign({...f.review.payload,task_id:child.payload.id,task_digest:child.digest,brief,packet:null,observed_at:time(16)},f.service);
 const parentAssignment=await sign<import('./coordination-repository-workspace.js').WorkspaceTaskAssignment>({type:'scopeblind.repository.workspace-task-assignment.v1',workspace_id:'workspace-origin',workspace_digest:'a'.repeat(64),task_id:f.task.payload.id,task_digest:f.task.digest,owner_member_id:'owner-member',owner_key:f.owner.publicKey,owner_member_revision:1,reviewer_member_id:'reviewer-member',reviewer_key:f.reviewer.publicKey,reviewer_member_revision:1,review_brief_digest:f.brief.digest,issued_at:time(2),expires_at:time(1000)},f.owner),assignment=await sign({...parentAssignment.payload,task_id:child.payload.id,task_digest:child.digest,review_brief_digest:brief.digest,source_draft_digest:draft.digest,issued_at:time(14)},f.owner);
 const origin={draft,assignment,parent_assignment:parentAssignment,parent,preparation:{mandate,adoption}},evidence:RepositoryReviewEvidence={type:'scopeblind.repository.review-evidence.v1',repository:{type:'scopeblind.repository.evidence.v1',state},review:await sign({...review.payload,origin_digest:await sha256(canonical(origin))},f.service),origin};const checked=await verifyRepositoryReviewEvidence(evidence,f.service.publicKey);expect(checked.valid,checked.errors.join(';')).toBe(true);expect(checked.originVerified).toBe(true);expect(checked.accepted).toBe(false);
 const withOrigin=async(origin:NonNullable<RepositoryReviewEvidence['origin']>)=>({...evidence,origin,review:await sign({...review.payload,origin_digest:await sha256(canonical(origin))},f.service)});
 const stripped={...evidence};delete stripped.origin;expect((await verifyRepositoryReviewEvidence(stripped,f.service.publicKey)).valid).toBe(false);expect((await verifyRepositoryReviewEvidence({...evidence,review},f.service.publicKey)).valid).toBe(false);
 const wrong=await sign({...draft.payload,source:{...draft.payload.source!,feedback_digest:'b'.repeat(64)}},f.agent),changed={...evidence,origin:{...evidence.origin!,draft:wrong,assignment:await sign({...assignment.payload,source_draft_digest:wrong.digest},f.owner)}};expect((await verifyRepositoryReviewEvidence(await withOrigin(changed.origin),f.service.publicKey)).valid).toBe(false);
 const later={...parent,repository:{type:'scopeblind.repository.evidence.v1' as const,state:await sign({...f.state.payload,observed_at:time(20)},f.service)},review:await sign({...parent.review.payload,observed_at:time(21)},f.service)};expect((await verifyRepositoryReviewEvidence(await withOrigin({...evidence.origin!,parent:later}),f.service.publicKey)).valid).toBe(false);
 const nested={...parent,origin:evidence.origin};expect((await verifyRepositoryReviewEvidence(await withOrigin({...evidence.origin!,parent:nested}),f.service.publicKey)).valid).toBe(false);
 const unbound={...evidence.origin!} as any;delete unbound.parent_assignment;expect((await verifyRepositoryReviewEvidence(await withOrigin(unbound),f.service.publicKey)).valid).toBe(false);
});
it('rejects stripped packet decisions even for a pending single approval or explicit rejection',async()=>{
 for(const decision of ['approve','reject'] as const){const f=await reviewFixture(),approval=await sign<RepositoryApproval>({type:'scopeblind.repository.approval.v1',task_id:f.task.payload.id,task_digest:f.task.digest,proposal_digest:f.proposal.digest,role:'owner',principal_key:f.owner.publicKey,decision,issued_at:time(6),expires_at:time(306),note:'An exact human decision.'},f.owner),sidecar=await sign<RepositoryReviewDecision>({type:'scopeblind.repository.review-decision.v1',task_id:f.task.payload.id,task_digest:f.task.digest,brief_digest:f.brief.digest,packet_digest:f.packet.digest,proposal_digest:f.proposal.digest,approval_digest:approval.digest,role:'owner',principal_key:f.owner.publicKey,issued_at:approval.payload.issued_at,expires_at:approval.payload.expires_at},f.owner),state=await sign({...f.state.payload,approvals:[approval],status:decision==='reject'?'rejected' as const:'review' as const},f.service),repository={type:'scopeblind.repository.evidence.v1' as const,state},review=await sign({...f.review.payload,decisions:[sidecar]},f.service);
  const valid=await verifyRepositoryReviewEvidence({...f.evidence,repository,review},f.service.publicKey);expect(valid.valid,valid.errors.join(';')).toBe(true);expect(valid.decisionsVerified).toBe(false);
  const stripped=await verifyRepositoryReviewEvidence({...f.evidence,repository,review:await sign({...review.payload,decisions:[]},f.service)},f.service.publicKey);expect(stripped.valid).toBe(false);expect(stripped.errors.join(';')).toContain('Each ordinary approval');expect(stripped.accepted).toBe(false);
 }
});
