/** Trusted Actions controller. Repository programs execute only in a networkless, credential-free container. */
import {mkdtemp,readFile,writeFile,mkdir,opendir,lstat,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join,dirname,relative} from 'node:path';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {createHash,randomUUID} from 'node:crypto';
import {canonical,sha256,sign,verify,makeRequest,importIdentity,type SigningIdentity,type Signed,type RpcAction} from './coordination-protocol.js';
import {pathAllowed,REPOSITORY_SHA,REPOSITORY_ID} from './coordination-repository.js';
import * as C from './coordination-repository-coding.js';
import {verifyRepositoryCodingEvidence} from './coordination-repository-coding-evidence.js';
const execute=promisify(execFile),hash=(v:Buffer|string)=>createHash('sha1').update(v).digest('hex');
export const gitBlob=(b:Buffer)=>hash(Buffer.concat([Buffer.from(`blob ${b.length}\0`),b]));
export interface RepositoryCodingConfig {type:'scopeblind.repository.coding-config.v1';endpoint:string;authority_key:string;worker_key:string;repository:string;base_branch:string;runtime:'node22-static-v1';test_command:string[];build_command:string[];preview_directory:string;docker_image:string}
export interface CodingSandbox {run(command:string[],timeout:number):Promise<{exit_code:number;output:string;duration_ms:number}>;close():Promise<void>}
type DockerExecute=(file:string,args:string[],options:{timeout:number;maxBuffer:number;env:{PATH:string|undefined}})=>Promise<{stdout:string;stderr:string}>;
export class DockerCodingSandbox implements CodingSandbox {
 private containers=new Set<string>();private closed=false;
 constructor(readonly directory:string,readonly image:string,private dockerExecute:DockerExecute=execute){if(!/^node@sha256:[a-f0-9]{64}$/.test(image))throw Error('coding_image_pin_required');}
 async run(command:string[],timeout:number){
  if(this.closed)throw Error('coding_sandbox_closed');if(!C.codingCommand(command))throw Error('coding_command_invalid');
  const name='scopeblind-coding-'+randomUUID(),started=Date.now(),args=['run','--name',name,'--rm','--network','none','--read-only','--cap-drop','ALL','--security-opt','no-new-privileges','--pids-limit','128','--memory','512m','--cpus','1','--tmpfs','/tmp:rw,noexec,nosuid,size=64m','--user',`${process.getuid?.()??1000}:${process.getgid?.()??1000}`,'--mount',`type=bind,source=${this.directory},target=/workspace`,'--workdir','/workspace',this.image,...command];this.containers.add(name);
  try{const r=await this.dockerExecute('docker',args,{timeout,maxBuffer:65536,env:{PATH:process.env.PATH}});return {exit_code:0,output:r.stdout+'\n'+r.stderr,duration_ms:Date.now()-started};}
  catch(e){const error=e as {code?:number;stdout?:string;stderr?:string};return {exit_code:Number.isSafeInteger(error.code)?Number(error.code):124,output:(error.stdout||'')+'\n'+(error.stderr||''),duration_ms:Date.now()-started};}
  finally{await this.remove(name);}
 }
 private async remove(name:string){await this.dockerExecute('docker',['rm','--force',name],{timeout:10000,maxBuffer:4096,env:{PATH:process.env.PATH}}).catch(()=>{});this.containers.delete(name);}
 async close(){this.closed=true;await Promise.all([...this.containers].map(name=>this.remove(name)));}
}
async function bounded(response:Response,max=4_000_000):Promise<any>{const reader=response.body?.getReader();if(!reader)throw Error('coding_empty_response');let n=0,parts:Uint8Array[]=[];try{for(;;){const p=await reader.read();if(p.done)break;n+=p.value.length;if(n>max)throw Error('coding_response_limit');parts.push(p.value);}}finally{await reader.cancel().catch(()=>{});}return JSON.parse(Buffer.concat(parts).toString('utf8'));}
function need(ok:unknown,code:string):asserts ok{if(!ok)throw Error(code);}
async function safeWrite(root:string,path:string,content:string|null){need(C.codingSafePath(path),'coding_path_forbidden');const parts=path.split('/');let current=root;for(const p of parts.slice(0,-1)){current=join(current,p);try{const s=await lstat(current);need(s.isDirectory()&&!s.isSymbolicLink(),'coding_symlink_forbidden');}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;await mkdir(current);}}const file=join(root,path);try{const s=await lstat(file);need(s.isFile()&&!s.isSymbolicLink(),'coding_symlink_forbidden');}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;}if(content===null)await rm(file,{force:true});else await writeFile(file,content,{mode:0o600});}
export async function scanCodingWorkspace(root:string):Promise<Map<string,Buffer>>{
 const found=new Map<string,Buffer>();let nodes=0,bytes=0;
 const visit=async(dir:string,depth:number):Promise<void>=>{need(depth<=10,'coding_directory_depth_limit');for await(const entry of await opendir(dir)){need(++nodes<=1200,'coding_node_limit');const path=join(dir,entry.name),s=await lstat(path),rel=relative(root,path);need(rel.length<=200&&!s.isSymbolicLink(),'coding_symlink_forbidden');if(s.isDirectory())await visit(path,depth+1);else{need(s.isFile()&&s.size<=524288,'coding_file_limit');need(bytes+s.size<=2*1024*1024,'coding_workspace_byte_limit');const content=await readFile(path);bytes+=content.length;need(bytes<=2*1024*1024&&content.length===s.size,'coding_workspace_byte_limit');found.set(rel,content);need(found.size<=1000,'coding_file_count_limit');}}};
 await visit(root,0);return found;
}
export function assertCodingWorkspaceUnchanged(before:Map<string,Buffer>,after:Map<string,Buffer>,previewDirectory?:string){for(const path of new Set([...before.keys(),...after.keys()])){if(previewDirectory&&(path===previewDirectory||path.startsWith(previewDirectory+'/')))continue;const a=before.get(path),b=after.get(path);need(a&&b&&Buffer.compare(a,b)===0,'coding_test_or_build_modified_source');}}
export function codingChanges(before:Map<string,Buffer>,after:Map<string,Buffer>,m:C.RepositoryCodingMandate){const changes:Array<{path:string;before_sha:string|null;after_sha:string|null;bytes:number}>=[];for(const p of new Set([...before.keys(),...after.keys()])){if(p===m.preview_directory||p.startsWith(m.preview_directory+'/'))continue;const a=before.get(p),b=after.get(p);if(a&&b&&Buffer.compare(a,b)===0)continue;need(C.codingSafePath(p)&&pathAllowed(p,m.allowed_paths),'coding_diff_outside_scope');changes.push({path:p,before_sha:a?gitBlob(a):null,after_sha:b?gitBlob(b):null,bytes:Math.max(a?.length??0,b?.length??0)});}need(changes.length>0&&changes.length<=m.max_changed_files&&changes.reduce((n,f)=>n+f.bytes,0)<=m.max_changed_bytes,'coding_diff_limit');return changes.sort((a,b)=>a.path.localeCompare(b.path));}
/** Compute an exact Git tree from trusted original metadata plus independently hashed edits. */
export function codingTree(entries:Array<{path:string;mode:string;sha:string}>,changes:Array<{path:string;after_sha:string|null}>){const files=new Map(entries.map(x=>[x.path,x]));for(const c of changes)if(c.after_sha)files.set(c.path,{path:c.path,mode:files.get(c.path)?.mode||'100644',sha:c.after_sha});else files.delete(c.path);const objects:Array<{path:string;sha:string;entries:Array<{path:string;mode:string;type:'tree'|'blob';sha:string}>}>=[];
 const tree=(prefix:string):string=>{const rows:Array<{path:string;mode:string;type:'tree'|'blob';sha:string}>=[],dirs=new Set<string>();for(const f of files.values()){if(!f.path.startsWith(prefix))continue;const rest=f.path.slice(prefix.length),slash=rest.indexOf('/');if(slash>=0)dirs.add(rest.slice(0,slash));else rows.push({path:rest,mode:f.mode,type:'blob',sha:f.sha});}for(const d of dirs)rows.push({path:d,mode:'040000',type:'tree',sha:tree(prefix+d+'/')});rows.sort((a,b)=>Buffer.compare(Buffer.from(a.path+(a.type==='tree'?'/':'')),Buffer.from(b.path+(b.type==='tree'?'/':''))));const data=Buffer.concat(rows.map(r=>Buffer.concat([Buffer.from(`${r.type==='tree'?'40000':r.mode} ${r.path}\0`),Buffer.from(r.sha,'hex')]))),sha=hash(Buffer.concat([Buffer.from(`tree ${data.length}\0`),data]));objects.push({path:prefix,sha,entries:rows});return sha;};return {sha:tree(''),objects};}
export class RepositoryCodingRunner {
 private publicationUntil=0;private stopped=false;
 constructor(readonly config:RepositoryCodingConfig,private identity:SigningIdentity,private githubToken:string,private fetcher:typeof fetch=fetch,private sandboxFactory:(dir:string)=>CodingSandbox=(dir:string)=>new DockerCodingSandbox(dir,config.docker_image)) {const u=new URL(config.endpoint);need(u.protocol==='https:'&&u.pathname==='/api/coordination'&&!u.search&&!u.hash&&!u.username&&!u.password&&config.worker_key===identity.publicKey&&githubToken,'coding_config_invalid');}
 private async rpc(action:C.RepositoryCodingAction,id:string,body:Record<string,unknown>={}){const request=await sign(makeRequest(action as RpcAction,id,body),this.identity),r=await this.fetcher(this.config.endpoint,{method:'POST',headers:{'content-type':'application/json','x-scopeblind-action':action},body:JSON.stringify({request}),redirect:'error',signal:AbortSignal.timeout(55000)}),v=await bounded(r);need(r.ok&&v.ok===true,typeof v.error==='string'?v.error:'coding_service_refused');return v;}
 private async github(path:string,init:RequestInit={},missing=false){if(init.method&&init.method!=='GET')need(!this.stopped&&this.publicationUntil>Date.now(),'coding_publication_expired');const r=await this.fetcher('https://api.github.com/repos/'+this.config.repository+path,{...init,headers:{authorization:'Bearer '+this.githubToken,accept:'application/vnd.github+json','content-type':'application/json','x-github-api-version':'2026-03-10'},redirect:'error',signal:AbortSignal.timeout(20000)});if(missing&&r.status===404){await r.body?.cancel();return null;}const v=await bounded(r);need(r.ok,'coding_github_'+r.status);return v;}
 private async checked(reply:any){const job=reply.job as Signed<C.RepositoryCodingJob>;need(job&&(await verifyRepositoryCodingEvidence({type:'scopeblind.repository.coding-evidence.v1',job},this.config.authority_key)).valid,'coding_job_evidence_invalid');const m=job.payload.mandate.payload;need(m.worker_key===this.identity.publicKey&&m.repository===this.config.repository&&m.base_branch===this.config.base_branch&&m.docker_image===this.config.docker_image&&m.runtime===this.config.runtime&&canonical(m.test_command)===canonical(this.config.test_command)&&canonical(m.build_command)===canonical(this.config.build_command)&&m.preview_directory===this.config.preview_directory,'coding_config_scope_mismatch');return job;}
 private async readback(j:C.RepositoryCodingJob){const p=j.plan!,result=await this.github('/pulls?state=all&head='+encodeURIComponent(this.config.repository.split('/')[0]+':'+p.payload.branch)+'&base='+encodeURIComponent(this.config.base_branch)+'&per_page=100');need(Array.isArray(result)&&result.length<=1,'coding_pull_ambiguous');if(!result.length)return null;const pull=result[0];need(pull.head?.sha===p.payload.commit_sha&&pull.head?.ref===p.payload.branch&&pull.base?.ref===this.config.base_branch&&pull.base?.repo?.full_name===this.config.repository&&pull.head?.repo?.full_name===this.config.repository,'coding_pull_conflict');return pull;}
 private async result(j:C.RepositoryCodingJob,pull:any,preview:{url:string;digest:string},deployment:any,status:any,check:any){need(check.name==='ScopeBlind isolated coding checks'&&check.app?.id===15368&&check.head_sha===j.plan!.payload.commit_sha&&check.conclusion==='success','coding_check_invalid');const result=await sign<C.RepositoryCodingResult>({type:'scopeblind.repository.coding-result.v1',job_id:j.request.payload.id,plan_digest:j.plan!.digest,publication_digest:j.publication!.digest,repository:this.config.repository,branch:j.plan!.payload.branch,head_sha:j.plan!.payload.commit_sha,pull_number:pull.number,pull_url:`https://github.com/${this.config.repository}/pull/${pull.number}`,preview_url:preview.url,preview_digest:preview.digest,deployment_id:deployment.id,deployment_status_id:status.id,deployment_environment:'ScopeBlind coding preview',check:{id:check.id,name:'ScopeBlind isolated coding checks',app_id:15368,head_sha:j.plan!.payload.commit_sha,conclusion:'success'},observed_at:new Date().toISOString()},this.identity);await this.rpc('repository_coding_complete',j.request.payload.workspace_id,{job_id:j.request.payload.id,lease_id:j.lease_id,result});}
 async runOne(jobIdFilter?:string){need(jobIdFilter===undefined||REPOSITORY_ID.test(jobIdFilter),'invalid_coding_job');const lease=crypto.randomUUID(),reply=await this.rpc('repository_coding_poll','repository-coding',{lease_id:lease,...(jobIdFilter?{job_id:jobIdFilter}:{})});if(reply.job===null)return false;let signed=await this.checked(reply),j=signed.payload;need(j.lease_id===lease&&Date.parse(j.lease_expires_at!)>Date.now(),'coding_lease_invalid');const jobId=j.request.payload.id,workspaceId=j.request.payload.workspace_id,base={job_id:jobId,lease_id:lease};
  this.stopped=false;let root:string|undefined,sandbox:CodingSandbox|undefined;const heartbeat=setInterval(()=>{void this.rpc('repository_coding_heartbeat',workspaceId,base).then(r=>this.checked(r)).then(state=>{if(state.payload.stop||['cancelled','expired','failed','unknown'].includes(state.payload.status))throw Error('coding_stopped');}).catch(()=>{this.stopped=true;void sandbox?.close();});},20000);
  try {
   if(j.publication){const pull=await this.readback(j);need(pull,'coding_publication_unknown');const deployments=await this.github('/deployments?sha='+j.plan!.payload.commit_sha+'&environment=ScopeBlind%20coding%20preview&per_page=100');need(Array.isArray(deployments)&&deployments.length<100,'coding_deployment_ambiguous');const deployment=deployments.find((d:any)=>d.payload?.scopeblind_job_id===jobId&&d.sha===j.plan!.payload.commit_sha);need(deployment,'coding_publication_unknown');const statuses=await this.github('/deployments/'+deployment.id+'/statuses?per_page=100'),status=statuses[0];need(status?.state==='success'&&typeof status.environment_url==='string'&&status.environment_url.includes(j.plan!.payload.preview_digest),'coding_publication_unknown');const checks=await this.github('/commits/'+j.plan!.payload.commit_sha+'/check-runs?check_name=ScopeBlind%20isolated%20coding%20checks&per_page=100'),check=checks.check_runs?.find((c:any)=>c.name==='ScopeBlind isolated coding checks'&&c.app?.id===15368&&c.head_sha===j.plan!.payload.commit_sha&&c.conclusion==='success');need(check,'coding_publication_unknown');await this.result(j,pull,{url:status.environment_url,digest:j.plan!.payload.preview_digest},deployment,status,check);return true;}
   const parent=j.parent.repository.type==='scopeblind.repository.evidence.v1'?j.parent.repository.state:j.parent.repository.repository.state,proposal=parent.payload.proposal!,m=j.mandate.payload;const currentBase=await this.github('/git/ref/heads/'+encodeURIComponent(m.base_branch));need(currentBase.object?.sha===proposal.payload.base_sha,'coding_source_base_changed');
   const head=await this.github('/git/commits/'+proposal.payload.head_sha);need(head.sha===proposal.payload.head_sha&&REPOSITORY_SHA.test(head.tree?.sha),'coding_source_head_invalid');const tree=await this.github('/git/trees/'+head.tree.sha+'?recursive=1');need(tree.truncated===false&&Array.isArray(tree.tree)&&tree.tree.length<=1000,'coding_source_tree_limit');const entries=tree.tree.filter((f:any)=>f.type!=='tree');need(entries.every((f:any)=>f.type==='blob'&&['100644','100755'].includes(f.mode)&&typeof f.path==='string'&&REPOSITORY_SHA.test(f.sha)),'coding_source_unsupported');
   root=await mkdtemp(join(tmpdir(),'scopeblind-code-'));const before=new Map<string,Buffer>();let total=0;for(const f of entries){if(!C.codingSafePath(f.path))continue;need(f.size<=131072,'coding_source_file_limit');const blob=await this.github('/git/blobs/'+f.sha);need(blob.encoding==='base64'&&typeof blob.content==='string','coding_source_blob_invalid');const bytes=Buffer.from(blob.content,'base64');total+=bytes.length;need(total<=524288&&bytes.length===blob.size&&gitBlob(bytes)===f.sha,'coding_source_integrity');before.set(f.path,bytes);await mkdir(dirname(join(root,f.path)),{recursive:true});await writeFile(join(root,f.path),bytes,{mode:0o600});}
   sandbox=this.sandboxFactory(root);const history:C.RepositoryCodingModelContext['history']=[];let tests:C.RepositoryCodingTest|null=null,finished=false;
   for(let n=j.model_calls;n<m.max_model_calls;n++){need(!this.stopped&&Date.now()<Date.parse(j.started_at!)+m.max_seconds*1000,'coding_time_limit');const files=await scanCodingWorkspace(root),contextFiles=[...files].filter(([p])=>pathAllowed(p,m.allowed_paths)||m.test_command.includes(p)||m.build_command.includes(p)).map(([path,b])=>({path,content:new TextDecoder('utf-8',{fatal:true}).decode(b)}));const step=await this.rpc('repository_coding_model',workspaceId,{...base,step_id:jobId+'-'+n,context:{files:contextFiles,history:history.slice(-6)}}),action=step.reply as {action:string;path:string|null;content:string|null};if(action.action==='write_file'||action.action==='delete_file'){need(C.codingSafePath(action.path)&&pathAllowed(action.path,m.allowed_paths),'coding_edit_forbidden');await safeWrite(root,action.path,action.action==='write_file'?action.content:null);tests=null;history.push({action,result:'Applied to isolated workspace.'});}else if(action.action==='run_tests'){await this.rpc('repository_coding_heartbeat',workspaceId,{...base,stage:'testing'});const testBefore=await scanCodingWorkspace(root),test=await sandbox.run(m.test_command,Math.min(60000,Math.max(1,Date.parse(j.started_at!)+m.max_seconds*1000-Date.now())));assertCodingWorkspaceUnchanged(testBefore,await scanCodingWorkspace(root));tests={command_digest:await sha256(canonical(m.test_command)),exit_code:test.exit_code,output_sha256:await sha256(test.output),duration_ms:test.duration_ms};history.push({action,result:test.output.slice(-8000)});}else if(action.action==='finish'){need(tests?.exit_code===0,'coding_tests_required');finished=true;break;}else throw Error('coding_model_action_invalid');}
   need(finished&&tests?.exit_code===0,'coding_model_budget_exhausted');const buildBefore=await scanCodingWorkspace(root),build=await sandbox.run(m.build_command,Math.min(60000,Math.max(1,Date.parse(j.started_at!)+m.max_seconds*1000-Date.now())));need(build.exit_code===0,'coding_build_failed');const built=await scanCodingWorkspace(root);assertCodingWorkspaceUnchanged(buildBefore,built,m.preview_directory);const finalTest=await sandbox.run(m.test_command,Math.min(60000,Math.max(1,Date.parse(j.started_at!)+m.max_seconds*1000-Date.now())));need(finalTest.exit_code===0,'coding_tests_required');const after=await scanCodingWorkspace(root);assertCodingWorkspaceUnchanged(built,after);tests={command_digest:await sha256(canonical(m.test_command)),exit_code:0,output_sha256:await sha256(finalTest.output),duration_ms:finalTest.duration_ms};const changes=codingChanges(before,after,m),previewFiles=[...after].filter(([p])=>p.startsWith(m.preview_directory+'/')).map(([p,b])=>({path:p.slice(m.preview_directory.length+1),content_base64:Buffer.from(b).toString('base64'),sha256:createHash('sha256').update(b).digest('hex')}));need(previewFiles.length>0&&previewFiles.length<=64&&previewFiles.reduce((n,f)=>n+Buffer.from(f.content_base64,'base64').length,0)<=524288,'coding_preview_limit');previewFiles.sort((a,b)=>a.path<b.path?-1:a.path>b.path?1:0);const previewDigest=await sha256(canonical(previewFiles.map(f=>({path:f.path,sha256:f.sha256,bytes:Buffer.from(f.content_base64,'base64').length})))),bundle={files:previewFiles,sha256:previewDigest};
   // Git objects are constructed locally; the exact one-use gate precedes every GitHub write.
   const next=codingTree(entries,changes),seconds=Math.floor(Date.parse(j.request.payload.issued_at)/1000),message='ScopeBlind bounded coding job '+jobId,person={name:'ScopeBlind Coding Worker',email:'coding@scopeblind.com',date:new Date(seconds*1000).toISOString()},commitBody=`tree ${next.sha}\nparent ${proposal.payload.head_sha}\nauthor ${person.name} <${person.email}> ${seconds} +0000\ncommitter ${person.name} <${person.email}> ${seconds} +0000\n\n${message}\n`,commitSha=hash(Buffer.concat([Buffer.from(`commit ${Buffer.byteLength(commitBody)}\0`),Buffer.from(commitBody)]));signed=await this.checked(await this.rpc('repository_coding_get',workspaceId,{job_id:jobId}));j=signed.payload;const plan=await sign<C.RepositoryCodingPlan>({type:'scopeblind.repository.coding-plan.v1',job_id:jobId,request_digest:j.request.digest,mandate_digest:j.mandate.digest,source_head_sha:proposal.payload.head_sha,source_base_sha:proposal.payload.base_sha,branch:'scopeblind/code/'+jobId,commit_sha:commitSha,tree_sha:next.sha,files:changes,tests,build:{command_digest:await sha256(canonical(m.build_command)),exit_code:0,output_sha256:await sha256(build.output),duration_ms:build.duration_ms},preview_digest:previewDigest,model_calls:j.model_calls,reserved_tokens:j.reserved_tokens,issued_at:new Date().toISOString()},this.identity);j=(await this.checked(await this.rpc('repository_coding_publish',workspaceId,{...base,plan}))).payload;
   need(j.publication&&Date.parse(j.publication.payload.expires_at)>Date.now(),'coding_publication_expired');this.publicationUntil=Date.parse(j.publication.payload.expires_at);const preview=(await this.rpc('repository_coding_preview',workspaceId,{...base,bundle})).preview;
   for(const change of changes)if(change.after_sha){const bytes=after.get(change.path)!;const blob=await this.github('/git/blobs',{method:'POST',body:JSON.stringify({encoding:'base64',content:Buffer.from(bytes).toString('base64')})});need(blob.sha===change.after_sha,'coding_blob_mismatch');}
   for(const object of next.objects){const made=await this.github('/git/trees',{method:'POST',body:JSON.stringify({tree:object.entries})});need(made.sha===object.sha,'coding_tree_mismatch');}
   const commit=await this.github('/git/commits',{method:'POST',body:JSON.stringify({message:message+'\n',tree:next.sha,parents:[proposal.payload.head_sha],author:person,committer:person})});need(commit.sha===commitSha,'coding_commit_mismatch');need(Date.parse(j.publication.payload.expires_at)>Date.now(),'coding_publication_expired');await this.github('/git/refs',{method:'POST',body:JSON.stringify({ref:'refs/heads/'+plan.payload.branch,sha:commitSha})});
   const pull=await this.github('/pulls',{method:'POST',body:JSON.stringify({title:'Address review feedback '+jobId,head:plan.payload.branch,base:m.base_branch,draft:true,body:'Prepared under a separate bounded code-edit mandate. Requires a new exact human review before any merge. Source feedback: '+j.request.payload.source.feedback_digest})});need(pull.head?.sha===commitSha,'coding_pull_mismatch');const check=await this.github('/check-runs',{method:'POST',body:JSON.stringify({name:'ScopeBlind isolated coding checks',head_sha:commitSha,status:'completed',conclusion:'success',completed_at:new Date().toISOString(),output:{title:'Fixed isolated tests and build passed',summary:'Executed the owner-reviewed fixed commands inside a networkless container without credentials. Test output SHA256: '+tests.output_sha256+'. Build output SHA256: '+plan.payload.build.output_sha256}})});const deployment=await this.github('/deployments',{method:'POST',body:JSON.stringify({ref:commitSha,auto_merge:false,required_contexts:[],environment:'ScopeBlind coding preview',transient_environment:true,production_environment:false,payload:{scopeblind_job_id:jobId,preview_digest:previewDigest}})});need(Number.isSafeInteger(deployment.id),'coding_deployment_invalid');const deploymentStatus=await this.github('/deployments/'+deployment.id+'/statuses',{method:'POST',body:JSON.stringify({state:'success',environment_url:preview.url,description:'Content-addressed static preview from isolated build.',auto_inactive:false})});need(deploymentStatus.state==='success','coding_deployment_invalid');await this.result(j,pull,preview,deployment,deploymentStatus,check);return true;
  }catch(error){const code=error instanceof Error&&/^[a-z0-9_]{3,80}$/.test(error.message)?error.message:'coding_worker_interrupted';await this.rpc('repository_coding_complete',workspaceId,{...base,error:code}).catch(()=>{});return true;}finally{this.publicationUntil=0;clearInterval(heartbeat);await sandbox?.close();if(root)await rm(root,{recursive:true,force:true});}
 }
}
export async function runRepositoryCoding(args=process.argv.slice(2)){
 let file:string|undefined,jobId=process.env.JOB_ID;for(let i=0;i<args.length;i++){if(args[i]==='--config'&&!file&&args[i+1])file=args[++i];else if(args[i]==='--job'&&args[i+1])jobId=args[++i];else throw Error('coding_argument_invalid');}
 const raw=file?await readFile(file,'utf8'):process.env.SCOPEBLIND_CODING_CONNECTION,key=process.env.SCOPEBLIND_CODING_WORKER_KEY,token=process.env.GITHUB_TOKEN;need(raw&&key&&token,'coding_configuration_required');const config=JSON.parse(raw) as RepositoryCodingConfig,identity=await importIdentity(key,config.worker_key);const runner=new RepositoryCodingRunner(config,identity,token);await runner.runOne(jobId);
}
