import {describe,it,expect} from 'vitest';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {fileURLToPath} from 'node:url';
import {generateIdentity,bytesToHex} from './coordination-protocol.js';import {renderGuidedCodingWorkflow} from './repository-connect-workflow.js';
import {DockerCodingSandbox,codingChanges,codingTree,gitBlob,scanCodingWorkspace,assertCodingWorkspaceUnchanged} from './repository-coding-runner.js';
import {codingSafePath,validRepositoryCodingMandate,type RepositoryCodingMandate,CODING_PERMISSIONS} from './coordination-repository-coding.js';
const key=(c:string)=>c.repeat(64),mandate=():RepositoryCodingMandate=>({type:'scopeblind.repository.coding-mandate.v1',id:'coding-mandate-001',workspace_id:'workspace-001',workspace_digest:key('d'),mode:'edit_code',owner_member_id:'owner-member-001',owner_key:key('a'),owner_member_revision:1,reviewer_member_id:'reviewer-member-001',reviewer_key:key('b'),reviewer_member_revision:1,worker_key:key('c'),repository:'scopeblind/coding',base_branch:'main',allowed_paths:['site/**'],required_checks:[{name:'ScopeBlind isolated coding checks',app_id:15368}],runtime:'node22-static-v1',docker_image:'node@sha256:'+key('1'),test_command:['node','--test','tests/site.test.mjs'],build_command:['node','tools/build.mjs'],preview_directory:'dist',max_jobs:2,max_attempts:2,max_model_calls:3,max_tokens:65536,max_seconds:300,max_changed_files:3,max_changed_bytes:32768,permissions:[...CODING_PERMISSIONS],issued_at:'2026-09-16T00:00:00.000Z',expires_at:'2026-09-16T01:00:00.000Z'});
describe('bounded coding controller',()=>{
 it('executes the generated workflow CLI with --config and restricts readiness polling to its exact JOB_ID',async()=>{const dir=await mkdtemp(join(tmpdir(),'coding-cli-'));try{const pair=await crypto.subtle.generateKey('Ed25519',true,['sign','verify']) as CryptoKeyPair,identity={publicKey:bytesToHex(new Uint8Array(await crypto.subtle.exportKey('raw',pair.publicKey)))},key=bytesToHex(new Uint8Array(await crypto.subtle.exportKey('pkcs8',pair.privateKey))),config={type:'scopeblind.repository.coding-config.v1',endpoint:'https://scopeblind.example/api/coordination',authority_key:'b'.repeat(64),worker_key:identity.publicKey,repository:'scopeblind/coding',base_branch:'main',runtime:'node22-static-v1',docker_image:'node@sha256:'+'a'.repeat(64),test_command:['node','--test','tests/site.test.mjs'],build_command:['node','tools/build.mjs'],preview_directory:'dist'};await writeFile(join(dir,'coding.json'),JSON.stringify(config));await writeFile(join(dir,'fixture.mjs'),"import {writeFileSync} from 'node:fs';globalThis.fetch=async(url,init)=>{const request=JSON.parse(init.body).request;writeFileSync('request.json',JSON.stringify(request.payload));return Response.json({ok:true,job:null});};");const {build}=await import('esbuild');await build({entryPoints:[fileURLToPath(new URL('./repository-coding-cli.ts',import.meta.url))],outfile:join(dir,'coding.cjs'),bundle:true,platform:'node',format:'cjs',logLevel:'silent'});const workflow=renderGuidedCodingWorkflow({url:'https://scopeblind.com/releases/repository-coding-0.24.0.cjs',sha256:'1'.repeat(64)},{url:'https://scopeblind.com/releases/repository-receiver-0.24.0.cjs',sha256:'2'.repeat(64)}),command=workflow.match(/node coding\.cjs[^\n]*/)?.[0];expect(command).toBe('node coding.cjs --config coding.json');await promisify(execFile)(process.execPath,['--import',join(dir,'fixture.mjs'),...command!.split(' ').slice(1)],{cwd:dir,env:{PATH:process.env.PATH,GITHUB_TOKEN:'local-test',SCOPEBLIND_CODING_WORKER_KEY:key,JOB_ID:'setup-readiness-001'}});const request=JSON.parse(await readFile(join(dir,'request.json'),'utf8'));expect(request.action).toBe('repository_coding_poll');expect(request.room_id).toBe('repository-coding');expect(request.body.job_id).toBe('setup-readiness-001');}finally{await rm(dir,{recursive:true,force:true});}});

 it('rejects source mutations caused by tests or build and preserves exact final preview bytes',()=>{const before=new Map([['site/main.js',Buffer.from('tested')],['dist/index.html',Buffer.from('built')]]),changed=new Map(before);changed.set('site/main.js',Buffer.from('not tested'));expect(()=>assertCodingWorkspaceUnchanged(before,changed,'dist')).toThrow('coding_test_or_build_modified_source');const previewChanged=new Map(before);previewChanged.set('dist/index.html',Buffer.from('replaced after build'));expect(()=>assertCodingWorkspaceUnchanged(before,previewChanged)).toThrow('coding_test_or_build_modified_source');expect(()=>assertCodingWorkspaceUnchanged(before,previewChanged,'dist')).not.toThrow();});
 it('bounds aggregate scan bytes and directory depth before collecting hostile output',async()=>{const dir=await mkdtemp(join(tmpdir(),'coding-scan-'));try{for(let i=0;i<5;i++)await writeFile(join(dir,`${i}.txt`),Buffer.alloc(524288));await expect(scanCodingWorkspace(dir)).rejects.toThrow('coding_workspace_byte_limit');await rm(dir,{recursive:true,force:true});await mkdir(join(dir,...Array(11).fill('deep')),{recursive:true});await expect(scanCodingWorkspace(dir)).rejects.toThrow('coding_directory_depth_limit');}finally{await rm(dir,{recursive:true,force:true});}});

 it('requires separate exact edit permissions, pinned runtime, and immutable test/build definitions',()=>{const m=mandate();expect(validRepositoryCodingMandate(m)).toBe(true);for(const change of [{permissions:['read_task','prepare_review']},{docker_image:'node:22'},{allowed_paths:['tests/**']},{allowed_paths:['tools/**']},{allowed_paths:['dist/**']},{required_checks:[null]},{max_model_calls:13}])expect(validRepositoryCodingMandate({...m,...change})).toBe(false);});
 it('blocks repository secrets and workflow paths even with case changes',()=>{for(const path of ['.github/workflows/test.yml','.GITHUB/workflows/test.yml','site/.env','site/.ENV.local','site/token.pem','site/../test.js','node_modules/a.js'])expect(codingSafePath(path)).toBe(false);});
 it('rejects hidden out-of-scope mutations while allowing a bounded source diff and separate build output',()=>{const before=new Map([['site/index.html',Buffer.from('old')],['tools/build.mjs',Buffer.from('fixed')]]),after=new Map(before);after.set('site/index.html',Buffer.from('new'));after.set('dist/index.html',Buffer.from('preview'));expect(codingChanges(before,after,mandate())).toEqual([{path:'site/index.html',before_sha:gitBlob(Buffer.from('old')),after_sha:gitBlob(Buffer.from('new')),bytes:3}]);const deleted=new Map(before);deleted.delete('site/index.html');expect(codingChanges(before,deleted,mandate())[0].bytes).toBe(3);after.set('tools/build.mjs',Buffer.from('changed'));expect(()=>codingChanges(before,after,mandate())).toThrow('coding_diff_outside_scope');});
 it('preserves untouched workflow blobs and original executable modes in computed Git trees',()=>{const entries=[{path:'.github/workflows/test.yml',mode:'100644',sha:'1'.repeat(40)},{path:'site/script.js',mode:'100755',sha:'2'.repeat(40)}],next=codingTree(entries,[{path:'site/script.js',after_sha:'3'.repeat(40)}]);expect(next.objects.find(x=>x.path==='.github/workflows/')!.entries[0].sha).toBe('1'.repeat(40));expect(next.objects.find(x=>x.path==='site/')!.entries[0]).toMatchObject({mode:'100755',sha:'3'.repeat(40)});});
 it('runs with no network, privilege or credentials, and removes a named container after timeout',async()=>{const calls:Array<{file:string;args:string[];options:any}>=[],box=new DockerCodingSandbox('/tmp/isolated-test','node@sha256:'+key('1'),async(file,args,options)=>{calls.push({file,args,options});if(args[0]==='run')throw Object.assign(new Error('timeout'),{code:'ETIMEDOUT',stdout:'partial'});return {stdout:'',stderr:''};});expect((await box.run(['node','--test','tests/site.test.mjs'],50)).exit_code).toBe(124);expect(calls).toHaveLength(2);const run=calls[0];expect(run.options.env).toEqual({PATH:process.env.PATH});expect(run.args).toContain('--read-only');expect(run.args.slice(run.args.indexOf('--network'),run.args.indexOf('--network')+2)).toEqual(['--network','none']);expect(run.args).not.toContain('--env');expect(calls[1].args).toEqual(['rm','--force',run.args[run.args.indexOf('--name')+1]]);await box.close();await expect(box.run(['node','tools/build.mjs'],50)).rejects.toThrow('coding_sandbox_closed');});
});
