/** ScopeBlind-owned fixed-repository controller. No visitor credentials or arbitrary workflow input. */
import {canonical,importIdentity,makeRequest,sha256,sign,verify,type Signed,type SigningIdentity,type RpcAction} from './coordination-protocol.js';
import {REPOSITORY_HEX,REPOSITORY_ID,REPOSITORY_SHA,verifyRepositoryEvidence} from './coordination-repository.js';
import {verifyRepositoryWorkspaceState} from './coordination-repository-workspace.js';
import {verifyRepositoryCodingEvidence} from './coordination-repository-coding-evidence.js';
import {RepositoryReceiver} from './repository-receiver.js';
import {RepositoryCodingRunner,gitBlob,type CodingSandbox} from './repository-coding-runner.js';
import * as T from './coordination-repository-trial.js';
import {TRIAL_BEFORE_HTML,TRIAL_SOURCE_HTML,TRIAL_TEST_SOURCE,TRIAL_BUILD_SOURCE} from './repository-trial-template.js';
function need(ok:unknown,code:string):asserts ok{if(!ok)throw Error(code);}
export interface RepositoryTrialRunnerConfig {endpoint:string;authority_key:string;receiver_key:string;worker_key:string;template_sha:string;workflow_sha:string}
export interface RepositoryTrialRun {run_id:number;run_attempt:number;workflow_ref:string;workflow_sha:string;oidc:(audience:string)=>Promise<string>}
async function json(response:Response,max=4000000):Promise<any>{const reader=response.body?.getReader();need(reader,'trial_response_empty');const parts:Uint8Array[]=[];let size=0;try{for(;;){const p=await reader.read();if(p.done)break;size+=p.value.length;need(size<=max,'trial_response_limit');parts.push(p.value);}}finally{await reader.cancel().catch(()=>{});}return JSON.parse(Buffer.concat(parts).toString('utf8'));}
export class RepositoryTrialRunner {
 constructor(readonly config:RepositoryTrialRunnerConfig,private receiver:SigningIdentity,private worker:SigningIdentity,private token:string,private run:RepositoryTrialRun,private fetcher:typeof fetch=fetch,private sandboxFactory?:((dir:string)=>CodingSandbox)){
  const u=new URL(config.endpoint);need(u.protocol==='https:'&&u.pathname==='/api/coordination'&&!u.username&&!u.password&&!u.search&&!u.hash,'trial_endpoint_invalid');need([config.authority_key,config.receiver_key,config.worker_key].every(k=>REPOSITORY_HEX.test(k))&&new Set([config.authority_key,config.receiver_key,config.worker_key]).size===3&&receiver.publicKey===config.receiver_key&&worker.publicKey===config.worker_key&&REPOSITORY_SHA.test(config.template_sha)&&REPOSITORY_SHA.test(config.workflow_sha)&&run.workflow_sha===config.workflow_sha&&run.workflow_ref===`${T.TRIAL_REPOSITORY}/${T.TRIAL_WORKFLOW}@refs/heads/main`&&token,'trial_runner_pins_invalid');
 }
 private async rpc(action:string,id:string,body:Record<string,unknown>,identity=this.receiver){const request=await sign(makeRequest(action as RpcAction,id,body),identity),r=await this.fetcher(this.config.endpoint,{method:'POST',headers:{'content-type':'application/json','x-scopeblind-action':action},body:JSON.stringify({request}),redirect:'error',signal:AbortSignal.timeout(55000)}),value=await json(r);need(r.ok&&value.ok===true,typeof value.error==='string'?value.error:'trial_service_refused');return value;}
 private async github(path:string,init:RequestInit={},missing=false){const r=await this.fetcher('https://api.github.com'+path,{...init,headers:{authorization:'Bearer '+this.token,accept:'application/vnd.github+json','content-type':'application/json','x-github-api-version':'2026-03-10'},redirect:'error',signal:AbortSignal.timeout(20000)});if(missing&&r.status===404){await r.body?.cancel();return null;}const value=await json(r);need(r.ok,'trial_github_'+r.status);return value;}
 private get repo(){return '/repos/'+T.TRIAL_REPOSITORY;}
 private async ref(branch:string){return (await this.github(this.repo+'/git/ref/heads/'+encodeURIComponent(branch),{},true))?.object?.sha??null;}
 private async blob(path:string,sha:string){const file=await this.github(this.repo+'/contents/'+path+'?ref='+sha);need(file.type==='file'&&file.encoding==='base64'&&file.size<=65536,'trial_file_invalid');const b=Buffer.from(file.content,'base64');need(b.length===file.size&&gitBlob(b)===file.sha,'trial_blob_mismatch');return {bytes:b,sha:file.sha};}
 private async ensureRef(branch:string,sha:string){const old=await this.ref(branch);if(old){need(old===sha,'trial_ref_conflict');return;}try{await this.github(this.repo+'/git/refs',{method:'POST',body:JSON.stringify({ref:'refs/heads/'+branch,sha})});}catch(error){if(await this.ref(branch)!==sha)throw error;}need(await this.ref(branch)===sha,'trial_ref_readback_mismatch');}
 private async checked(value:Signed<T.RepositoryTrialJob>,lease:string){need(value&&await verify(value,this.config.authority_key),'trial_job_signature_invalid');const j=value.payload,r=j.request?.payload;need(j.type==='scopeblind.repository.trial-job.v1'&&T.validRepositoryTrialRequest(r)&&r.authority_key===this.config.authority_key&&await verify(j.request,r.owner_key)&&j.lease_id===lease&&Date.parse(j.lease_expires_at)>Date.now()&&j.receiver_key===this.receiver.publicKey&&j.template_sha===this.config.template_sha&&canonical(j.config)===canonical(T.trialCodingConfig(r.id,this.config.endpoint,this.config.authority_key,this.worker.publicKey))&&j.proof.workflow_sha===this.config.workflow_sha&&j.proof.workflow_ref===this.run.workflow_ref&&j.proof.run_id===this.run.run_id&&j.proof.run_attempt===this.run.run_attempt,'trial_job_scope_mismatch');
  need(j.kind==='reconcile'||j.kind==='coding_reconcile'||Date.parse(r.expires_at)>Date.now(),'trial_expired');if(j.workspace){need(await verifyRepositoryWorkspaceState(j.workspace,this.config.authority_key),'trial_workspace_invalid');const w=j.workspace.payload.workspace.payload;need(w.owner_key===r.owner_key&&w.repository===T.TRIAL_REPOSITORY&&w.base_branch===T.trialBase(r.id)&&w.receiver_key===this.receiver.publicKey,'trial_workspace_mismatch');}
  if(j.provision)need(T.validRepositoryTrialProvision(j.provision.payload)&&await verify(j.provision,this.receiver.publicKey)&&j.provision.payload.request_digest===j.request.digest&&j.provision.payload.trial_id===r.id,'trial_provision_invalid');return j;
 }
 async provision(j:T.RepositoryTrialJob):Promise<Signed<T.RepositoryTrialProvision>>{
  const r=j.request.payload;need(j.kind==='provision'&&!j.target_id,'trial_provision_scope_mismatch');const template=await this.github(this.repo+'/git/commits/'+this.config.template_sha);need(template.sha===this.config.template_sha&&REPOSITORY_SHA.test(template.tree?.sha),'trial_template_invalid');
  for(const [path,expected] of [['site/index.html',TRIAL_BEFORE_HTML],['tests/contact.test.cjs',TRIAL_TEST_SOURCE],['tools/build.cjs',TRIAL_BUILD_SOURCE]])need((await this.blob(path,this.config.template_sha)).bytes.toString('utf8')===expected,'trial_template_bytes_changed');
  const baseBranch=T.trialBase(r.id),sourceBranch=T.trialSource(r.id);await this.ensureRef(baseBranch,this.config.template_sha);
  const tree=await this.github(this.repo+'/git/trees',{method:'POST',body:JSON.stringify({base_tree:template.tree.sha,tree:[{path:'site/index.html',mode:'100644',type:'blob',content:TRIAL_SOURCE_HTML}]})});need(REPOSITORY_SHA.test(tree.sha),'trial_tree_invalid');
  const person={name:'ScopeBlind Trial',email:'trial@scopeblind.com',date:new Date(Math.floor(Date.parse(r.issued_at)/1000)*1000).toISOString()},commit=await this.github(this.repo+'/git/commits',{method:'POST',body:JSON.stringify({message:'Unfinished managed trial '+r.id,tree:tree.sha,parents:[this.config.template_sha],author:person,committer:person})});need(REPOSITORY_SHA.test(commit.sha)&&commit.tree?.sha===tree.sha&&commit.parents?.length===1&&commit.parents[0].sha===this.config.template_sha,'trial_commit_invalid');await this.ensureRef(sourceBranch,commit.sha);need((await this.blob('site/index.html',commit.sha)).bytes.toString('utf8')===TRIAL_SOURCE_HTML,'trial_source_bytes_changed');
  let pulls=await this.github(this.repo+'/pulls?state=all&head='+encodeURIComponent('ScopeBlind:'+sourceBranch)+'&base='+encodeURIComponent(baseBranch)+'&per_page=100');need(Array.isArray(pulls)&&pulls.length<=1,'trial_pull_ambiguous');let pull=pulls[0];if(!pull){try{pull=await this.github(this.repo+'/pulls',{method:'POST',body:JSON.stringify({title:r.title,head:sourceBranch,base:baseBranch,draft:false,body:'Disposable styled starter for a shared AI coding trial. This initial change is deterministic and intentionally unfinished. A separate signed coding mandate and later exact review are required.'})});}catch(error){pulls=await this.github(this.repo+'/pulls?state=all&head='+encodeURIComponent('ScopeBlind:'+sourceBranch)+'&base='+encodeURIComponent(baseBranch)+'&per_page=100');if(!Array.isArray(pulls)||pulls.length!==1)throw error;pull=pulls[0];}}
  need(pull.state==='open'&&!pull.draft&&pull.head?.sha===commit.sha&&pull.head?.ref===sourceBranch&&pull.base?.ref===baseBranch&&pull.base?.repo?.full_name===T.TRIAL_REPOSITORY&&pull.head?.repo?.full_name===T.TRIAL_REPOSITORY,'trial_pull_mismatch');
  const checkRows=await this.github(this.repo+'/commits/'+commit.sha+'/check-runs?per_page=100&filter=latest');let check=checkRows.check_runs?.find((c:any)=>c.name===T.TRIAL_SOURCE_CHECK.name&&c.app?.id===15368&&c.head_sha===commit.sha&&c.conclusion==='success');if(!check){need(TRIAL_SOURCE_HTML.includes('href="#contact"')&&!/\bid=["']contact["']/.test(TRIAL_SOURCE_HTML)&&!/<script\b|<form\b|@import\b|url\s*\(/i.test(TRIAL_SOURCE_HTML),'trial_source_safety_failed');check=await this.github(this.repo+'/check-runs',{method:'POST',body:JSON.stringify({name:T.TRIAL_SOURCE_CHECK.name,head_sha:commit.sha,status:'completed',conclusion:'success',output:{title:'Reviewed starter bytes match',summary:'The exact fixed static starter and immutable test/build definitions were checked. The contact destination is intentionally absent; improvement tests have not passed and no AI repair is claimed.'}})});}
  need(check.app?.id===15368&&check.head_sha===commit.sha&&check.conclusion==='success','trial_source_check_invalid');const html=async(value:string)=>({html:value,sha256:await sha256(value),blob_sha:gitBlob(Buffer.from(value))});return sign<T.RepositoryTrialProvision>({type:'scopeblind.repository.trial-provision.v1',trial_id:r.id,request_digest:j.request.digest,receiver_key:this.receiver.publicKey,repository:T.TRIAL_REPOSITORY,template_sha:this.config.template_sha,base_branch:baseBranch,source_branch:sourceBranch,base_sha:this.config.template_sha,source_sha:commit.sha,pull_number:pull.number,before:await html(TRIAL_BEFORE_HTML),source:await html(TRIAL_SOURCE_HTML),source_check:{id:check.id,name:T.TRIAL_SOURCE_CHECK.name,app_id:15368,head_sha:commit.sha,conclusion:'success'},observed_at:new Date().toISOString()},this.receiver);
 }
 private async receive(j:T.RepositoryTrialJob){need(j.workspace&&j.assignment&&j.task&&j.provision&&j.target_id===j.task.payload.task.payload.id,'trial_task_required');need((await verifyRepositoryEvidence({type:'scopeblind.repository.evidence.v1',state:j.task},this.config.authority_key)).valid,'trial_task_invalid');const w=j.workspace.payload,a=j.assignment.payload,t=j.task.payload.task.payload,r=j.request.payload;need(await verify(j.assignment,r.owner_key)&&a.workspace_id===w.workspace.payload.id&&a.workspace_digest===w.workspace.digest&&a.task_digest===j.task.payload.task.digest&&a.owner_key===r.owner_key&&a.reviewer_key===j.task.payload.reviewer?.payload.reviewer_key&&w.assignments.some(x=>x.digest===j.assignment!.digest),'trial_assignment_invalid');if(j.kind!=='reconcile')for(const [memberId,key,revision,role] of [[a.owner_member_id,a.owner_key,a.owner_member_revision,'owner'],[a.reviewer_member_id,a.reviewer_key,a.reviewer_member_revision,'reviewer']] as const)need(w.members.some(m=>m.member_id===memberId&&m.current_key===key&&m.revision===revision&&m.role===role&&m.status==='active'),'trial_membership_changed');
  need(t.repository===T.TRIAL_REPOSITORY&&t.base_branch===T.trialBase(r.id)&&t.owner_key===r.owner_key&&t.receiver_key===this.receiver.publicKey&&canonical(t.allowed_paths)===canonical(['site/**']),'trial_task_scope_mismatch');const source=t.pull_number===j.provision.payload.pull_number;need(canonical(t.required_checks)===canonical([source?T.TRIAL_SOURCE_CHECK:T.TRIAL_CODING_CHECK]),'trial_checks_mismatch');if(!source)need(j.coding&&(await verifyRepositoryCodingEvidence({type:'scopeblind.repository.coding-evidence.v1',job:j.coding},this.config.authority_key)).published&&j.coding.payload.request.payload.workspace_id===w.workspace.payload.id&&j.coding.payload.result!.payload.pull_number===t.pull_number,'trial_child_origin_invalid');need(j.kind!=='execute'||!source,'trial_source_effect_refused');
  const receiver=new RepositoryReceiver({type:'scopeblind.repository.receiver-config.v1',endpoint:this.config.endpoint,authority_key:this.config.authority_key,owner_key:r.owner_key,reviewer_key:a.reviewer_key,receiver_key:this.receiver.publicKey,repository:T.TRIAL_REPOSITORY,base_branch:T.trialBase(r.id)},this.receiver,this.token,this.fetcher);if(j.kind==='inspect')await receiver.inspect(t.id);else if(j.kind==='execute')await receiver.execute(t.id);else await receiver.reconcile(t.id);
 }
 private async refreshReady(j:T.RepositoryTrialJob,resultDigest:string){
  const audience='https://scopeblind.com/repository-trial/'+j.lease_id,oidc_token=await this.run.oidc(audience),response=(await this.rpc('repository_trial_poll','repository-trial',{lease_id:j.lease_id,run_id:this.run.run_id,run_attempt:this.run.run_attempt,oidc_token,refresh_only:true})).poll as Signed<T.RepositoryTrialPoll>;
  need(response&&await verify(response,this.config.authority_key)&&response.payload.lease_id===j.lease_id&&response.payload.job,'trial_ready_lease_required');const current=await this.checked(response.payload.job,j.lease_id),c=current.coding,w=current.workspace?.payload,m=c?.payload.mandate.payload;
  need(current.id===j.id&&current.kind===j.kind&&current.target_id===j.target_id&&c?.payload.result?.digest===resultDigest&&c.payload.stop===null&&w&&m&&Date.parse(m.expires_at)>Date.now()&&Date.parse(current.request.payload.expires_at)>Date.now()&&Math.abs(Date.now()-Date.parse(current.observed_at))<=30000,'trial_coding_ready_authority_inactive');
  for(const [memberId,key,revision,role]of[[m.owner_member_id,m.owner_key,m.owner_member_revision,'owner'],[m.reviewer_member_id,m.reviewer_key,m.reviewer_member_revision,'reviewer']]as const)need(w.members.some(x=>x.member_id===memberId&&x.current_key===key&&x.revision===revision&&x.role===role&&x.status==='active'),'trial_coding_ready_authority_inactive');
 }
 private async coding(j:T.RepositoryTrialJob){need(j.coding&&j.workspace&&j.target_id===j.coding.payload.request.payload.id&&(await verifyRepositoryCodingEvidence({type:'scopeblind.repository.coding-evidence.v1',job:j.coding},this.config.authority_key)).valid&&j.coding.payload.request.payload.workspace_id===j.workspace.payload.workspace.payload.id,'trial_coding_scope_mismatch');const m=j.coding.payload.mandate.payload;need(m.owner_key===j.request.payload.owner_key&&m.repository===T.TRIAL_REPOSITORY&&m.base_branch===T.trialBase(j.request.payload.id)&&m.worker_key===this.worker.publicKey&&canonical(m.allowed_paths)===canonical(['site/**'])&&canonical(m.required_checks)===canonical([T.TRIAL_CODING_CHECK])&&Object.entries(T.TRIAL_LIMITS).every(([k,v])=>(m as any)[k]<=v),'trial_coding_limits_mismatch');
  need(!['coding_reconcile','coding_ready'].includes(j.kind)||j.coding.payload.publication,'trial_coding_publication_required');if(j.kind==='coding_ready')need(j.coding.payload.result,'trial_coding_result_required');else if(!j.coding.payload.result){const runner=new RepositoryCodingRunner(j.config,this.worker,this.token,this.fetcher,this.sandboxFactory);await runner.runOne(j.target_id!);}const current=(await this.rpc('repository_coding_get',m.workspace_id,{job_id:j.target_id},this.worker)).job as Signed<import('./coordination-repository-coding.js').RepositoryCodingJob>;need((await verifyRepositoryCodingEvidence({type:'scopeblind.repository.coding-evidence.v1',job:current},this.config.authority_key)).published,'trial_coding_not_published');const result=current.payload.result!.payload,pull=await this.github(this.repo+'/pulls/'+result.pull_number);need(pull.head?.sha===result.head_sha&&pull.head?.ref===result.branch&&pull.base?.ref===T.trialBase(j.request.payload.id)&&pull.base?.sha===current.payload.plan!.payload.source_base_sha&&await this.ref(T.trialBase(j.request.payload.id))===current.payload.plan!.payload.source_base_sha&&pull.state==='open'&&pull.base?.repo?.full_name===T.TRIAL_REPOSITORY&&pull.head?.repo?.full_name===T.TRIAL_REPOSITORY,'trial_coding_pull_changed');if(pull.draft){need(j.kind!=='coding_reconcile','trial_coding_ready_required');need(typeof pull.node_id==='string','trial_pull_node_missing');await this.refreshReady(j,current.payload.result!.digest);const marked=await this.github('/graphql',{method:'POST',body:JSON.stringify({query:'mutation($id:ID!){markPullRequestReadyForReview(input:{pullRequestId:$id}){pullRequest{id isDraft}}}',variables:{id:pull.node_id}})});need(!marked.errors?.length&&marked.data?.markPullRequestReadyForReview?.pullRequest?.id===pull.node_id&&marked.data.markPullRequestReadyForReview.pullRequest.isDraft===false,'trial_ready_readback_required');}const after=await this.github(this.repo+'/pulls/'+result.pull_number);need(after.draft===false&&after.head?.sha===result.head_sha&&after.base?.ref===T.trialBase(j.request.payload.id)&&after.base?.sha===current.payload.plan!.payload.source_base_sha&&await this.ref(T.trialBase(j.request.payload.id))===current.payload.plan!.payload.source_base_sha,'trial_ready_readback_required');
 }
 async runOne(){const lease=crypto.randomUUID(),initial=(await this.rpc('repository_trial_poll','repository-trial',{lease_id:lease})).poll as Signed<T.RepositoryTrialPoll>;need(initial&&await verify(initial,this.config.authority_key)&&initial.payload.lease_id===lease&&initial.payload.challenge.audience==='https://scopeblind.com/repository-trial/'+lease,'trial_challenge_invalid');const token=await this.run.oidc(initial.payload.challenge.audience),response=(await this.rpc('repository_trial_poll','repository-trial',{lease_id:lease,run_id:this.run.run_id,run_attempt:this.run.run_attempt,oidc_token:token})).poll as Signed<T.RepositoryTrialPoll>;need(response&&await verify(response,this.config.authority_key)&&response.payload.lease_id===lease,'trial_poll_invalid');if(!response.payload.job)return false;const j=await this.checked(response.payload.job,lease);let provision:Signed<T.RepositoryTrialProvision>|null=null,error:string|null=null;try{if(j.kind==='provision')provision=await this.provision(j);else if(j.kind==='coding'||j.kind==='coding_reconcile'||j.kind==='coding_ready')await this.coding(j);else await this.receive(j);}catch(e){error=e instanceof Error&&/^[a-z0-9_]{3,100}$/.test(e.message)?e.message:'trial_runner_interrupted';}
  const completion=await sign<T.RepositoryTrialCompletion>({type:'scopeblind.repository.trial-completion.v1',job_id:j.id,trial_id:j.request.payload.id,request_digest:j.request.digest,lease_id:lease,receiver_key:this.receiver.publicKey,kind:j.kind,provision,error,observed_at:new Date().toISOString()},this.receiver);await this.rpc('repository_trial_complete','repository-trial',{completion});if(error)throw Error(error);return true;
 }
}
export async function runRepositoryTrial(){const e=process.env;need(e.GITHUB_ACTIONS==='true'&&e.GITHUB_REPOSITORY===T.TRIAL_REPOSITORY&&e.GITHUB_REF==='refs/heads/main'&&e.GITHUB_EVENT_NAME==='workflow_dispatch','trial_trusted_workflow_required');const config=JSON.parse(e.SCOPEBLIND_TRIAL_CONFIG||'null') as RepositoryTrialRunnerConfig;need(config&&e.SCOPEBLIND_TRIAL_RECEIVER_KEY&&e.SCOPEBLIND_TRIAL_WORKER_KEY&&e.GITHUB_TOKEN&&e.ACTIONS_ID_TOKEN_REQUEST_URL&&e.ACTIONS_ID_TOKEN_REQUEST_TOKEN,'trial_configuration_required');const run:RepositoryTrialRun={run_id:Number(e.GITHUB_RUN_ID),run_attempt:Number(e.GITHUB_RUN_ATTEMPT),workflow_ref:e.GITHUB_WORKFLOW_REF!,workflow_sha:e.GITHUB_WORKFLOW_SHA!,oidc:async audience=>{const u=new URL(e.ACTIONS_ID_TOKEN_REQUEST_URL!);need(u.protocol==='https:'&&u.hostname.endsWith('.actions.githubusercontent.com')&&!u.username&&!u.password,'trial_oidc_endpoint_invalid');u.searchParams.set('audience',audience);const r=await fetch(u,{headers:{authorization:'Bearer '+e.ACTIONS_ID_TOKEN_REQUEST_TOKEN},redirect:'error',signal:AbortSignal.timeout(20000)}),v=await json(r,40000);need(r.ok&&typeof v.value==='string','trial_oidc_unavailable');return v.value;}};const runner=new RepositoryTrialRunner(config,await importIdentity(e.SCOPEBLIND_TRIAL_RECEIVER_KEY,config.receiver_key),await importIdentity(e.SCOPEBLIND_TRIAL_WORKER_KEY,config.worker_key),e.GITHUB_TOKEN,run);const leaseUntil=Date.now()+30*60000;for(let count=0;count<6&&Date.now()<leaseUntil;count++)if(!await runner.runOne())break;process.stdout.write('The managed trial controller finished its bounded queue pass.\n');}
